### ISSUE TITLE
Can't login using Android App

### ISSUE THREAD

**Issue by CapSel** [immich-app/immich#10202]
### The bug

Can't login using android app. Apps on iOS not affected - I was not logged out. I can login and logout via Web.

### The OS that Immich Server is running on

ArchLinux

### Version of Immich Server

1.106.2

### Version of Immich Mobile App

1.105.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
Not sure - today it does not work.
I've been using immich server via web, ios apps and android app for long time now.
```

### Relevant log output

```shell
2024-06-12 12:56:42.183491 | SEVERE   | AuthenticationNotifier | Unable to get user information from the server. |
2024-06-12 12:56:42.183350 | SEVERE   | AuthenticationNotifier | Error getting user information from the server [API EXCEPTION] | ApiException 404: {"message":"Cannot GET /api/user/me","error":"Not Found","statusCode":404,"correlationId":"gguynsxn"} |
#0      UserApi.getMyUserInfo (package:openapi/api/user_api.dart:289)
<asynchronous suspension>
#1      AuthenticationNotifier.setSuccessLoginInfo (package:immich_mobile/providers/authentication.provider.dart:183)
<asynchronous suspension>
#2      LoginForm.build.login (package:immich_mobile/widgets/forms/login_form.dart:156)
<asynchronous suspension>

2024-06-12 12:56:41.503325 | INFO     | ApiService           | Pinging server with response code 200 |
2024-06-12 12:56:17.304249 | INFO     | ApiService           | Pinging server with response code 200 |
2024-06-12 12:56:17.304249 | INFO     | ApiService           | Pinging server with response code 200 |
```

### Additional information

I still can't find logs on immich server ;)

**Comment by CapSel** [comment]
It seems that yet again f-droid app distribution lags behind. Thank you (:
