### ISSUE TITLE
Unable to upload Apple Live Photos 

### ISSUE THREAD

**Issue by lbp0** [immich-app/immich#10952]
### The bug

When I upload a live photo, it becomes into a video without thumbnail like this:
![IMG_1183](https://github.com/immich-app/immich/assets/14981936/4adcce5f-ea5a-40ae-b559-df774354a981)

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.1 build.162

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.dockerproxy.com/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.dockerproxy.com/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.dockerproxy.com/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/lbp12345/Pictures

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.Upload Live Photo
```

### Relevant log output

```shell
2024-07-08 10:48:41.083373 | INFO     | AssetNotifier        | Load assets: 358ms |
2024-07-08 10:48:41.083343 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 10:48:41.042187 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 10:48:41.042156 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 10:48:40.911902 | INFO     | SyncService          | Upserted 1 assets into the DB |
2024-07-08 10:48:40.750781 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:48:40.750381 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:48:40.730503 | INFO     | BackupNotifier       | [_resumeBackup] Start back up |
2024-07-08 10:42:20.746689 | INFO     | AssetNotifier        | Load assets: 305ms |
2024-07-08 10:42:20.746660 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 10:42:20.731214 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 10:42:20.731147 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 10:42:20.620796 | INFO     | SyncService          | Upserted 1 assets into the DB |
2024-07-08 10:42:20.465197 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:42:20.463450 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:42:20.443448 | INFO     | BackupNotifier       | [_resumeBackup] Start back up |
2024-07-08 10:42:20.746689 | INFO     | AssetNotifier        | Load assets: 305ms |
2024-07-08 10:42:20.746660 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 10:42:20.731214 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 10:42:20.731147 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 10:42:20.620796 | INFO     | SyncService          | Upserted 1 assets into the DB |
2024-07-08 10:42:20.465197 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:42:20.463450 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:42:20.443448 | INFO     | BackupNotifier       | [_resumeBackup] Start back up |
2024-07-08 10:41:43.619084 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:41:43.618342 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:41:39.459221 | INFO     | AssetNotifier        | Load assets: 301ms |
2024-07-08 10:41:39.459194 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 10:41:39.438980 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 10:41:39.438945 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 10:41:39.190168 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:41:39.189657 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:41:39.169372 | INFO     | BackupNotifier       | [_resumeBackup] Start back up |
2024-07-08 10:41:38.899257 | INFO     | ManualUploadNotifier | [_startUpload] Manual Upload Completed - success: 0, failed: 1 |
2024-07-08 10:29:20.530817 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 404, uri = http://10.1.4.210:2283/api/assets/48a39aeb-a685-4a8a-8d8a-0a793309164e/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription' |

2024-07-08 10:29:19.303727 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 404, uri = http://10.1.4.210:2283/api/assets/fe473a52-652c-4796-8183-654f97842b92/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription' |

2024-07-08 10:29:04.875111 | INFO     | AssetNotifier        | Load assets: 291ms |
2024-07-08 10:29:04.875090 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 10:29:04.860285 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 10:29:04.860240 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 10:29:04.748549 | INFO     | SyncService          | Upserted 1 assets into the DB |
2024-07-08 10:28:41.913934 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:28:41.910924 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:28:39.631726 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:28:39.631186 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:28:39.415100 | INFO     | AssetNotifier        | Load assets: 387ms |
2024-07-08 10:28:39.415077 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 10:28:39.400133 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 10:28:39.400109 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 10:28:39.285692 | INFO     | SyncService          | Upserted 10 assets into the DB |
2024-07-08 10:28:10.361616 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 404, uri = http://10.1.4.210:2283/api/assets/bb39c599-2244-4372-8220-614d21b0831c/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription' |

2024-07-08 10:28:02.902948 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: PlatformException(VideoError, Failed to load video: 无法打开, null, null)
Library: widgets library
Context: Instance of 'ErrorDescription' |
#1      AsyncError.value (package:riverpod/src/common.dart:494:0)
#2      VideoViewerPage.build (package:immich_mobile/pages/common/video_viewer.page.dart:36:0)
#3      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476:0)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5599:0)
#5      ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539:0)
#6      HookElement.build (package:flutter_hooks/src/framework.dart:438:0)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487:0)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:0)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:0)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136:0)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:0)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:0)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:0)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:0)
#16     _invoke (dart:ui/hooks.dart:312:0)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:0)
#18     _drawFrame (dart:ui/hooks.dart:283:0)

2024-07-08 10:27:54.091762 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 404, uri = http://10.1.4.210:2283/api/assets/d758ea91-e42c-46d4-9029-9e4e729fbd68/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription' |

2024-07-08 10:27:50.298177 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 404, uri = http://10.1.4.210:2283/api/assets/5def1ad5-d454-45ca-91ef-d9c833cd4d98/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription' |

2024-07-08 10:27:29.846219 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: PlatformException(VideoError, Failed to load video: 无法打开, null, null)
Library: widgets library
Context: Instance of 'ErrorDescription' |
#1      AsyncError.value (package:riverpod/src/common.dart:494:0)
#2      VideoViewerPage.build (package:immich_mobile/pages/common/video_viewer.page.dart:36:0)
#3      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476:0)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5599:0)
#5      ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539:0)
#6      HookElement.build (package:flutter_hooks/src/framework.dart:438:0)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487:0)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:0)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:0)
#11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136:0)
#12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:0)
#13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:0)
#14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:0)
#15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:0)
#16     _invoke (dart:ui/hooks.dart:312:0)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:0)
#18     _drawFrame (dart:ui/hooks.dart:283:0)

2024-07-08 10:27:26.696711 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 404, uri = http://10.1.4.210:2283/api/assets/5ba4e575-5d8e-4ac9-9ce0-782a9c95392c/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription' |

2024-07-08 10:27:22.313630 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:27:22.312847 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:26:34.931739 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 404, uri = http://10.1.4.210:2283/api/assets/29a0f1c1-38ea-4989-8e01-d9148e8fc55d/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription' |

2024-07-08 10:26:23.684883 | INFO     | AssetNotifier        | Load assets: 416ms |
2024-07-08 10:26:23.684857 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 10:26:23.669867 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 10:26:23.669835 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 10:26:23.467191 | INFO     | SyncService          | Upserted 1 assets into the DB |
2024-07-08 10:26:23.296104 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:26:23.295490 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:26:23.277302 | INFO     | BackupNotifier       | [_resumeBackup] Start back up |
2024-07-08 10:23:07.550382 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 404, uri = http://10.1.4.210:2283/api/assets/bb39c599-2244-4372-8220-614d21b0831c/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription' |

2024-07-08 10:23:00.241947 | INFO     | AssetNotifier        | Load assets: 462ms |
2024-07-08 10:23:00.241922 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 10:23:00.225754 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 10:23:00.225707 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 10:22:59.800346 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:22:59.799974 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:22:59.788367 | INFO     | BackupNotifier       | [_resumeBackup] Start back up |
2024-07-08 10:22:48.691571 | INFO     | AssetNotifier        | Load assets: 333ms |
2024-07-08 10:22:48.691549 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 10:22:48.676495 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 10:22:48.676448 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 10:22:48.563217 | INFO     | SyncService          | Upserted 6 assets into the DB |
2024-07-08 10:21:20.873612 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 404, uri = http://10.1.4.210:2283/api/assets/dd898019-150e-4885-bf00-304febd03919/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription' |

2024-07-08 10:21:10.069077 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:21:10.068376 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:21:07.918603 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:21:07.918019 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:21:04.983998 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:21:04.983295 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:21:02.761115 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:21:02.759868 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:20:58.629847 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:20:58.624855 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:20:55.263186 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:20:55.262417 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:20:52.138375 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:20:52.137649 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:20:52.062659 | INFO     | ManualUploadNotifier | [_startUpload] Manual Upload Completed - success: 0, failed: 1 |
2024-07-08 10:20:22.920874 | INFO     | AssetNotifier        | Load assets: 357ms |
2024-07-08 10:20:22.920846 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 10:20:22.905759 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 10:20:22.905718 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 10:20:22.796367 | INFO     | SyncService          | Upserted 4 assets into the DB |
2024-07-08 10:19:41.820551 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:19:41.819762 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:19:32.471668 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:19:32.468335 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:19:29.662595 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:19:29.661667 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:19:14.607977 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 404, uri = http://10.1.4.210:2283/api/assets/5ba4e575-5d8e-4ac9-9ce0-782a9c95392c/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription' |

2024-07-08 10:19:10.918919 | INFO     | AssetNotifier        | Load assets: 595ms |
2024-07-08 10:19:10.918886 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 10:19:10.902731 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 10:19:10.902706 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 10:19:10.806220 | INFO     | SyncService          | Upserted 1 assets into the DB |
2024-07-08 10:19:10.340831 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:19:10.340277 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:19:10.325427 | INFO     | BackupNotifier       | [_resumeBackup] Start back up |
2024-07-08 10:13:06.921671 | INFO     | AssetNotifier        | Load assets: 396ms |
2024-07-08 10:13:06.921638 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 10:13:06.894426 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 10:13:06.894395 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 10:13:06.810279 | INFO     | AlbumService         | refreshDeviceAlbums is already in progress |
2024-07-08 10:13:06.809930 | INFO     | SyncService          | Upserted 1 assets into the DB |
2024-07-08 10:13:06.596625 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 10:13:06.596299 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 10:13:06.497920 | INFO     | BackupNotifier       | [_resumeBackup] Start back up |
2024-07-08 10:13:06.411233 | INFO     | ApiService           | Pinging server with response code 200 |
2024-07-08 00:34:49.627356 | INFO     | AssetNotifier        | Load assets: 353ms |
2024-07-08 00:34:49.627249 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 00:34:49.601258 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 00:34:49.601192 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 00:34:49.485633 | INFO     | SyncService          | Upserted 1 assets into the DB |
2024-07-08 00:34:49.307899 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 00:34:49.307278 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-08 00:34:49.287379 | INFO     | BackupNotifier       | [_resumeBackup] Start back up |
2024-07-08 00:02:11.560950 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-07-08 00:02:11.547244 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-08 00:02:11.547215 | INFO     | AlbumService         | Found 18 device albums |
2024-07-08 00:02:10.254181 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-08 00:02:10.253871 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-07 23:59:45.589424 | INFO     | AssetNotifier        | Load assets: 540ms |
2024-07-07 23:59:45.589410 | INFO     | AlbumService         | Syncing completed. Changes: true |
2024-07-07 23:59:45.589388 | INFO     | SyncService          | Synced changes of local album 人像 to DB |
2024-07-07 23:59:45.506270 | INFO     | SyncService          | Synced changes of local album RAW to DB |
2024-07-07 23:59:45.467864 | INFO     | SyncService          | Synced changes of local album 实况照片 to DB |
2024-07-07 23:59:45.408037 | INFO     | SyncService          | Synced changes of local album 全景照片 to DB |
2024-07-07 23:59:45.376824 | INFO     | AlbumService         | refreshDeviceAlbums is already in progress |
2024-07-07 23:59:45.376118 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-07 23:59:45.376084 | INFO     | AlbumService         | Found 18 device albums |
2024-07-07 23:59:45.113862 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-07 23:59:45.100528 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-07 23:59:45.024900 | INFO     | BackupNotifier       | [_resumeBackup] Start back up |
2024-07-07 23:59:44.954769 | INFO     | ApiService           | Pinging server with response code 200 |
2024-07-07 23:51:58.746995 | INFO     | AlbumService         | Syncing completed. Changes: true |
2024-07-07 23:51:58.746986 | INFO     | SyncService          | Added a new local album to DB: 人像 |
2024-07-07 23:51:58.746095 | INFO     | SyncService          | Upserted 287 assets into the DB |
2024-07-07 23:51:58.742102 | INFO     | SyncService          | 0 assets already existed in DB, to upsert 287 |
2024-07-07 23:51:58.607122 | INFO     | SyncService          | Syncing a new local album to DB: 人像 |
2024-07-07 23:51:58.607115 | INFO     | SyncService          | Added a new local album to DB: RAW |
2024-07-07 23:51:58.606625 | INFO     | SyncService          | Upserted 1 assets into the DB |
2024-07-07 23:51:58.606126 | INFO     | SyncService          | 0 assets already existed in DB, to upsert 1 |
2024-07-07 23:51:58.423152 | INFO     | SyncService          | Syncing a new local album to DB: RAW |
2024-07-07 23:51:58.423125 | INFO     | SyncService          | Added a new local album to DB: 实况照片 |
2024-07-07 23:51:58.421422 | INFO     | SyncService          | Upserted 416 assets into the DB |
2024-07-07 23:51:58.414149 | INFO     | SyncService          | 0 assets already existed in DB, to upsert 416 |
2024-07-07 23:51:54.341894 | INFO     | SyncService          | Syncing a new local album to DB: 实况照片 |
2024-07-07 23:51:54.341885 | INFO     | SyncService          | Added a new local album to DB: 全景照片 |
2024-07-07 23:51:54.341409 | INFO     | SyncService          | Upserted 1 assets into the DB |
2024-07-07 23:51:54.341025 | INFO     | SyncService          | 0 assets already existed in DB, to upsert 1 |
2024-07-07 23:51:54.272299 | INFO     | SyncService          | Syncing a new local album to DB: 全景照片 |
2024-07-07 23:51:54.272114 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |
2024-07-07 23:51:54.272060 | INFO     | AlbumService         | Found 18 device albums |
2024-07-07 23:51:19.820210 | INFO     | BackupNotifier       | No assets are selected for back up |
2024-07-07 23:51:19.749086 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-07 23:51:19.748893 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-07 23:51:18.495731 | INFO     | BackupNotifier       | No assets are selected for back up |
2024-07-07 23:51:18.417888 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 26 available albums |
2024-07-07 23:51:18.417645 | INFO     | BackupNotifier       | Found 26 local albums |
2024-07-07 23:50:26.537837 | INFO     | AssetNotifier        | Load assets: 5457ms |
2024-07-07 23:50:26.535759 | INFO     | SyncService          | Upserted 26409 assets into the DB |
2024-07-07 23:50:20.776151 | INFO     | AssetNotifier        | Load assets: 84975ms |
2024-07-07 23:50:20.773875 | SEVERE   | AssetService         | Error while getting remote assets | ApiException 400: HTTP connection failed: POST /sync/full-sync (Inner exception: Bad file descriptor)

#0      IOClient.send (package:http/src/io_client.dart:96)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      ApiClient.invokeAPI (package:openapi/api_client.dart:96)
<asynchronous suspension>
#3      SyncApi.getFullSyncForUser (package:openapi/api/sync_api.dart:99)
<asynchronous suspension>
#4      AssetService._getRemoteAssets (package:immich_mobile/services/asset.service.dart:115)
<asynchronous suspension>
#5      SyncService._syncRemoteAssetsForUser (package:immich_mobile/services/sync.service.dart:241)
<asynchronous suspension>
#6      SyncService._syncRemoteAssetsFull (package:immich_mobile/services/sync.service.dart:231)
<asynchronous suspension>
#7      SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/services/sync.service.dart:56)
<asynchronous suspension>
#8      AsyncMutex.run.<anonymous closure> (package:immich_mobile/utils/async_mutex.dart:15)
<asynchronous suspension>
 |
#0      ApiClient.invokeAPI (package:openapi/api_client.dart:125)
<asynchronous suspension>
#1      SyncApi.getFullSyncForUser (package:openapi/api/sync_api.dart:99)
<asynchronous suspension>
#2      AssetService._getRemoteAssets (package:immich_mobile/services/asset.service.dart:115)
<asynchronous suspension>
#3      SyncService._syncRemoteAssetsForUser (package:immich_mobile/services/sync.service.dart:241)
<asynchronous suspension>
#4      SyncService._syncRemoteAssetsFull (package:immich_mobile/services/sync.service.dart:231)
<asynchronous suspension>
#5      SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/services/sync.service.dart:56)
<asynchronous suspension>
#6      AsyncMutex.run.<anonymous closure> (package:immich_mobile/utils/async_mutex.dart:15)
<asynchronous suspension>

2024-07-07 23:48:55.372820 | INFO     | ApiService           | Pinging server with response code 200 |
2024-07-07 23:48:45.094015 | INFO     | ApiService           | Pinging server with response code 200 |
```

**Comment by alextran1502** [comment]
Hmm, can you try logout and log back in?

**Comment by lbp0** [comment]
> Hmm, can you try logout and log back in?

It doesn't work😭😭😭

**Comment by HippoBloke** [comment]
I saw this behaviour when using the CLI, if uploaded through the web or app it doesn't seem to happen.

**Comment by alextran1502** [comment]
@lbp0 Did you update those from the CLI? I assume those LivePhotos were edited at one point that was why they lost the information to link the two together

**Comment by lbp0** [comment]
> @lbp0 Did you update those from the CLI? I assume those LivePhotos were edited at one point that was why they lost the information to link the two together

I updated immich from CLI using docker compose, but I uploaded photos from the phone app. I think they are original LivePhotos formate when I uploaded

**Comment by lbp0** [comment]
Well, I installed immich on my windows PC and everything work good. I will try reinstalling immich on my server. Maybe I got some files damaged when I pulled the docker images or something?

**Comment by lbp0** [comment]
OK guys, I updated to the latest docker compose file and .env file. Now server works fine. Thank you guys!
