### ISSUE TITLE
Error while transcoding videos

### ISSUE THREAD

**Issue by krypton9208** [immich-app/immich#11133]
### The bug

`2024-07-16T05:45:45.045017807Z [Nest] 7  - 07/16/2024, 7:45:45 AM   ERROR [Microservices:MediaRepository] ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
2024-07-16T05:45:45.045064422Z   built with gcc 12 (Debian 12.2.0-14)
2024-07-16T05:45:45.045074043Z   configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
2024-07-16T05:45:45.045106292Z   libavutil      58.  2.100 / 58.  2.100
2024-07-16T05:45:45.045115183Z   libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
2024-07-16T05:45:45.045130063Z   libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
2024-07-16T05:45:45.045153383Z   libswresample   4. 10.100 /  4. 10.100
2024-07-16T05:45:45.045160943Z   libpostproc    57.  1.100 / 57.  1.100
2024-07-16T05:45:45.045169059Z [h264 @ 0x305e21e0580] Reinit context to 1088x1920, pix_fmt: yuv420p
2024-07-16T05:45:45.045177175Z Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/upload/51977439-e226-4222-8e09-b30a4908c647/c6/0a/c60a83ed-b2a3-4891-8a92-8b713fdf6f7d.mp4':
2024-07-16T05:45:45.045184833Z   Metadata:
2024-07-16T05:45:45.045192756Z     major_brand     : mp42
2024-07-16T05:45:45.045200566Z     minor_version   : 0
2024-07-16T05:45:45.045207956Z     compatible_brands: isommp42
2024-07-16T05:45:45.045216011Z     creation_time   : 1970-01-01T00:00:00.000000Z
2024-07-16T05:45:45.045223517Z   Duration: 00:00:04.37, start: 0.000000, bitrate: 3637 kb/s
2024-07-16T05:45:45.045231544Z   Stream #0:0[0x1](und): Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(tv, bt709, progressive, left), 1080x1920 (1088x1920) [SAR 1:1 DAR 9:16], 3556 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
2024-07-16T05:45:45.045239004Z     Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
2024-07-16T05:45:45.045253800Z       handler_name    : ISO Media file produced by Google Inc.
2024-07-16T05:45:45.045261305Z       vendor_id       : [0][0][0][0]
2024-07-16T05:45:45.045269057Z   Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
2024-07-16T05:45:45.045276522Z     Metadata:
2024-07-16T05:45:45.045284193Z       creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : ISO Media file produced by Google Inc.
2024-07-16T05:45:45.045299476Z       vendor_id       : [0][0][0][0]
2024-07-16T05:45:45.045306835Z Stream mapping:
2024-07-16T05:45:45.045314595Z   Stream #0:0 -> #0:0 (h264 (native) -> webp (libwebp_anim))
2024-07-16T05:45:45.045322043Z Press [q] to stop, [?] for help
2024-07-16T05:45:45.045329603Z [h264 @ 0x305e21e1580] Reinit context to 1088x1920, pix_fmt: yuv420p
2024-07-16T05:45:45.045337126Z EOF in input file 0
Terminating demuxer thread 0
[Parsed_thumbnail_1 @ 0x305e2162f40] batch size: 12 frames
2024-07-16T05:45:45.045359249Z [Parsed_scale_5 @ 0x305e2121080] w:250 h:-2 flags:'lanczos+accurate_rnd+full_chroma_int' interl:0
2024-07-16T05:45:45.045366834Z [graph 0 input from stream 0:0 @ 0x305e2120d80] w:1080 h:1920 pixfmt:yuv420p tb:1/15360 fr:30/1 sar:1/1
2024-07-16T05:45:45.045381629Z [Parsed_fps_0 @ 0x305e2162e80] fps=12/1
2024-07-16T05:45:45.045390336Z [Parsed_scale_5 @ 0x305e2121080] w:1080 h:1920 fmt:yuv420p sar:1/1 -> w:250 h:444 fmt:yuv420p sar:999/1000 flags:0x00042200
2024-07-16T05:45:45.045397969Z [Parsed_fps_0 @ 0x305e2162e80] Set first pts to 49
Output #0, webp, to 'upload/thumbs/51977439-e226-4222-8e09-b30a4908c647/e4/e2/e4e23291-88fe-49a7-944a-6229ebe48b39-thumbnail.webp':
2024-07-16T05:45:45.045413100Z   Metadata:
2024-07-16T05:45:45.045420637Z     major_brand     : mp42
2024-07-16T05:45:45.045428147Z     minor_version   : 0
2024-07-16T05:45:45.045435688Z     compatible_brands: isommp42
2024-07-16T05:45:45.045443245Z     encoder         : Lavf60.3.100
2024-07-16T05:45:45.045450938Z   Stream #0:0(und): Video: webp, 1 reference frame, yuv420p, 250x444 (0x0) [SAR 999:1000 DAR 9:16], q=2-31, 200 kb/s, 12 fps, 1k tbn (default)
2024-07-16T05:45:45.045458548Z     Metadata:
2024-07-16T05:45:45.045466170Z       creation_time   : 1970-01-01T00:00:00.000000Z
2024-07-16T05:45:45.045473880Z       handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
2024-07-16T05:45:45.045489036Z       encoder         : Lavc60.3.100 libwebp_anim
2024-07-16T05:45:45.045496629Z frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
2024-07-16T05:45:45.045504244Z No more output streams to write to, finishing.
2024-07-16T05:45:45.045511986Z [libwebp encoder @ 0x305e2180680] WebPAnimEncoderAssemble() failed with error: 1
[vost#0:0/libwebp_anim @ 0x305e2154080] Error submitting video frame to the encoder
[Parsed_fps_0 @ 0x305e2162e80] 2 frames in, 0 frames out; 2 frames dropped, 0 frames duplicated.
2024-07-16T05:45:45.045565335Z [out#0/webp @ 0x305e2160840] All streams finished
2024-07-16T05:45:45.045573005Z [out#0/webp @ 0x305e2160840] Terminating muxer thread
2024-07-16T05:45:45.045580589Z [AVIOContext @ 0x305e2180900] Statistics: 0 bytes written, 0 seeks, 0 writeouts
2024-07-16T05:45:45.045588232Z [AVIOContext @ 0x305e21802c0] Statistics: 1985124 bytes read, 0 seeks
2024-07-16T05:45:45.045595737Z Conversion failed!
2024-07-16T05:45:45.045603198Z 
2024-07-16T05:45:45.046178141Z [Nest] 7  - 07/16/2024, 7:45:45 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnail): Error: ffmpeg exited with code 1: Conversion failed!

[Nest] 7  - 07/16/2024, 7:45:45 AM   ERROR [Microservices:JobService] Error: ffmpeg exited with code 1: Conversion failed!

    at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
2024-07-16T05:45:45.046291550Z     at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)`

### The OS that Immich Server is running on

helm

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

v1.108.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
normal
```

### Your .env content

```Shell
normal
```

### Reproduction steps

```bash
1. Start video trancoding job
2. Show logs from pod.
```

**Comment by bo0tzz** [comment]
Please post more detail including your helm values, whether you're using hardware acceleration, and if this happens for all files or just one/a few.

**Comment by krypton9208** [comment]
i thinks this is maybe not for all videos, but every time a click "transcoding missing videos" , immich find almost 3500  (where i have 4500 total videos on server) movies that not transcoded... How can i list videos that not transcoded yet?

`## This chart relies on the common library chart from bjw-s
## You can find it at https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
## Refer there for more detail about the supported values

# These entries are shared between all the Immich components

env:
  REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
  DB_HOSTNAME: "{{ .Release.Name }}-postgresql"
  DB_USERNAME: "{{ .Values.postgresql.global.postgresql.auth.username }}"
  DB_DATABASE_NAME: "{{ .Values.postgresql.global.postgresql.auth.database }}"
  # -- You should provide your own secret outside of this helm-chart and use `postgresql.global.postgresql.auth.existingSecret` to provide credentials to the postgresql instance
  DB_PASSWORD: "{{ .Values.postgresql.global.postgresql.auth.password }}"
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
  TZ: "Poland"

image:
  tag: v1.109.2

immich:
  metrics:
    # Enabling this will create the service monitors needed to monitor immich with the prometheus operator
    enabled: false
  persistence:
    # Main data store for all photos shared between different components.
    library:
      # Automatically creating the library volume is not supported by this chart
      # You have to specify an existing PVC to use
      existingClaim: immich-storage
  # configuration is immich-config.json converted to yaml
  # ref: https://immich.app/docs/install/config-file/
  #
  configuration:
    ffmpeg:
      crf: 23
      threads: 0
      preset: ultrafast
      targetVideoCodec: h264
      acceptedVideoCodecs:
        - h264
      targetAudioCodec: aac
      acceptedAudioCodecs:
        - aac
        - mp3
        - libopus
      targetResolution: '720'
      maxBitrate: '0'
      bframes: -1
      refs: 0
      gopSize: 0
      npl: 0
      temporalAQ: false
      cqMode: auto
      twoPass: false
      preferredHwDevice: auto
      transcode: required
      tonemap: hable
      accel: disabled
    job:
      backgroundTask:
        concurrency: 5
      smartSearch:
        concurrency: 2
      metadataExtraction:
        concurrency: 5
      faceDetection:
        concurrency: 2
      search:
        concurrency: 5
      sidecar:
        concurrency: 5
      library:
        concurrency: 5
      migration:
        concurrency: 5
      thumbnailGeneration:
        concurrency: 10
      videoConversion:
        concurrency: 3
    logging:
      enabled: true
      level: log
    machineLearning:
      enabled: true
      url: http://immich-machine-learning:3003
      clip:
        enabled: true
        modelName: ViT-B-32__openai
      facialRecognition:
        enabled: true
        modelName: buffalo_l
        minScore: 0.7
        maxDistance: 0.6
        minFaces: 3
    map:
      enabled: true
      lightStyle: ''
      darkStyle: ''
    reverseGeocoding:
      enabled: true
    oauth:
      enabled: false
      issuerUrl: ''
      clientId: ''
      clientSecret: ''
      scope: openid email profile
      signingAlgorithm: RS256
      storageLabelClaim: preferred_username
      storageQuotaClaim: immich_quota
      defaultStorageQuota: 0
      buttonText: Login with OAuth
      autoRegister: true
      autoLaunch: false
      mobileOverrideEnabled: false
      mobileRedirectUri: ''
    passwordLogin:
      enabled: true
    storageTemplate:
      enabled: false
      hashVerificationEnabled: true
      template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
    image:
      thumbnailFormat: webp
      thumbnailSize: 250
      previewFormat: jpeg
      previewSize: 1440
      quality: 80
      colorspace: p3
      extractEmbedded: false
    newVersionCheck:
      enabled: true
    notifications:
      smtp:
        enabled: true
        from: 'Immich Photo Server <SECRET>'
        replyTo: 'SECRET'
        transport:
          ignoreCert: false
          host: 'smtp.sendgrid.net'
          port: 465
          username: 'apikey'
          password: SECRET
    trash:
      enabled: true
      days: 30
    theme:
      customCss: ''
    user:
      deleteDelay: 7
    library:
      scan:
        enabled: true
        cronExpression: 0 0 * * *
      watch:
        enabled: true
    server:
      externalDomain: 'https://SECRECT'
    # trash:
    #   enabled: false
    #   days: 30
    # storageTemplate:
    #   enabled: true
  #   template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"

# Dependencies

postgresql:
  enabled: true
  image:
    repository: tensorchord/pgvecto-rs
    tag: pg14-v0.2.0
  global:
    postgresql:
      auth:
        username: immich
        database: immich
        password: SECRET
  primary:
    initdb:
      scripts:
        create-extensions.sql: |
          CREATE EXTENSION cube;
          CREATE EXTENSION earthdistance;
          CREATE EXTENSION vectors;

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

# Immich components

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  probes:
    liveness:
      spec:
        initialDelaySeconds: 120
    readiness:
      spec:
        initialDelaySeconds: 120

machine-learning:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    pullPolicy: IfNotPresent
  env:
    TRANSFORMERS_CACHE: /cache
  persistence:
    cache:
      enabled: true
      size: 10Gi
      # Optional: Set this to pvc to avoid downloading the ML models every start.
      type: pvc
      accessMode: ReadWriteMany
      storageClass: longhorn
`

I don't have any GPU, i just create k8s cluster, with longhorn storage, so immich use cpu (Intel(R) Xeon(R) CPU E5-2470 v2 @ 2.40GHz ), i have 3 worker nodes (each node is virtual machine on proxmox with 16GB ram, and 4 CPU and)

**Comment by bo0tzz** [comment]
@mertalev any ideas?

**Comment by mertalev** [comment]
The error in the OP is for video thumbnail generation, meaning it apparently couldn't find a frame. This issue was ironed out after a few changes, but it seems there's an edge case here.

It's normal for queueing *Missing* for Transcode Videos to queue a bunch of assets each time since videos can get skipped based on the transcode policy. Any video asset that's never been transcoded will get queued. I don't think this is related to the issue in the OP.

A sample video that causes this error would be very helpful so I can reproduce it.

**Comment by diogotcorreia** [comment]
@mertalev I happen to have a video with the same error (.MOV, ~6 seconds long). I can send you the video by email if you wish, just tell me where to send it to (you can reach me privately if you want, contact info on my profile).

This log happens after clicking the "regenerate thumbnail" button of the asset in question (thumbnail is known to be broken since it's showing up under "offline files" in the repair page):

<details>
<summary>immich + ffmpeg log</summary>

```
[Nest] 7  - 08/10/2024, 12:28:20 PM     LOG [Microservices:MediaService] Successfully generated JPEG video preview for asset e993754e-8f26-454b-b9be-8f95b01ee3d3
[Nest] 7  - 08/10/2024, 12:28:20 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbhash): Error: Input file is missing: upload/thumbs/abe58e18-04a4-4051-a1c9-b7e3ef461b77/e9/93/e993754e-8f26-454b-b9be-8f95b01ee3d3-preview.jpeg
[Nest] 7  - 08/10/2024, 12:28:20 PM   ERROR [Microservices:JobService] Error: Input file is missing: upload/thumbs/abe58e18-04a4-4051-a1c9-b7e3ef461b77/e9/93/e993754e-8f26-454b-b9be-8f95b01ee3d3-preview.jpeg
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:161:17)
    at MediaRepository.generateThumbhash (/usr/src/app/dist/repositories/media.repository.js:137:14)
    at MediaService.handleGenerateThumbhash (/usr/src/app/dist/services/media.service.js:223:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 08/10/2024, 12:28:20 PM   ERROR [Microservices:JobService] Object:
{
  "id": "e993754e-8f26-454b-b9be-8f95b01ee3d3"
}
[Nest] 7  - 08/10/2024, 12:28:20 PM   ERROR [Microservices:MediaRepository] ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[h264 @ 0x3edfe100580] Reinit context to 1088x1920, pix_fmt: yuv420p
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/library/admin/2019/2019-01-19/IMG_0117.MOV':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-01-19T16:43:27.000000Z
  Duration: 00:00:06.08, start: 0.000000, bitrate: 4371 kb/s
  Stream #0:0[0x1](und): Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(tv, bt709, progressive, left), 1080x1920 (1088x1920) [SAR 1:1 DAR 9:16], 4329 kb/s, 29.97 fps, 29.97 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2019-01-19T23:29:38.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 01/19/2019.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 93 kb/s (default)
    Metadata:
      creation_time   : 2019-01-19T23:29:38.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 01/19/2019.
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> webp (libwebp_anim))
Press [q] to stop, [?] for help
[h264 @ 0x3edfe101580] Reinit context to 1088x1920, pix_fmt: yuv420p
[Parsed_thumbnail_1 @ 0x3edfe1a2dc0] batch size: 12 frames
[Parsed_scale_5 @ 0x3edfe110a80] w:250 h:-2 flags:'lanczos+accurate_rnd+full_chroma_int' interl:0
[graph 0 input from stream 0:0 @ 0x3edfe110c80] w:1080 h:1920 pixfmt:yuv420p tb:1/90000 fr:30000/1001 sar:1/1
[Parsed_fps_0 @ 0x3edfe1a2d00] fps=12/1
[Parsed_scale_5 @ 0x3edfe110a80] w:1080 h:1920 fmt:yuv420p sar:1/1 -> w:250 h:444 fmt:yuv420p sar:999/1000 flags:0x00042200
EOF in input file 0
Terminating demuxer thread 0
[Parsed_fps_0 @ 0x3edfe1a2d00] Set first pts to 10
Output #0, webp, to 'upload/thumbs/abe58e18-04a4-4051-a1c9-b7e3ef461b77/e9/93/e993754e-8f26-454b-b9be-8f95b01ee3d3-thumbnail.webp':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf60.3.100
  Stream #0:0(und): Video: webp, 1 reference frame, yuv420p, 250x444 (0x0) [SAR 999:1000 DAR 9:16], q=2-31, 200 kb/s, 12 fps, 1k tbn (default)
    Metadata:
      creation_time   : 2019-01-19T23:29:38.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 01/19/2019.
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.3.100 libwebp_anim
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A
No more output streams to write to, finishing.
[libwebp encoder @ 0x3edfe7b0180] WebPAnimEncoderAssemble() failed with error: 1
[vost#0:0/libwebp_anim @ 0x3edfe0b2b80] Error submitting video frame to the encoder
[Parsed_fps_0 @ 0x3edfe1a2d00] 2 frames in, 0 frames out; 2 frames dropped, 0 frames duplicated.
[out#0/webp @ 0x3edfe1a0900] All streams finished
[out#0/webp @ 0x3edfe1a0900] Terminating muxer thread
[AVIOContext @ 0x3edfe7b0400] Statistics: 0 bytes written, 0 seeks, 0 writeouts
[AVIOContext @ 0x3edfe0d0180] Statistics: 3324675 bytes read, 0 seeks
Conversion failed!

[Nest] 7  - 08/10/2024, 12:28:20 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnail): Error: ffmpeg exited with code 1: Conversion failed!

[Nest] 7  - 08/10/2024, 12:28:20 PM   ERROR [Microservices:JobService] Error: ffmpeg exited with code 1: Conversion failed!
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
[Nest] 7  - 08/10/2024, 12:28:20 PM   ERROR [Microservices:JobService] Object:
{
  "id": "e993754e-8f26-454b-b9be-8f95b01ee3d3"
}
```

</details>

Using Immich v1.111.0 on Docker.

**Comment by C-Otto** [comment]
Regarding the repair page issue: see #12053

**Comment by C-Otto** [comment]
@mertalev here are my two videos (the only two!) that cause the "Conversion failed!" error when generating the preview.

- https://c-otto.de/20180913_181550.mp4
- https://c-otto.de/neuseeland-00014.mts

**Comment by yuhuan417** [comment]
I have a similar problem with a video. The video is very short, only 2 seconds, 524K bytes, and I can't generate a preview image.
The ffmpeg command line includes "-skip_frame nointra", but interestingly, this video does not have any key frame.

# ffprobe -show_frames -select_streams v:0 IMG_20180816_221353.MOV|grep key_frame|sort|uniq -c
88 key_frame=0

I'm not sure how to fix this, retry without "-skip_frame nointra"?

**Comment by alextran1502** [comment]
This is no longer relevant with the new implementation, please open a new issue if it is still persisted
