### ISSUE TITLE
Immich only starts up after 10 minutes

### ISSUE THREAD

**Issue by canedje** [immich-app/immich#11197]
### The bug

It take a long time before Immich starts (appr. 10 minutes)
The log is starting with a "geodata_places error"
[Nest] 228  - 07/18/2024, 8:56:37 PM   ERROR [Microservices:MetadataService] Unable to initialize reverse geocoding: QueryFailedError: relation "geodata_places" does not exist

```
QueryFailedError: relation "geodata_places" does not exist
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryRunner.clearTable (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:1584:9)
  Baseimage from linuxserver.io    at async EntityManager.clear (/app/immich/server/node_modules/typeorm/entity-manager/EntityManager.js:679:20)

    at async MapRepository.importGeodata (/app/immich/server/dist/repositories/map.repository.js:205:13)
    at async MapRepository.init (/app/immich/server/dist/repositories/map.repository.js:59:9)
    at async /app/immich/server/dist/repositories/database.repository.js:177:23
```

### The OS that Immich Server is running on

As a docker under Unraid

### Version of Immich Server

v1.109.1

### Version of Immich Mobile App

not used

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
docker run
  -d
  --name='immich'
  --net='ewhnet'
  --cpuset-cpus='2,4,6,8,10,3,5,7,9'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower2"
  -e HOST_CONTAINERNAME="immich"
  -e 'DB_HOSTNAME'='192.168.2.240'
  -e 'DB_USERNAME'='name'
  -e 'DB_PASSWORD'='passwd'
  -e 'DB_DATABASE_NAME'='immich'
  -e 'REDIS_HOSTNAME'='192.168.2.240'
  -e 'DB_PORT'='5432'
  -e 'REDIS_PORT'='6379'
  -e 'REDIS_PASSWORD'='passwd'
  -e 'MACHINE_LEARNING_WORKERS'='1'
  -e 'MACHINE_LEARNING_WORKER_TIMEOUT'='120'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png'
  -p '8089:8080/tcp'
  -v '/mnt/remotes/NAS_NetwerkSchijf/Media/immich/photos/':'/photos':'rw,slave'
  -v '/mnt/remotes/NAS_NetwerkSchijf/Media/immich/import/':'/import':'ro,slave'
  -v '/mnt/user/appdata/immich':'/config':'rw' 'ghcr.io/imagegenius/immich:latest'
1eec4a8a4a3d2bdebd7a1f7512576d5f09df3e03fbf137ca6eda1605dbd2a51b

The command finished successfully!
```

### Your .env content

```Shell
I do not know where to find
```

### Reproduction steps

```bash
1.do a update or stop the docker
2. then its happening
3.
...
```

### Relevant log output

```shell
QueryFailedError: relation "geodata_places" does not exist
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryRunner.clearTable (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:1584:9)
  Baseimage from linuxserver.io    at async EntityManager.clear (/app/immich/server/node_modules/typeorm/entity-manager/EntityManager.js:679:20)

    at async MapRepository.importGeodata (/app/immich/server/dist/repositories/map.repository.js:205:13)
    at async MapRepository.init (/app/immich/server/dist/repositories/map.repository.js:59:9)
    at async /app/immich/server/dist/repositories/database.repository.js:177:23

[Nest] 235  - 07/18/2024, 9:15:23 PM     LOG [Microservices:MapRepository] Initializing metadata repository
[Nest] 235  - 07/18/2024, 9:15:23 PM   FATAL [Microservices:MapRepository] Error importing geodata
[Nest] 235  - 07/18/2024, 9:15:23 PM   FATAL [Microservices:MapRepository] QueryFailedError: relation "geodata_places" does not exist
[Nest] 235  - 07/18/2024, 9:15:23 PM    WARN [Microservices:DuplicateService] Unknown keys found: {
  "job": {
    "objectTagging": {
      "concurrency": 3
    },
    "recognizeFaces": {
      "concurrency": 3
    },
    "storageTemplateMigration": {
      "concurrency": 8
    }
  }
}

```

**Comment by alextran1502** [comment]
Does it always happen like that or just a one time thing?

**Comment by zaggash** [comment]
Even tho it might be protected and through VPN, I would not share my password on GitHub @canedje 
Careful ♥️

**Comment by canedje** [comment]
> Does it always happen like that or just a one time thing?

All the time after starting the container again

**Comment by canedje** [comment]
> Even tho it might be protected and through VPN, I would not share my password on GitHub @canedje Careful ♥️

Thanks for the warning, I didn't think about that. Changed it

**Comment by zaggash** [comment]
> > Even tho it might be protected and through VPN, I would not share my password on GitHub @canedje Careful ♥️
> 
> Thanks for the warning, I didn't think about that. Changed it

Just a last warning to say that github keeps an history of issues and modifications.
I'm done with off topic.

**Comment by canedje** [comment]
After latest update, the container is starting up immediatly again.
Thanks
