### ISSUE TITLE
Cache Directory Does Not Exist, CLIP model - Unraid 

### ISSUE THREAD

**Issue by OfficiallyCrazy** [immich-app/immich#11318]
### The bug

I tried to install the some of the CLIP models but I get this error. 
I have read other issues both opened and closed but the issues I fond was over 1 year ago. I assume that it has something to do with cache permission. But i don't know where this folder is meant to exist. 

I am able to restore the setting to the default and it works. But it doesn't when I try any other CLIP models. 

### The OS that Immich Server is running on

UNRAID

### Version of Immich Server

v1.109.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Installation direct from Unraid
```

### Your .env content

```Shell
Not sure what that is.
```

### Reproduction steps

```bash
1. Try to install a CLIP model provided from IMMICH website
2. Run Smart Search
3. Open Logs
...
```

### Relevant log output

```shell
[07/23/24 11:45:11] INFO     Downloading visual model 'RN50__openai'. This may  
                             take a while.                                      
[07/23/24 11:45:39] WARNING  Failed to load visual model 'RN50__openai'.        
                             Clearing cache.                                    
[07/23/24 11:45:39] INFO     Downloading visual model 'RN50__openai'. This may  
                             take a while.                                      
[07/23/24 11:45:39] WARNING  Attempted to clear cache for model 'RN50__openai', 
                             but cache directory does not exist                 
[Nest] 233  - 07/23/2024, 11:45:39 AM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request '{"clip":{"visual":{"modelName":"immich-app/RN50__openai"}}}' failed with status 500: Internal Server Error
[Nest] 233  - 07/23/2024, 11:45:39 AM   ERROR [Microservices:JobService] Error: Machine learning request '{"clip":{"visual":{"modelName":"immich-app/RN50__openai"}}}' failed with status 500: Internal Server Error
    at MachineLearningRepository.predict (/app/immich/server/dist/repositories/machine-learning.repository.js:22:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MachineLearningRepository.encodeImage (/app/immich/server/dist/repositories/machine-learning.repository.js:42:26)
    at async SmartInfoService.handleEncodeClip (/app/immich/server/dist/services/smart-info.service.js:91:27)
    at async /app/immich/server/dist/services/job.service.js:148:36
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 233  - 07/23/2024, 11:45:39 AM   ERROR [Microservices:JobService] Object:
{
  "id": "4c2fdcd0-517a-454a-8179-0472eaf382ec"
}

[07/23/24 11:46:07] WARNING  Failed to load visual model 'RN50__openai'.        
                             Clearing cache.                                    
[07/23/24 11:46:07] WARNING  Attempted to clear cache for model 'RN50__openai', 
                             but cache directory does not exist                 
[Nest] 233  - 07/23/2024, 11:46:07 AM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request '{"clip":{"visual":{"modelName":"immich-app/RN50__openai"}}}' failed with status 500: Internal Server Error
[Nest] 233  - 07/23/2024, 11:46:07 AM   ERROR [Microservices:JobService] Error: Machine learning request '{"clip":{"visual":{"modelName":"immich-app/RN50__openai"}}}' failed with status 500: Internal Server Error
    at MachineLearningRepository.predict (/app/immich/server/dist/repositories/machine-learning.repository.js:22:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MachineLearningRepository.encodeImage (/app/immich/server/dist/repositories/machine-learning.repository.js:42:26)
    at async SmartInfoService.handleEncodeClip (/app/immich/server/dist/services/smart-info.service.js:91:27)
    at async /app/immich/server/dist/services/job.service.js:148:36
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 233  - 07/23/2024, 11:46:07 AM   ERROR [Microservices:JobService] Object:
{
  "id": "3e1a17c4-6119-4c83-b27c-97553d92a734"
}

[Nest] 210  - 07/23/2024, 11:46:57 AM     LOG [Api:SystemConfigService~lhrbcksl] LogLevel=log (set via system config)
[Nest] 210  - 07/23/2024, 11:46:57 AM     LOG [Api:SystemConfigService~lhrbcksl] LogLevel=log (set via system config)
[Nest] 210  - 07/23/2024, 11:46:57 AM     LOG [Api:MapRepository~lhrbcksl] Initializing metadata repository
[Nest] 210  - 07/23/2024, 11:46:57 AM     LOG [Api:MetadataService~lhrbcksl] Initialized local reverse geocoder
[Nest] 233  - 07/23/2024, 11:46:57 AM     LOG [Microservices:SystemConfigService] LogLevel=log (set via system config)
[Nest] 210  - 07/23/2024, 11:46:57 AM     LOG [Api:SearchRepository~lhrbcksl] Dimension size of model ViT-B-32__openai is 512, but database expects 1024.
[Nest] 210  - 07/23/2024, 11:46:57 AM     LOG [Api:SearchRepository~lhrbcksl] Updating database CLIP dimension size to 512.
[Nest] 210  - 07/23/2024, 11:46:57 AM     LOG [Api:SearchRepository~lhrbcksl] Successfully updated database CLIP dimension size from 1024 to 512.
[Nest] 210  - 07/23/2024, 11:46:57 AM     LOG [Api:SystemConfigService~lhrbcksl] LogLevel=log (set via system config)
[07/23/24 11:47:05] INFO     Loading visual model 'ViT-B-32__openai' to memory  
[07/23/24 11:47:05] INFO     Setting execution providers to                     
                             ['CPUExecutionProvider'], in descending order of   
                             preference
```

**Comment by danieldietzler** [comment]
Hey, is this still an issue?

**Comment by Michael-XKCD** [comment]
Same issue here.

**Comment by maicss** [comment]
![image](https://github.com/user-attachments/assets/a8b7fa74-722b-4fb4-9aca-3f4713a13287)

I download the `ViT-B-32__openai` manually:

1. `cd model-cache`
2. ` apt install git-lfs & git lfs install`
3. `git clone https://huggingface.co/immich-app/ViT-B-32__openai`

And `ls -lah` output:
```
# I am the root user
➜  model-cache ls -lah
total 16K
drwxr-xr-x 4 root root 4.0K Dec  2 02:35 .
drwxr-xr-x 5 kk   kk   4.0K Jul 25 00:25 ..
drwxr-xr-x 5 root root 4.0K Dec  2 02:23 ViT-B-32__openai
```

And `tree -pu` output:

```
[drwxr-xr-x root    ]  .
├── [drwxr-xr-x root    ]  ViT-B-32__openai
│   ├── [-rw-r--r-- root    ]  config.json
│   ├── [-rw-r--r-- root    ]  README.md
│   ├── [drwxr-xr-x root    ]  textual
│   │   ├── [drwxr-xr-x root    ]  fp16
│   │   │   └── [-rw-r--r-- root    ]  model.armnn
│   │   ├── [-rw-r--r-- root    ]  merges.txt
│   │   ├── [-rw-r--r-- root    ]  model.onnx
│   │   ├── [-rw-r--r-- root    ]  special_tokens_map.json
│   │   ├── [-rw-r--r-- root    ]  tokenizer_config.json
│   │   ├── [-rw-r--r-- root    ]  tokenizer.json
│   │   └── [-rw-r--r-- root    ]  vocab.json
│   └── [drwxr-xr-x root    ]  visual
│       ├── [drwxr-xr-x root    ]  fp16
│       │   └── [-rw-r--r-- root    ]  model.armnn
│       ├── [-rw-r--r-- root    ]  model.armnn
│       ├── [-rw-r--r-- root    ]  model.onnx
│       └── [-rw-r--r-- root    ]  preprocess_cfg.json
```

Still got logs above. Can anyone helps with this? Thank you very much!!

**Comment by ramondsq** [comment]
You should put `ViT-B-32__openai` under `/cache/clip/` and put facial recognition models under `/cache/facial-recognition/`, which is not mentioned in official docs. I got the idea of this from [here](https://github.com/immich-app/immich/issues/6616#:~:text=This%20is%20what%20I%20have%20for%20my%20volume)

**Comment by danieldietzler** [comment]
This sounds fixed to me. If not please let us know
