### ISSUE TITLE
Changing path of library results in not working admin tab

### ISSUE THREAD

**Issue by DeltaTango69** [immich-app/immich#11687]
### The bug

when I change the upload path in the env the upload folder can't be found.

for example

before is working:

```
# The location where your uploaded files are stored
 UPLOAD_LOCATION=./library
 THUMB_LOCATION=./library/thumbs
 ENCODED_VIDEO_LOCATION=./library/encoded-video
 PROFILE_LOCATION=./library/profile
```

this works not!
```
 UPLOAD_LOCATION=./library/upload
 THUMB_LOCATION=./library/thumbs
 ENCODED_VIDEO_LOCATION=./library/encoded-video
 PROFILE_LOCATION=./library/profile
```

### The OS that Immich Server is running on

Windows 11

### Version of Immich Server

V1.111.0

### Version of Immich Mobile App

V1.111

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
see above
```

### Your .env content

```Shell
see above
```

### Reproduction steps

```bash
see above
```

### Relevant log output

```shell
2024-07-12 11:56:33 immich_server            | [Nest] 19  - 07/12/2024, 11:56:33 AM   ERROR [Api:Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'
2024-07-12 11:56:33 immich_server            |     at async Object.statfs (node:internal/fs/promises:1043:18)
2024-07-12 11:56:33 immich_server            |     at async StorageRepository.checkDiskUsage (/usr/src/app/dist/repositories/storage.repository.js:126:23)
2024-07-12 11:56:33 immich_server            |     at async ServerService.getStorage (/usr/src/app/dist/services/server.service.js:75:26)~f3rip7bh] Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'
```

**Comment by DeltaTango69** [comment]
this works  UPLOAD_LOCATION="e:/upload"
I think something is wrong with my SMB mount?!
