### ISSUE TITLE
Error after crop and save to gallery

### ISSUE THREAD

**Issue by lukanowa** [immich-app/immich#11800]
### The bug

After cropping a photo and trying to save it to the gallery:
![Screenshot_20240815_103146](https://github.com/user-attachments/assets/9cccb659-4afd-430f-b71d-e4756af651d7)

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.112.0-1

### Version of Immich Mobile App

1.112.1 b154

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
.
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
1. Crop photo,
2. Save to gallery
3. Error: Null check operator used on a null value
```

**Comment by etymotic** [comment]
I have the same error when cropping images on Android. App version is 1.112.1 installed from github through Obtanium. 

Docker logs for immich_server don't show anything unusual.

**Comment by helloworld1987** [comment]
I have the same issue on Docker/Debian.

**Comment by Benedolt** [comment]
I get exactly the same issue. I didn't even crop, just rotate from the mobile app. 

- Android App v1.112.1 build.154
- Server (Docker) v1.112.1

**Comment by mikerjensen** [comment]
Same issue, on a Pixel 7A.  I think i've had about 2 successful crops out of about 10 attempts. Most of the crops don't appear anywhere on the phone or on the server, despite the 'Image saved' notification (which appears before the 'Null check operator...' notification.
    Android App v1.112.1 build.154
    Server (Docker) v1.112.1

Not sure it's related, but often when i launch the Android app, i just get the Immich logo frozen on the screen for a minute or so before loading the thumbnails.

**Comment by plord12** [comment]
I saw the same error when trying a rotate (no crop).

**Comment by jakev383** [comment]
Seeing the same issue on a Pixel 8, running Android 14. Immich android app version 1.112.1 build.154, server version 1.112.1 as a docker container. 
On the Android app, I only have "Camera" selected as the album to backup, not "Recent" (picks up images I do not wish backed up in Immich).
Server logs do not really show much at this detail level, just the websocket connect and disconnect. 

Steps to reproduce:

1. Open app and select image to bring it to full screen
2. Select Edit from bottom menu
3. Select Crop from bottom menu
4. Click rotate-right icon, then the checkmark at top right of screen
5. Select "Save to gallery"
6. App pauses for 10 seconds
7. App shows "Images saved!" message
8. 2 seconds later app shows "Null check operator used on null value" message
9. Rotated/edited image is saved to device, but does not show in Immich Photo Browser

Turning the app log level to INFO, I believe this is the relevant log entries to coincide with the app error:
```
2024-08-26 12:25:01.853038 | SEVERE   | ImmichErrorLogger    | PlatformDispatcher - Catch all | Null check operator used on a null value |
#0      MediaQuery._of (package:flutter/src/widgets/media_query.dart:1169)
#1      MediaQuery.of (package:flutter/src/widgets/media_query.dart:1164)
#2      FToast.showToast (package:fluttertoast/fluttertoast.dart:247)
#3      ImmichToast.show (package:immich_mobile/widgets/common/immich_toast.dart:49)
#4      EditImagePage.build.<anonymous closure> (package:immich_mobile/pages/editing/edit.page.dart:107)
<asynchronous suspension>

2024-08-26 11:19:40.316636 | SEVERE   | ImmichErrorLogger    | PlatformDispatcher - Catch all | Null check operator used on a null value |
#0      MediaQuery._of (package:flutter/src/widgets/media_query.dart:1169)
#1      MediaQuery.of (package:flutter/src/widgets/media_query.dart:1164)
#2      FToast.showToast (package:fluttertoast/fluttertoast.dart:247)
#3      ImmichToast.show (package:immich_mobile/widgets/common/immich_toast.dart:49)
#4      EditImagePage.build.<anonymous closure> (package:immich_mobile/pages/editing/edit.page.dart:107)
<asynchronous suspension>

2024-08-26 11:19:07.126812 | SEVERE   | ImmichErrorLogger    | PlatformDispatcher - Catch all | Null check operator used on a null value |
#0      MediaQuery._of (package:flutter/src/widgets/media_query.dart:1169)
#1      MediaQuery.of (package:flutter/src/widgets/media_query.dart:1164)
#2      FToast.showToast (package:fluttertoast/fluttertoast.dart:247)
#3      ImmichToast.show (package:immich_mobile/widgets/common/immich_toast.dart:49)
#4      EditImagePage.build.<anonymous closure> (package:immich_mobile/pages/editing/edit.page.dart:107)
<asynchronous suspension>

2024-08-26 11:19:00.568383 | SEVERE   | ImmichErrorLogger    | PlatformDispatcher - Catch all | Null check operator used on a null value |
#0      MediaQuery._of (package:flutter/src/widgets/media_query.dart:1169)
#1      MediaQuery.of (package:flutter/src/widgets/media_query.dart:1164)
#2      FToast.showToast (package:fluttertoast/fluttertoast.dart:247)
#3      ImmichToast.show (package:immich_mobile/widgets/common/immich_toast.dart:49)
#4      EditImagePage.build.<anonymous closure> (package:immich_mobile/pages/editing/edit.page.dart:107)
<asynchronous suspension>

2024-08-26 11:18:52.252627 | SEVERE   | ImmichErrorLogger    | PlatformDispatcher - Catch all | Null check operator used on a null value |
#0      MediaQuery._of (package:flutter/src/widgets/media_query.dart:1169)
#1      MediaQuery.of (package:flutter/src/widgets/media_query.dart:1164)
#2      FToast.showToast (package:fluttertoast/fluttertoast.dart:247)
#3      ImmichToast.show (package:immich_mobile/widgets/common/immich_toast.dart:49)
#4      EditImagePage.build.<anonymous closure> (package:immich_mobile/pages/editing/edit.page.dart:107)
<asynchronous suspension>

2024-08-26 11:18:32.618419 | INFO     | AssetNotifier        | Load assets: 1090ms |
2024-08-26 11:18:32.618339 | INFO     | AlbumService         | Syncing completed. Changes: false |
2024-08-26 11:18:31.836496 | INFO     | AlbumService         | 'Recents' is not selected, keeping only selected albums |

```

**Comment by jakev383** [comment]
With version 1.113.0 it no longer displays the error message and seems to save the cropped image, although in a different location. Original image was at /storage/emulated/0/DCIM/Camera and crop save location is /storage/emulated/0/Pictures

**Comment by mikerjensen** [comment]
Yes, great progress, i'm now able to save cropped images to the server. Would be great if the cropped image could preserve the date of the original image. And maybe ask if the original (uncropped image) should be deleted?

**Comment by yashrajjain726** [comment]
Great idea @mikerjensen , I would like to proceed, but just needs the confirmation if we wanted to have the functionality of deleting the orginal photo's once it is cropped and saved into new ones ?

**Comment by mikerjensen** [comment]
Thanks, well mostly i delete the original, but sometimes I crop
      the original photo twice - to focus on a different part of the
      image each time, and sometimes one might still want to retain the
      original after making a crop, so it would be good to have
      something like a 'delete original?' dialogue after each crop?
    On 10/7/24 21:17, Yashraj Jain wrote:
    
    
      
      Great idea @mikerjensen
        , I would like to proceed, but just needs the confirmation if we
        wanted to have the functionality of deleting the orginal photo's
        once it is cropped and saved into new ones ?
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/immich-app/immich/issues/11800#issuecomment-2397586935",
"url": "https://github.com/immich-app/immich/issues/11800#issuecomment-2397586935",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yashrajjain726** [comment]
Great, I can start working on this. But I think this card isn't relevant to the issue that we are proceeding on, so can we start with a new issue, where we can start there and close this issue, as this is fixed.

**Comment by yashrajjain726** [comment]
Hey @mikerjensen , as you mentioned, I have added the new functionality of asking a user to delete the orginal image after the crop functionality.

**Comment by mikerjensen** [comment]
This is really great!, I can't wait to try it! Also wondering if
      some key image info might be preserved - perhaps you also included
      that in the upcoming version, as currently it seems that that the
      cropped image no longer includes the location info?
    On 10/8/24 12:23, Yashraj Jain wrote:
    
      
      Hey @mikerjensen
        , as you mentioned, I have added the new functionality of asking
        a user to delete the orginal image after the crop functionality.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/immich-app/immich/issues/11800#issuecomment-2399325464",
"url": "https://github.com/immich-app/immich/issues/11800#issuecomment-2399325464",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by plord12** [comment]
> With version 1.113.0 it no longer displays the error message and seems to save the cropped image, although in a different location. Original image was at /storage/emulated/0/DCIM/Camera and crop save location is /storage/emulated/0/Pictures

I see the same with 1.118.0.  ie, on android -

Edit photo - say apply rotation
Save to gallery
"Image Saved" reported
Image is saved in /storage/Pictures directory and doesn't make it back to immich

**Comment by patienttruth** [comment]
> > With version 1.113.0 it no longer displays the error message and seems to save the cropped image, although in a different location. Original image was at /storage/emulated/0/DCIM/Camera and crop save location is /storage/emulated/0/Pictures
> 
> I see the same with 1.118.0. ie, on android -
> 
> Edit photo - say apply rotation Save to gallery "Image Saved" reported Image is saved in /storage/Pictures directory and doesn't make it back to immich

I came here looking to see if there was a way to change locations of the save. I'm not sure if this is the case for you, but I excluded "pictures" from my backup, so I assume that's why my edit doesn't make it back into Immich.

In any case, the end result for me too is that the edit doesn't make it back into Immich which is not ideal.

@yashrajjain726 bummer on the closed PR. A lot of times I'm cropping something to save for documentation (like a photo of a part number) and the original is redundant. It gets trashed anyway. Thanks for trying!

**Comment by rsmanning** [comment]
I'm not getting any errors.  I rotate in android app and save to gallery and it goes back to the main screen with no changes and nothing rotated.

**Comment by gleeballs** [comment]
@rsmanning > I'm not getting any errors. I rotate in android app and save to gallery and it goes back to the main screen with no changes and nothing rotated.

Image is saved in /storage/Pictures directory and doesn't make it back to immich

I am also frustrated with this as I need to manually remember to move the files back tot the Camera folder so they can back up.

I do not want to have to backup my whole /Pictures folder as I have apps that put a load of crap in there that I don't want backed up.

We need to be able to either 

a) have the edited image save back to the Camera folder or
b) change the edit pictures gallery location

**Comment by bo0tzz** [comment]
It seems like the original bug was long fixed, and the new editing implementation is on its way, so I'll close this thread.
