### ISSUE TITLE
Extremely long images appears "squashed" when the original is loaded on mobile app

### ISSUE THREAD

**Issue by ChiNoel-osu** [immich-app/immich#11987]
### The bug

If I want to view an extremely long image (for example 50000x1000 in resolution) from the Immich mobile app, the image appears to be "squashed" after loading the original so a circle now looks like a ellipse.
The original file is not "squashed" I think, it's just a visual bug.

I'm on iOS, not sure about Android.

### The OS that Immich Server is running on

Ubuntu Server 24.04 LTS

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

1.112.1 build.169

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I don't think this is relevant.
```

### Your .env content

```Shell
I don't think this is relevant.
```

### Reproduction steps

```bash
1. Have a extremely long image on Immich server.
2. Open the Immich mobile app and connect to the server.
3. From Setting->Asset Viewer, enable "Load original image".
4. Go to the main page and tap on the extremely long image and wait for it to load the original.
5. After it loads the original image, the image appears to be "squashed".
```

**Comment by ChiNoel-osu** [comment]
Also I can't really move the image when zoomed in on a long image, but that's for another issue I think.

**Comment by ChiNoel-osu** [comment]
Example image:
![test](https://github.com/user-attachments/assets/e0d05c3d-c4e8-4341-b6fe-98e4e8a24d6b)

The squares in image will become rectangles in immich.

**Comment by ChiNoel-osu** [comment]
Immich APP:
![IMG_7018](https://github.com/user-attachments/assets/6350ca3d-a078-42c5-8c6d-fc8d2004db70)
Immich Web:
<img width="1280" alt="Screenshot 2024-10-27 222735" src="https://github.com/user-attachments/assets/db970197-64bf-453b-8774-a11e9fbb632b">

**Comment by ChiNoel-osu** [comment]
Updating issue description. This issue still exists in the latest version.

**Comment by LeLunZ** [comment]
@ChiNoel-osu for me the image is fully visible on the latest version just like on your web screenshot. The only issue is that I can't generate a thumbnail for your photo

**Comment by ChiNoel-osu** [comment]
@LeLunZ Hmm, I just tested on latest version of the app (2.7.5 build.256), the image is still squished.
I'm on iOS 26.4.1, iPhone 13 mini (updating description)

**Comment by LeLunZ** [comment]
Interesting I am also on the 13 mini with iOS 26.4.1

**Comment by ChiNoel-osu** [comment]
@LeLunZ That is so weird. I downloaded my example image before and now it's appearing normally. However, I suspect this is because Immich is not loading the original at all (which is another problem on its own). The edge of the squares are not sharp as it should be.
To be more prominent, I created another example below.
If I upload this image to my phone and open Immich to sync it, Immich is loading the original, and and image appears squished after original has loaded.
If I upload this image to immich from my PC and open this image in Immich Mobile, the original is not loading (can confirm by monitoring network usage), and the image is blurry.

loooong image below

<img width="1111" height="56870" alt="Image" src="https://github.com/user-attachments/assets/02da6fcd-4af2-40b6-bd8f-3ef9c3f599d1" />

**Comment by LeLunZ** [comment]
Do you have "load original image" on in your immich settings on your phone?

**Comment by ChiNoel-osu** [comment]
> Do you have "load original image" on in your immich settings on your phone?

I do

**Comment by LeLunZ** [comment]
Could you download the generated previews for both pictures and upload them here?

**Comment by ChiNoel-osu** [comment]
> Could you download the generated previews for both pictures and upload them here?

@LeLunZ Not sure where to find the generated previews, but I do see some errors regarding big images:
```
[Nest] 7  - 05/22/2026, 12:00:00 AM     LOG [Microservices:LibraryService] Initiating scan of all external libraries...
[Nest] 7  - 05/22/2026, 12:00:00 AM     LOG [Microservices:LibraryService] Checking for any libraries pending deletion...
[Nest] 7  - 05/22/2026, 2:00:00 AM     LOG [Microservices:DatabaseBackupService] Database Backup Starting. Database Version: 14
/usr/lib/postgresql/14/bin/pg_dump exited (0)
gzip exited (0)
[Nest] 7  - 05/22/2026, 2:00:17 AM     LOG [Microservices:DatabaseBackupService] Database Backup Success
[Nest] 7  - 05/22/2026, 3:00:00 AM     LOG [Microservices:SessionService] Deleted 0 expired session tokens
[Nest] 7  - 05/22/2026, 3:00:00 AM     LOG [Microservices:MemoryService] Creating memories for 2026-05-25T00:00:00.000Z
[Nest] 7  - 05/22/2026, 3:00:03 AM   ERROR [Microservices:{"id":"c70479f3-b7d0-42a3-a9d1-3d2fe5709dd9"}] Unable to run job handler (AssetGenerateThumbnails): Error: Processed image is too large for the WebP format
Error: Processed image is too large for the WebP format
    at Sharp.toFile (/usr/src/app/server/node_modules/.pnpm/sharp@0.34.5/node_modules/sharp/lib/output.js:90:19)
    at MediaRepository.generateThumbnail (/usr/src/app/server/dist/repositories/media.repository.js:149:23)
    at async Promise.all (index 1)
    at async MediaService.generateImageThumbnails (/usr/src/app/server/dist/services/media.service.js:276:25)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/server/dist/services/media.service.js:153:25)
    at async JobService.onJobRun (/usr/src/app/server/dist/services/job.service.js:51:30)
    at async EventRepository.onEvent (/usr/src/app/server/dist/repositories/event.repository.js:91:13)
    at async /usr/src/app/server/node_modules/.pnpm/bullmq@5.71.0/node_modules/bullmq/dist/cjs/classes/worker.js:570:32
[Nest] 7  - 05/22/2026, 3:00:09 AM   ERROR [Microservices:{"id":"92043dcc-f26c-42c0-a731-2b4a9cf1041d"}] Unable to run job handler (AssetGenerateThumbnails): Error: Processed image is too large for the JPEG format
Error: Processed image is too large for the JPEG format
    at Sharp.toFile (/usr/src/app/server/node_modules/.pnpm/sharp@0.34.5/node_modules/sharp/lib/output.js:90:19)
    at MediaRepository.generateThumbnail (/usr/src/app/server/dist/repositories/media.repository.js:149:23)
    at async Promise.all (index 2)
    at async MediaService.generateImageThumbnails (/usr/src/app/server/dist/services/media.service.js:276:25)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/server/dist/services/media.service.js:153:25)
    at async JobService.onJobRun (/usr/src/app/server/dist/services/job.service.js:51:30)
    at async EventRepository.onEvent (/usr/src/app/server/dist/repositories/event.repository.js:91:13)
    at async /usr/src/app/server/node_modules/.pnpm/bullmq@5.71.0/node_modules/bullmq/dist/cjs/classes/worker.js:570:32
```

**Comment by ChiNoel-osu** [comment]
Another one of my findings:
Enabling "Prefer remote images" in the app setting will prevent loading the original long images from local, therefore they're not "squished". However the remote original images are never loaded, they'll be blurry.
