### ISSUE TITLE
Backup on mobile stops when encountering unsupported formats instead of skipping them

### ISSUE THREAD

**Issue by toorux** [immich-app/immich#12191]
### The bug

There are some .pic format photos in my iPhone album that cannot be backed up, and the app stops the backup process completely when encountering these photos. I have to delete the .pic format photos from my album to resume the backup, which is very inconvenient. Synology Photos automatically skips such files when it encounters this issue, which I believe is a more reasonable approach. Of course, I would prefer if the app could support the .pic format.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.113.0

### Version of Immich Mobile App

v1.113.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
irrelevant
```

### Your .env content

```Shell
irrelevant
```

### Reproduction steps

1. Save a picture in pic format in a photo album
2. Backup this album in the immich app
3. When the backup reaches this pic, it will indicate that the format is not supported and stop the backup.

**Comment by alextran1502** [comment]
Can you help with the step to produce the .pic format?

**Comment by toorux** [comment]
> Can you help with the step to produce the .pic format?

@alextran1502 I'm not sure why the images in my photo album are in pic format, as they were saved through another app. If necessary, I can send you one, but I'll need your email address.

**Comment by Cohinem** [comment]
This also happens to me. I would expect it to write the error and continue on with the backup at least.

This is me trying several times.
```
[Nest] 17  - 08/31/2024, 5:32:14 PM   ERROR [Api:AssetMediaService] Unsupported file type obfuscated.jpg_large
[Nest] 17  - 08/31/2024, 5:33:25 PM   ERROR [Api:AssetMediaService~gj3ca4rd] Unsupported file type obfuscated.jpg_large
[Nest] 17  - 08/31/2024, 5:34:02 PM   ERROR [Api:AssetMediaService~2bgzx03r] Unsupported file type obfuscated.jpg_large
[Nest] 17  - 08/31/2024, 5:34:20 PM   ERROR [Api:AssetMediaService] Unsupported file type obfuscated.jpg_large

```

**Comment by MattKayDev** [comment]
I've had this happen as well. 

The current work around is restarting backup manually, but that's not ideal.

**Comment by loki29pl** [comment]
I have the same issue, but I have pdf in iCloud photos database

**Comment by sladg** [comment]
I'm seeing same issue on iPhone. Immich runs through like 20k of assets without issue and then starts failing on random assets when nearing the finish. It's couple of HEIC photos (tried to sync different albums and got different HEIC file names).

Server will throw following:
```
 [Nest] 7  - 02/17/2025, 9:33:28 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
 [Nest] 7  - 02/17/2025, 9:33:28 PM   ERROR [Microservices:JobService] Error: Input file contains unsupported image format
     at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
     at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
     at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
     at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
 [Nest] 7  - 02/17/2025, 9:33:28 PM   ERROR [Microservices:JobService] Object(2) {
   id: '1f840795-0be4-451b-9071-20ed3eeb3734',
   source: 'upload'
 }
```

Mobile client won't input any useful logs, it would just stop processing the remaining assets without any warnings/errors in log.

Is it possible for Immich to continue processing and do sth like blacklist for those files? So I can get list of those and remove them manually later from phone? Currently, I would have to tediously one-by-one find the offending file, try to delete, try to re-upload and wait for new file to fail it.

 :/ any guidance/help is appreciated

running 1.126.1 and 1.126.1 build 194

**Comment by Cohinem** [comment]
> Currently, I would have to tediously one-by-one find the offending file, try to delete, try to re-upload and wait for new file to fail it.

Thats exactly what I had to do. Anyway if it's just a certain extension then just search for all files with it (.png) for example in the files explorer and rename them all to a different supported extension.
