### ISSUE TITLE
Metadata extraction does not tolerate bad "Rating" field in EXIF

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#12476]
Introduced in #11580. @stumpigit if you're willing to PR a fix that would be much appreciated (but no pressure).

The value probably just needs `validate()` called on it, and ideally a test is written to cover this case as well.

Related: #2229

```
[Nest] 7  - 09/08/2024, 9:43:37 AM VERBOSE [Microservices:MetadataService] Exif Tags
[Nest] 7  - 09/08/2024, 9:43:37 AM VERBOSE [Microservices:MetadataService] Object:
{
  (snip)
  "Rating": "Entity= Criteria= ",
  (...)
}

[Nest] 7  - 09/08/2024, 9:43:37 AM   ERROR [Microservices:JobService] Unable to run job handler (metadataExtraction/metadata-extraction): QueryFailedError: invalid input syntax for type integer: "Entity= Criteria= "
[Nest] 7  - 09/08/2024, 9:43:37 AM   ERROR [Microservices:JobService] QueryFailedError: invalid input syntax for type integer: "Entity= Criteria= "
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async AssetRepository.upsertExif (/usr/src/app/dist/repositories/asset.repository.js:49:9)
    at async MetadataService.handleMetadataExtraction (/usr/src/app/dist/services/metadata.service.js:201:9)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```

**Comment by stumpigit** [comment]
Thanks for the hint. I will be happy to look into this over the next few days.
