### ISSUE TITLE
Android/Ios app cannot play video only saved on server

### ISSUE THREAD

**Issue by juvraniak** [immich-app/immich#12910]
### The bug

As mentioned in title mobile apps struggle to load video from server.

I have tested with transcoding on/off
tested with HEVC video as well h.264(should have better compatibility) nothing seems to help (config in samsung s23 ultra)
Also tested if i can download video(test if there is wrong refId to video) but it downloaded fine.

I have increased log level to Debug, and did not see anything interesting
`024-09-24 20:01:07.004223+02:00[95m[Nest] 16  - [39m09/24/2024, 8:01:07 PM [95m  DEBUG[39m [33m[Api:LoggingInterceptor~3omasnym][39m [95mGET /api/server-info/ping 200 0.11ms ::ffff:172.16.0.1[39m
2024-09-24 20:01:08.697340+02:00[95m[Nest] 16  - [39m09/24/2024, 8:01:08 PM [95m  DEBUG[39m [33m[Api:LoggingInterceptor~0sxrlpww][39m [95mGET /api/assets/device/e8d356df30407ed219a1118d0a85ff0bb9e81c2ede39f3184604ded0f7f04ae9 200 49.95ms 95.102.226.55[39m
2024-09-24 20:01:10.201175+02:00[95m[Nest] 16  - [39m09/24/2024, 8:01:10 PM [95m  DEBUG[39m [33m[Api:LoggingInterceptor~8bl0x2m5][39m [95mPOST /api/auth/validateToken 200 0.14ms 95.102.226.55[39m`

Here is error i can see in application:
`Instance of 'FlutterErrorDetails'
Exception: PlatformException(VideoError, Video player had error j1.l: Source error, null, null)
Library: widgets library
Context: Instance of 'ErrorDescription'`
`#1      AsyncError.value (package:riverpod/src/common.dart:494:0)
#2      VideoViewerPage.build (package:immich_mobile/pages/common/video_viewer.page.dart:36:0)
#3      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476:0)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5729:0)
#5      ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539:0)
#6      HookElement.build (package:flutter_hooks/src/framework.dart:438:0)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617:0)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:0)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5333:0)
#10     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:0)
#11     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:0)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:0)
#13     _LayoutBuilderElement._rebuildWithConstraints (package:flutter/src/widgets/layout_builder.dart:231:0)
#14     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2719:0)
#15     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1098:0)
#16     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2719:0)
#17     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:278:0)
#18     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:369:0)
#19     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2446:0)
#20     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1052:0)
#21     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1065:0)
#22     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:602:0)
#23     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164:0)
#24     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:0)
#25     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:0)
#26     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:0)
#27     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:0)
#28     _invoke (dart:ui/hooks.dart:312:0)
#29     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:0)
#30     _drawFrame (dart:ui/hooks.dart:283:0)`

If i forgot to add any detail please let me know.

### The OS that Immich Server is running on

TrueNAS Scale Dragonfish-24.04.2.2

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0 build.159

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
https://github.com/truenas/charts/tree/master/community/immich
```

### Your .env content

```Shell
https://github.com/truenas/charts/tree/master/community/immich
```

### Reproduction steps

Steps to reproduce:
1. Make a video
2. Sync with server
3. Play video - this works
4. Delete video localy
5. Play it from server - fails(on web no problem)

Second scenario is when video is uploaded from camera and try to play on mobile -> results in failure

**Comment by bo0tzz** [comment]
Is this a duplicate of #11689?

**Comment by juvraniak** [comment]
Well may be, sorry did not look into that issue, as i taugt it has to do only with older devices.
