### ISSUE TITLE
V1.116 map.lightStyle value

### ISSUE THREAD

**Issue by chrichrichri** [immich-app/immich#12961]
### The bug

I have updated to v1.116. I have a config file defined, which is based on the [default config file](https://immich.app/docs/install/config-file/). Before the update, everything worked fine. Now the `immich_server` crashes with the error below.

The respective value of the config file is like this:

```
"map": {
    "enabled": true,
    "lightStyle": "",
    "darkStyle": ""
  },
```

What should I use as default value instead?

### The OS that Immich Server is running on

NixOs

### Version of Immich Server

1.116.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not relevant for issue
```

### Your .env content

```Shell
Not relevant for issue
```

### Reproduction steps

1. Start the server with the config file and the map-settings as described above.

### Relevant log output

```shell
immich_server            | Detected CPU Cores: 2
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_server            | [Nest] 6  - 09/26/2024, 6:32:26 PM     LOG [Microservices:EventRepository] Initialized websocket server
immich_server            | [Nest] 6  - 09/26/2024, 6:32:26 PM    WARN [Microservices:DuplicateService] Unknown keys found: {
immich_server            |   "library": {
immich_server            |     "watch": {
immich_server            |       "usePolling": false,
immich_server            |       "interval": 10000
immich_server            |     }
immich_server            |   }
immich_server            | }
immich_server            | Error: Invalid value(s) in file: An instance of SystemConfigDto has failed the validation:
immich_server            |  - property map.lightStyle has failed the following constraints: isUrl, isNotEmpty
immich_server            |  - property map.darkStyle has failed the following constraints: isUrl, isNotEmpty
immich_server            |
immich_server            |     at SystemConfigCore.buildConfig (/usr/src/app/dist/cores/system-config.core.js:129:23)
immich_server            |     at async /usr/src/app/dist/cores/system-config.core.js:80:35
immich_server            | microservices worker error: Error: Invalid value(s) in file: An instance of SystemConfigDto has failed the validation:
immich_server            |  - property map.lightStyle has failed the following constraints: isUrl, isNotEmpty
immich_server            |  - property map.darkStyle has failed the following constraints: isUrl, isNotEmpty
immich_server            |
immich_server            | microservices worker exited with code 1
```

**Comment by bo0tzz** [comment]
Remove those empty fields from your config
