### ISSUE TITLE
machine-learning image fails to start with IMMICH_HOST= set to bare IPv6 address

### ISSUE THREAD

**Issue by frebib** [immich-app/immich#13782]
### The bug

Setting `IMMICH_HOST=::` causes the container to crashloop
```
+ gunicorn app.main:app -k app.config.CustomUvicornWorker -c gunicorn_conf.py -b :::3003 -w 1 -t 120 --log-config-json log_conf.json --keep-alive 2 --graceful-timeout 0

Error: '' is not a valid port number.
```

Setting `IMMICH_HOST=[::]` allows it to start

`IMMICH_HOST=::` is the correct representation here. The container needs to identify that it's an IPv6 address and handle it correctly/add the square brackets.

### The OS that Immich Server is running on

Debian, Docker

### Version of Immich Server

v1.119.0

**Comment by mmomjian** [comment]
This looks to be behaving according to the gunicorn docs: https://docs.gunicorn.org/en/stable/settings.html#bind

**Comment by frebib** [comment]
@mmomjian Problem is, it's not consistent with the immich server container. That behaves the opposite way. `::` works but `[::]` is invalid. I'm not entirely sure how gunicorn is invoked, but this is squarely a "immich doesn't work as it should" problem, regardless of how the backing software works. Crashlooping is never "expected behaviour"

**Comment by frebib** [comment]
The issue is that you're not correctly invoking gunicorn here https://github.com/immich-app/immich/blob/main/machine-learning/start.sh#L21

**Comment by frebib** [comment]
See https://datatracker.ietf.org/doc/html/rfc6874#section-2 for how IPv6 should be treated.
As a bare literal, it should be raw hex and colos, e.g. `abcd:1234::` and in a URI it should be enclosed in square brackets e.g. `[abcd:1234::]:567`
The `IMMICH_HOST` variable as per your documentation is a raw literal: https://immich.app/docs/install/environment-variables#ports
and thus I would expect `IMMICH_HOST=abcd:1234::` to work for both the immich server and immich machine-learning services to work the same, but it does not as per 1.119.0

**Comment by mertalev** [comment]
We can check if it's a valid IPv6 address in `start.sh` and add braces if so.

**Comment by Trevinlc1997** [comment]
I am experiencing this currently, setting IMMICH_HOST with [::] works for machine learning but for IMMICH_SERVER you end up with this error. This is on a IPv6 only network (LAN/WAN)

```
[Nest] 7  - 08/16/2025, 12:46:25 AM    WARN [Microservices:Error: Failed to fetch GitHub release: TypeError: fetch failed
    at ServerInfoRepository.getGitHubRelease (/usr/src/app/server/dist/repositories/server-info.repository.js:60:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async VersionService.handleVersionCheck (/usr/src/app/server/dist/services/version.service.js:111:77)
    at async VersionService.onBootstrap (/usr/src/app/server/dist/services/version.service.js:64:9)
    at async EventRepository.onEvent (/usr/src/app/server/dist/repositories/event.repository.js:126:13)
    at async MicroservicesModule.onModuleInit (/usr/src/app/server/dist/app.module.js:83:9)
    at async callModuleInitHook (/usr/src/app/server/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
    at async NestApplication.callInitHook (/usr/src/app/server/node_modules/@nestjs/core/nest-application-context.js:242:13)
    at async NestApplication.init (/usr/src/app/server/node_modules/@nestjs/core/nest-application.js:103:9)
    at async NestApplication.listen (/usr/src/app/server/node_modules/@nestjs/core/nest-application.js:175:13)] Unable to run version check: Error: Failed to fetch GitHub release: TypeError: fetch failed

[Nest] 7  - 08/16/2025, 12:46:25 AM     LOG [Microservices:SystemConfigService] LogLevel=log (set via system config)
[Nest] 18  - 08/16/2025, 12:46:25 AM     LOG [Api:DatabaseRepository] targetLists=1, current=1 for clip_index of 3669 rows
[Nest] 18  - 08/16/2025, 12:46:25 AM     LOG [Api:DatabaseRepository] targetLists=1, current=1 for face_index of 662 rows

Error: getaddrinfo ENOTFOUND [::]
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '[::]'
}

microservices worker error: Error: getaddrinfo ENOTFOUND [::], stack: Error: getaddrinfo ENOTFOUND [::]
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26)
microservices worker exited with code 1

Killing api process

```

**Comment by bo0tzz** [comment]
@Trevinlc1997 is that the complete log or did you remove parts?
