### ISSUE TITLE
无法在 realme Q3 5g 手机上运行

### ISSUE THREAD

**Issue by Dean1990** [immich-app/immich#13890]
### The bug

手机型号：realme q3 5g
处理器：高通骁龙750G 八核
运行内存： 8.00G
Android版本：12
realme UI版本 V3.0
故障：启动App时闪退
截取日志：
Flutter initialization failed.
                                                                                                    java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Could not load libflutter.so this is possibly because the application is running on an architecture that Flutter Android does not support (e.g. x86) see https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures for more detail.
                                                                                                    App is using cpu architecture: aarch64, and the native libraries directory (with path /data/app/~~Y2Qoy0AS2FkWTQr23h3Lpw==/app.alextran.immich-BFG85tq_UjdQOYg8_GA8Mw==/lib/arm64) contains the following files: null
                                                                                                    	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
                                                                                                    	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
                                                                                                    	at ma.f.h(Unknown Source:29)
                                                                                                    	at io.flutter.embedding.engine.d.<init>(Unknown Source:35)
                                                                                                    	at io.flutter.embedding.android.e.K(Unknown Source:172)
                                                                                                    	at io.flutter.embedding.android.e.s(Unknown Source:7)
                                                                                                    	at io.flutter.embedding.android.d.onCreate(Unknown Source:13)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8145)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8125)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3750)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3943)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2348)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:233)
                                                                                                    	at android.os.Looper.loop(Looper.java:344)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8191)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
                                                                                                    Caused by: java.lang.UnsupportedOperationException: Could not load libflutter.so this is possibly because the application is running on an architecture that Flutter Android does not support (e.g. x86) see https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures for more detail.
                                                                                                    App is using cpu architecture: aarch64, and the native libraries directory (with path /data/app/~~Y2Qoy0AS2FkWTQr23h3Lpw==/app.alextran.immich-BFG85tq_UjdQOYg8_GA8Mw==/lib/arm64) contains the following files: null
                                                                                                    	at ma.f$a.b(Unknown Source:168)
                                                                                                    	at ma.f$a.call(Unknown Source:0)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(Unknown Source:13)
                                                                                                    	at ma.f$a.b(Unknown Source:19)
                                                                                                    	at ma.f$a.call(Unknown Source:0) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 

### The OS that Immich Server is running on

android 12

### Version of Immich Server

1.119.1

### Version of Immich Mobile App

1.119.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
1
```

### Your .env content

```Shell
1
```

### Reproduction steps

1.
2.
3.
...

**Comment by bo0tzz** [comment]
Can you give a bit more detail about what's happening? Does the app just never launch, does it crash after using it for a bit, or what exactly is going on?

**Comment by Dean1990** [comment]
> Can you give a bit more detail about what's happening? Does the app just never launch, does it crash after using it for a bit, or what exactly is going on?

由于我的网络环境问题，无法直接使用google play ，所以我使用以下链接下了的应用，arches选择了arm64-v8a。
https://apkcombo.com/downloader?__cf_chl_tk=1xRiiPKqUhwBOM4mykAg4NweoKgXPO70rGZYMU.MjE0-1730630452-1.0.1.1-lXj1Os7vKQ9NVj47TphgMrpv_g8J0ARfF.hWre7Kx1Y#package=app.alextran.immich&device=phone&sdk=31&arches=arm64-v8a

得到了一个 .xapk的包，解压后，在解压目录里执行命令：
adb install-multiple *.apk

安装成功，但是无法打开这个应用，上面有提到报错内容。

我查看了应用安装后占用空间的大小，与我的其他手机显示的不一样，这个有错误的手机上该应用的大小只有7MB，这明显是不对的

**Comment by bo0tzz** [comment]
Don't download apps from sketchy websites like that, you're bound to get into trouble. We attach APKs to the assets on our github releases https://github.com/immich-app/immich/releases/tag/v1.119.1.

**Comment by Dean1990** [comment]
> Don't download apps from sketchy websites like that, you're bound to get into trouble. We attach APKs to the assets on our github releases https://github.com/immich-app/immich/releases/tag/v1.119.1.

非常感谢，问题解决了！
