### ISSUE TITLE
android app does not detect any images in camera folder

### ISSUE THREAD

**Issue by CaptainTrex** [immich-app/immich#13934]
### The bug

I'm having a problem with the latest version of the Immich app. Since version 1.119, the app has not been able to recognize or detect any images in the camera folder. However, the problem is resolved when I downgrade the app to version 1.118. This problem only occurs with the camera folder. The app can see files in every other folder except the camera folder.

### The OS that Immich Server is running on

Fedora

### Version of Immich Server

v1.119.1

### Version of Immich Mobile App

v1.119

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT SUM(checksum_failures) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    volumes:
      - ./db_dumps:/db_dumps
    depends_on:
      - database

volumes:
  model-cache:

networks:
  default:
    name: cloudpipe
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. select camera folder for backup
nothing will happen as the app will not find any file in that folder.
also can not  see the pics in that folder by clicking the gallery button next to in in selection menu.

### Relevant log output

```shell
2024-11-05 22:00:06.353607 | SEVERE   | ImmichErrorLogger    | PlatformDispatcher - Catch all | PlatformException(The getAssetListRange method has an error: Asset (13717) does not exists at its path (/storage/emulated/0/DCIM/Camera/PXL_20241027_152729296.jpg)., java.lang.RuntimeException: Asset (13717) does not exists at its path (/storage/emulated/0/DCIM/Camera/PXL_20241027_152729296.jpg).
	at n6.e$b.J(Unknown Source:7)
	at n6.a.D(Unknown Source:0)
	at n6.e$b.K(Unknown Source:80)
	at n6.a.m(Unknown Source:0)
	at n6.e$b.L(Unknown Source:7)
	at n6.a$b.b(Unknown Source:13)
	at n6.a$b.a(Unknown Source:2)
	at n6.a.M(Unknown Source:18)
	at n6.a.w(Unknown Source:131)
	at j6.b.k(Unknown Source:31)
	at j6.h.k(Unknown Source:1112)
	at j6.h.e(Unknown Source:0)
	at j6.h$d.b(Unknown Source:20)
	at j6.h$d.c(Unknown Source:0)
	at j6.h$b.c(Unknown Source:5)
	at j6.h$b.a(Unknown Source:0)
	at j6.i.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
, {start: 0, end: 662, id: -1739773001, type: 3, option: {type: 0, child: {image: {duration: {min: 0, allowNullable: false, max: 86400000}, size: {minHeight: 0, maxHeight: 100000, minWidth: 0, maxWidth: 100000, ignoreSize: false}, title: true}, updateDate: {min: 0, max: 1730824206253, ignore: true}, containsLivePhotos: true, containsPathModified: true, orders: [], video: {duration: {min: 0, allowNullable: false, max: 86400000}, size: {minHeight: 0, maxHeight: 100000, minWidth: 0, maxWidth: 100000, ignoreSize: false}, title: true}, audio: {duration: {min: 0, allowNullable: false, max: 86400000}, size: {minHeight: 0, maxHeight: 100000, minWidth: 0, maxWidth: 100000, ignoreSize: false}, title: false}, onlyLivePhotos: false, createDate: {min: 0, max: 1730824206253, ignore: false}}}}, null) |
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>
#2      PhotoManagerPlugin.getAssetListRange (package:photo_manager/src/internal/plugin.dart:215)
<asynchronous suspension>
#3      AlbumMediaRepository.getAssets (package:immich_mobile/repositories/album_media.repository.dart:64)
<asynchronous suspension>
#4      BackupNotifier._updateBackupAssetCount (package:immich_mobile/providers/backup/backup.provider.dart:336)
<asynchronous suspension>
#5      BackupControllerPage.build.buildFolderSelectionTile.<anonymous closure> (package:immich_mobile/pages/backup/backup_controller.page.dart:211)
<asynchronous suspension>

2024-11-05 22:00:04.494869 | SEVERE   | ImmichErrorLogger    | PlatformDispatcher - Catch all | PlatformException(The getAssetListRange method has an error: Asset (13717) does not exists at its path (/storage/emulated/0/DCIM/Camera/PXL_20241027_152729296.jpg)., java.lang.RuntimeException: Asset (13717) does not exists at its path (/storage/emulated/0/DCIM/Camera/PXL_20241027_152729296.jpg).
	at n6.e$b.J(Unknown Source:7)
	at n6.a.D(Unknown Source:0)
	at n6.e$b.K(Unknown Source:80)
	at n6.a.m(Unknown Source:0)
	at n6.e$b.L(Unknown Source:7)
	at n6.a$b.b(Unknown Source:13)
	at n6.a$b.a(Unknown Source:2)
	at n6.a.M(Unknown Source:18)
	at n6.a.w(Unknown Source:131)
	at j6.b.k(Unknown Source:31)
	at j6.h.k(Unknown Source:1112)
	at j6.h.e(Unknown Source:0)
	at j6.h$d.b(Unknown Source:20)
	at j6.h$d.c(Unknown Source:0)
	at j6.h$b.c(Unknown Source:5)
	at j6.h$b.a(Unknown Source:0)
	at j6.i.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
, {start: 0, end: 662, id: -1739773001, type: 3, option: {type: 0, child: {image: {duration: {min: 0, allowNullable: false, max: 86400000}, size: {minHeight: 0, maxHeight: 100000, minWidth: 0, maxWidth: 100000, ignoreSize: false}, title: true}, updateDate: {min: 0, max: 1730824204376, ignore: true}, containsLivePhotos: true, containsPathModified: true, orders: [], video: {duration: {min: 0, allowNullable: false, max: 86400000}, size: {minHeight: 0, maxHeight: 100000, minWidth: 0, maxWidth: 100000, ignoreSize: false}, title: true}, audio: {duration: {min: 0, allowNullable: false, max: 86400000}, size: {minHeight: 0, maxHeight: 100000, minWidth: 0, maxWidth: 100000, ignoreSize: false}, title: false}, onlyLivePhotos: false, createDate: {min: 0, max: 1730824204376, ignore: false}}}}, null) |
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>
#2      PhotoManagerPlugin.getAssetListRange (package:photo_manager/src/internal/plugin.dart:215)
<asynchronous suspension>
#3      AlbumMediaRepository.getAssets (package:immich_mobile/repositories/album_media.repository.dart:64)
<asynchronous suspension>
#4      BackupNotifier._updateBackupAssetCount (package:immich_mobile/providers/backup/backup.provider.dart:336)
<asynchronous suspension>
#5      BackupNotifier.getBackupInfo (package:immich_mobile/providers/backup/backup.provider.dart:434)
<asynchronous suspension>
#6      BackupNotifier.startBackupProcess (package:immich_mobile/providers/backup/backup.provider.dart:480)
<asynchronous suspension>
#7      BackupNotifier._resumeBackup (package:immich_mobile/providers/backup/backup.provider.dart:682)
<asynchronous suspension>

2024-11-05 22:00:04.322922 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 31 available albums |
2024-11-05 22:00:04.211567 | SEVERE   | ImmichErrorLogger    | PlatformDispatcher - Catch all | PlatformException(The getAssetListRange method has an error: Asset (13717) does not exists at its path (/storage/emulated/0/DCIM/Camera/PXL_20241027_152729296.jpg)., java.lang.RuntimeException: Asset (13717) does not exists at its path (/storage/emulated/0/DCIM/Camera/PXL_20241027_152729296.jpg).
	at n6.e$b.J(Unknown Source:7)
	at n6.a.D(Unknown Source:0)
	at n6.e$b.K(Unknown Source:80)
	at n6.a.m(Unknown Source:0)
	at n6.e$b.L(Unknown Source:7)
	at n6.a$b.b(Unknown Source:13)
	at n6.a$b.a(Unknown Source:2)
	at n6.a.M(Unknown Source:18)
	at n6.a.w(Unknown Source:131)
	at j6.b.k(Unknown Source:31)
```

**Comment by alextran1502** [comment]
Can you help me check if you can find the file `DCIM/Camera/PXL_20241027_152729296.jpg` on your phone storage? Also, which phone model is this?

**Comment by Ammi55** [comment]
no the file is not present in the folder. I deleted the folder camera and recreated it clicked new photos to see if the app shows them, but same issue.

I am using Poco F1, running Android 10.

**Comment by alextran1502** [comment]
Can you try restart the phone to see if it helps? Is the Camera folder on an SD card or the phone internal storage?

**Comment by CaptainTrex** [comment]
Tried restarting. Cleared app cache and data multiple times. Uninstalled and installed. nothing resolves it.

**Comment by alextran1502** [comment]
Hmm very odd, looks like compatibility issue with this phone model

**Comment by CaptainTrex** [comment]
Don't know man, currently sticking to v1.118

**Comment by CaptainTrex** [comment]
V1.120 fixed it. Thanks

**Comment by sashao** [comment]
Hi, I can't sync or see all my photos from immich app. 
I am sure that worked fine about month ago when photos synced for the first time.

Android app version 1.124.2 - shows only 13 photos in camera folder.
After I made one more photo it shows 14 now. Looks like some time limit or something. 

Problem: I have many more photos in the camera and DCIM folders, which are visible with every other app.
google pixel 6, android 15
