### ISSUE TITLE
Uploading from mobile does not actually upload 

### ISSUE THREAD

**Issue by mce0** [immich-app/immich#14015]
### The bug

When uploading photos from the mobile app they are not actually uploaded. Uploading from the Web does work and the images are also shown in the mobile app.

### The OS that Immich Server is running on

Fedora 41 - Docker

### Version of Immich Server

v1.120.1

### Version of Immich Mobile App

v1.120.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich_server
    restart: unless-stopped
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    ports:
      - "127.0.0.1:2283:2283"
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false
    user: 1001:1001
    read_only: true
    tmpfs:
        - /tmp:size=10M,mode=0770,uid=1001,gid=1001,noexec,nosuid,nodev
    security_opt:
        - "no-new-privileges=true"
    cap_drop:
        - ALL
    #cap_add:
    #  - CHOWN
    #  - DAC_READ_SEARCH
    #  - SETUID
    #  - SETGID


  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich_machine_learning
    restart: unless-stopped
    extends:
      file: hwaccel.ml.yml
      service: openvino
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    healthcheck:
      disable: false
    #user: 1001:1001
    #read_only: true
    #tmpfs:
    #    - /tmp:size=10M,mode=0770,uid=1001,gid=1001,noexec,nosuid,nodev
    security_opt:
        - "no-new-privileges=true"
    cap_drop:
        - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - SETUID
      - SETGID

  redis:
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    container_name: immich_redis
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    #user: "991:991"
    #read_only: true
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL
    #cap_add:
    #  - CHOWN
    #  - DAC_READ_SEARCH
    #  - SETUID
    #  - SETGID

  database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    container_name: immich_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    user: "70:70"
    read_only: true
    tmpfs:
      - /var/run/postgresql:size=50M,mode=0770,uid=70,gid=70,noexec,nosuid,nodev
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
        - ALL

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/library
# The location where your database files are stored
DB_DATA_LOCATION=./data/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.120.1

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=[REDACTED]

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Open the App and upload an photo
2. Notification appears that indicates an successful upload
3. Check Web Page on another device and see that the Image was not uploaded

### Relevant log output

```shell
Message:
PlatformDispatcher - Catch all

Details:
PlatformException(error, Missing type parameter., null, java.lang.RuntimeException: Missing type parameter.
at S3.a.e(Unknown Source:26)
at S3.a.(SourceFile:2)
at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin$a.(Unknown Source:0)
at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.loadScheduledNotifications(Unknown Source:25)
at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.removeNotificationFromCache(Unknown Source:0)
at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.cancelNotification(Unknown Source:53)
at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.cancel(Unknown Source:22)
at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(Unknown Source:425)
at O4.j$a.a(Unknown Source:17)
at F4.c.l(Unknown Source:18)
at F4.c.m(Unknown Source:41)
at F4.c.i(Unknown Source:0)
at [F4.b.run](http://f4.b.run/)(Unknown Source:12)
at android.os.Handler.handleCallback([Handler.java:959](http://handler.java:959/))
at android.os.Handler.dispatchMessage([Handler.java:100](http://handler.java:100/))
at android.os.Looper.loopOnce([Looper.java:232](http://looper.java:232/))
at android.os.Looper.loop([Looper.java:317](http://looper.java:317/))
at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:8744](http://activitythread.java:8744/))
at java.lang.reflect.Method.invoke(Native Method)
at [com.android](http://com.android/).internal.os.RuntimeInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)([RuntimeInit.java:580](http://runtimeinit.java:580/))
at [com.android](http://com.android/).internal.os.ExecInit.main([ExecInit.java:50](http://execinit.java:50/))
at [com.android](http://com.android/).internal.os.RuntimeInit.nativeFinishInit(Native Method)
at [com.android](http://com.android/).internal.os.RuntimeInit.main([RuntimeInit.java:369](http://runtimeinit.java:369/))
)

From:
ImmichErrorLogger

Stack trace:
#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)

#2 FlutterLocalNotificationsPlugin.cancel (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:277)

#3 ManualUploadNotifier._startUpload (package:immich_mobile/providers/backup/manual_upload.provider.dart:325)
```

**Comment by Bigpet** [comment]
Had a similar issue. I get the same flutter error, and got shown no notification.

No upload happened. Then I fixed my nginx reverse proxy settings, that now fixes the upload, however I still get shown no notification and the same error gets written into the log.

**Comment by alextran1502** [comment]
@mce0 What is your phone model? Does running upload from the backup page work?

**Comment by alextran1502** [comment]
I am pretty sure this could be GraphineOS internal API issue 🧐

**Comment by Bigpet** [comment]
> > Had a similar issue. I get the same flutter error, and got shown no notification.
> > No upload happened. Then I fixed my nginx reverse proxy settings, that now fixes the upload, however I still get shown no notification and the same error gets written into the log.
> 
> @Bigpet what did you change in your nginx config? I am using nginx as well.

I just added all the settings I was missing from https://immich.app/docs/administration/reverse-proxy/#nginx-example-config (namely timeout, max size and websocket support)



> I am pretty sure this could be GraphineOS internal API issue 🧐

I doubt it. I'm on OneUI 6.1 (Android 14). Talking about the flutter error regarding the missing notifications, not the upload error.

**Comment by Bigpet** [comment]
Looking at some of the related code, it seems that it might be an issue when it's decoding the json for the notification here: https://github.com/MaikuB/flutter_local_notifications/blame/master/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L507-L509C58

Possibly stemming from some wrong or unknown property when creating the notification here:

https://github.com/immich-app/immich/blob/edce096680bc3d529b2a467fed3fbe90c3f0f26b/mobile/lib/services/local_notification.service.dart#L86-L115

But it's been a while since I did Android development and never touched Dart, so that's mostly a guess.

**Comment by alextran1502** [comment]
@Bigpet Can you help me with the steps/configuration of the app to reproduce this issue?

**Comment by Bigpet** [comment]
> @Bigpet Can you help me with the steps/configuration of the app to reproduce this issue?

I don't know what the additional step is. For me it reliably gets written into the log every time I manually upload a local image. Regardless of whether the upload fails or succeeds.
