### ISSUE TITLE
 Code: 'ERR_INVALID_URL' for every version from 1.116 up until latest 1.120.2

### ISSUE THREAD

**Issue by DuckersMcQuack** [immich-app/immich#14181]
### The bug

Every version from 1.116 till 1.120.2 breaks this way, and all versions between 1.105.1 being the version i installed when i got the docker and the semi functional 1.110.0 can't read raw image data at all upon clicking.

Is it breaking because images and facial recognition was done with cuda that it fails the way it does?
And is there a way to redo image scan without facial recognition while keeping image location and albums/album information?

```
[Nest] 708  - 11/17/2024, 2:49:09 AM     LOG [Api:EventRepository] Initialized websocket server
[Nest] 708  - 11/17/2024, 2:49:10 AM   ERROR [Api:An instance of SystemConfigDto has failed the validation:
 - property server.externalDomain has failed the following constraints: isUrl 
] Validation error
TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at buildConfig (/app/immich/server/dist/utils/config.js:118:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/utils/config.js:53:26 {
  code: 'ERR_INVALID_URL',
  input: 'personaldomain.com'
}
api worker exited with code 1
Starting api worker
```
this error loops on startup on latest update.

### The OS that Immich Server is running on

Unraid 6.12.11

### Version of Immich Server

1.105.1 - 1.120.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Don't know. Installed via unraid apps.
```

### Your .env content

```Shell
ghcr.io/imagegenius/immich:1.105.1-1.110.0 and 1.110.0 to latest 1.120.2

Don't know what else to input here.
```

### Reproduction steps

1. install 1.105.1 with nvidia cuda for machine learning facial recognition, and start scanning images
2.Install latest version, see it bootlooping with 1.120.2, downgrade to 1.110.0, it can now see images in albums, but clicking on images will throw errors.

**Comment by alextran1502** [comment]
From the working version of 1.110 or 1.115, go to Administration > Settings > External Url and make sure the content has either http:// or https://
