### ISSUE TITLE
Error with after Update to v1.121.0

### ISSUE THREAD

**Issue by jmerifjKriwe** [immich-app/immich#14295]
### The bug

Docker container is currently not able to start.
Seems to miss something with public.earth

(Worked without issue before the update)

### The OS that Immich Server is running on

Docker (on Unraid)

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

none

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
docker run
  -d
  --name='immich'
  --net='br0'
  --ip='192.168.50.56'
  --pids-limit 2048
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="tower"
  -e HOST_CONTAINERNAME="immich"
  -e 'TCP_PORT_8080'='8080'
  -e 'DB_HOSTNAME'='192.168.50.8'
  -e 'DB_USERNAME'='immich'
  -e 'DB_PASSWORD'=':[replaced]'
  -e 'DB_DATABASE_NAME'='immich'
  -e 'REDIS_HOSTNAME'='192.168.50.11'
  -e 'DISABLE_MACHINE_LEARNING'='false'
  -e 'DISABLE_TYPESENSE'='true'
  -e 'DB_PORT'='5432'
  -e 'REDIS_PORT'='6379'
  -e 'REDIS_PASSWORD'='kfiMTKu873dE'
  -e 'MACHINE_LEARNING_WORKERS'='1'
  -e 'MACHINE_LEARNING_WORKER_TIMEOUT'='120'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png'
  -v '/mnt/user/photos_neu':'/photos':'rw'
  -v '/mnt/user/appdata/immich/config/machine-learning':'/config/machine-learning':'rw'
  -v '/mnt/user/appdata/immich/import':'/import':'ro'
  -v '/mnt/user/photos':'/mnt/manual_import_photos':'rw'
  -v '/mnt/user/appdata/immich':'/config':'rw' 'ghcr.io/imagegenius/immich'
```

### Your .env content

```Shell
.
```

### Reproduction steps

1. just updated Docker file to v1.121.0
2.
3.
...

### Relevant log output

```shell
[custom-init] No custom files found, skipping...
Starting api worker
[Nest] 211  - 11/22/2024, 10:10:34 AM     LOG [Api:EventRepository] Initialized websocket server
Migration "NaturalEarthCountriesIdentityColumn1732072134943" failed, error: type "public.earth" does not exist
Starting api worker
[Nest] 240  - 11/22/2024, 10:10:39 AM     LOG [Api:EventRepository] Initialized websocket server
Migration "NaturalEarthCountriesIdentityColumn1732072134943" failed, error: type "public.earth" does not exist
QueryFailedError: type "public.earth" does not exist
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NaturalEarthCountriesIdentityColumn1732072134943.up (/app/immich/server/dist/migrations/1732072134943-NaturalEarthCountriesIdentityColumn.js:9:9)
    at async MigrationExecutor.executePendingMigrations (/app/immich/server/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/app/immich/server/dist/repositories/database.repository.js:189:9)
    at async /app/immich/server/dist/services/database.service.js:96:17
    at async /app/immich/server/dist/repositories/database.repository.js:197:23 {
  query: '\n' +
    '      CREATE FUNCTION ll_to_earth_public(latitude double precision, longitude double precision) RETURNS public.earth PARALLEL SAFE IMMUTABLE STRICT LANGUAGE SQL AS $$\n' +
    '        SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(latitude))*cos(radians(longitude))),public.earth()*cos(radians(latitude))*sin(radians(longitude))),public.earth()*sin(radians(latitude)))::public.earth\n' +
    '    $$',
  parameters: undefined,
  driverError: error: type "public.earth" does not exist
      at /app/immich/server/node_modules/pg/lib/client.js:535:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async NaturalEarthCountriesIdentityColumn1732072134943.up (/app/immich/server/dist/migrations/1732072134943-NaturalEarthCountriesIdentityColumn.js:9:9)
      at async MigrationExecutor.executePendingMigrations (/app/immich/server/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
      at async DataSource.runMigrations (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:265:35)
      at async DatabaseRepository.runMigrations (/app/immich/server/dist/repositories/database.repository.js:189:9)
      at async /app/immich/server/dist/services/database.service.js:96:17
      at async /app/immich/server/dist/repositories/database.repository.js:197:23 {
    length: 104,
    severity: 'ERROR',
    code: '42704',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'functioncmds.c',
    line: '136',
    routine: 'compute_return_type'
  },
  length: 104,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'functioncmds.c',
  line: '136',
  routine: 'compute_return_type'
}
api worker exited with code 1
```

**Comment by a1k0z** [comment]
I have the same error

**Comment by bo0tzz** [comment]
See #14270
