### ISSUE TITLE
Cannot download backed up files to iOS phone

### ISSUE THREAD

**Issue by ertugrullKara** [immich-app/immich#14510]
### The bug

We've been using Immich for a long time now. However, recently when we went back to old videos on iOS phones (in the app), it looks like we cannot download the videos. I've checked the logs and I am not exactly sure what the issue is. On Android and Web, there seems to be no issue.

This looks to be a decoding issue, though I am not sure how/why. Because when I remove transcoding, ios cannot play these videos in the app.

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.122.0

### Version of Immich Mobile App

v1.121.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I am running a single docker instance with https://github.com/imagegenius/docker-immich
```

### Your .env content

```Shell
Nothing extraordinary other than https://github.com/imagegenius/docker-immich
```

### Reproduction steps

1. Go to a video
2. Click on the cloud download icon on top
3. Pop up says download completed.
4. Video is not downloaded.

### Relevant log output

```shell
MESSAGE
Error saving video

DETAILS
PlatformException(PHPhotosErrorDomain (3302), The operation couldn't be completed. (PHPhotosErrorDomain error 3302.), No failure reason provided, null)

FROM
DownloadService

STACK TRACE
#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>
#2 PhotoManagerPlugin.saveVideo (package:photo_manager/src/internal/plugin.dart:416)
<asynchronous suspension>
#3 FileMediaRepository.saveVideo (package:immich_mobile/repositories/file_media.repository.dart:62)
<asynchronous suspension> 
#4 DownloadService.saveVideo (package:immich_mobile/services/download.service.dart:87
<asynchronous suspension>
```

**Comment by alextran1502** [comment]
Can you share the video you try to download?

**Comment by ertugrullKara** [comment]
I've been digging into this I've found that the problematic videos are encoded vp09 which is weird but may be the remnants of Google photos migration. Did other people experienced similar issues about this? Is there a migration job that I can/should run?

**Comment by pawelptak** [comment]
Same problem here. Cannot download or share vp9 videos from the mobile app. Only playback in the app works fine

**Comment by joonon** [comment]
I'm experiencing this issue with several fresh installs, currently trying v1.138.1

I'm using Immich-Go and a google takeout file that is otherwise importing fine but on iOS the videos will not play and will not download. If I take the original h264 mp4 video before it was uploaded to google photos and copy that into Immich, it will play on mobile just fine.

**Comment by SummitLabDev** [comment]
Just found out I have the exact same issue. It's not about file size, pictures are just fine, it seems to be specifically MP4's migrated from Google Photos. Similar/same log in iPhone app:

<img width="400" height="700" alt="Image" src="https://github.com/user-attachments/assets/5f1e2a23-8787-4f72-809e-bb1284c2c19c" />

**Comment by jfroy525** [comment]
> Just found out I have the exact same issue. It's not about file size, pictures are just fine, it seems to be specifically MP4's migrated from Google Photos. Similar/same log in iPhone app:
> 
> ![Image](https://github.com/user-attachments/assets/d47525e4-903c-4497-9ab0-55355a5046a7)

Yeah... this is a major issue and needs to be looked at by the team...

**Comment by mpu3000** [comment]
I have the same issue with the same log in the app.

<img width="1179" height="2556" alt="Image" src="https://github.com/user-attachments/assets/7a945996-4639-49e9-93ad-e693916d11c8" />

**Comment by pretubedongit** [comment]
same issue here. The error message is the same.

**Comment by imreverse** [comment]
Faced the same issue on iOS, with the same logs. Jotting down what I found along the way.

Error logs - 
```
Error saving video

PlatformException(PHPhotosErrorDomain (3302), The operation couldn’t be completed. (PHPhotosErrorDomain error 3302.), No failure reason provided, null)

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:366)
<asynchronous suspension>
#2      PhotoManagerPlugin.saveVideo (package:photo_manager/src/internal/plugin.dart:487)
<asynchronous suspension>
#3      FileMediaRepository.saveVideo (package:immich_mobile/repositories/file_media.repository.dart:38)
<asynchronous suspension>
#4      DownloadService._saveVideo (package:immich_mobile/services/download.service.dart:98)
<asynchronous suspension>

```

The video in question for me was recorded on my Pixel 10 Pro, with the following metadata -
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'PXL_20260816_205105049.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 131072
    compatible_brands: isomiso2mp41
    creation_time   : 2026-08-16T20:52:58.000000Z
    location        : +XXX/
    location-eng    : +XXX/
    com.android.capture.fps: 30.000000
    com.android.model: Pixel 10 Pro
    com.android.manufacturer: Google
  Duration: 00:01:50.50, start: 0.000000, bitrate: 38889 kb/s
  Stream #0:0[0x1](eng): Video: av1 (libdav1d) (Main) (av01 / 0x31307661), yuv420p10le(tv, bt2020nc/bt2020/arib-std-b67), 3840x2160 [SAR 1:1 DAR 16:9], 38624 kb/s, 29.91 fps, 30 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2026-08-16T20:52:58.000000Z
      handler_name    : VideoHandle
    Side data:
      Display Matrix: rotation of -90.00 degrees
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 191 kb/s, start 0.008396 (default)
    Metadata:
      creation_time   : 2026-08-16T20:52:58.000000Z
      handler_name    : SoundHandle
  Stream #0:2[0x3](eng): Data: none (mett / 0x7474656D), 55 kb/s (default)
    Metadata:
      creation_time   : 2026-08-16T20:52:58.000000Z
      handler_name    : MetaHandle
Unsupported codec with id 0 for input stream 2
```
The video is encoded in AV1. From what I found online on couple discussion threads was that, iPhone supports only a few specific formats, which doesn't include AV1 and VP9 (as other people on this thread faced it) - https://discussions.apple.com/thread/256212244, https://discussions.apple.com/thread/253798205.

A workaround is to save it to Files instead of Photos, and use any other app like VLC to play it, but this isn't fun. IIUC, some changes needs to be done in properly handling failed downloads (like informing user the download failed, instead of just logging the error). Not sure, what can be done for long term solution (I guess encoding into a supported format before saving to iOS's photos?).

I might be wrong in my deduction, so feel free to correct me.
