### ISSUE TITLE
Immich Server "Failed to fetch GitHub release" every hour

### ISSUE THREAD

**Issue by jt3204** [immich-app/immich#14801]
### The bug

I see Immich is trying to determine if it is up to date (I think) every hour. However the logs are saying this is failing with the following message.

```
2024-12-19 13:47:57 immich_server            | [Nest] 6  - 12/19/2024, 1:47:57 PM    WARN [Microservices:Error: Failed to fetch GitHub release: TypeError: fetch failed
2024-12-19 13:47:57 immich_server            |     at ServerInfoRepository.getGitHubRelease (/usr/src/app/dist/repositories/server-info.repository.js:63:19)
2024-12-19 13:47:57 immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2024-12-19 13:47:57 immich_server            |     at async VersionService.handleVersionCheck (/usr/src/app/dist/services/version.service.js:94:77)
2024-12-19 13:47:57 immich_server            |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
2024-12-19 13:47:57 immich_server            |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:134:13)
2024-12-19 13:47:57 immich_server            |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
2024-12-19 13:47:57 immich_server            |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)] Unable to run version check: Error: Failed to fetch GitHub release: TypeError: fetch failed
```

What is strange though is that I do still get the "new version available" popup (at least for the past two updates).

### The OS that Immich Server is running on

Docker Desktop for Windows

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Will supply if requested. Essentially the default.
```

### Your .env content

```Shell
Will supply if requested. Essentially the default.
```

### Reproduction steps

1. Start immich_server
2. Wait up to 1 hour
3. View logs

### Relevant log output

```shell
2024-12-19 13:47:57 immich_server            | [Nest] 6  - 12/19/2024, 1:47:57 PM    WARN [Microservices:Error: Failed to fetch GitHub release: TypeError: fetch failed
2024-12-19 13:47:57 immich_server            |     at ServerInfoRepository.getGitHubRelease (/usr/src/app/dist/repositories/server-info.repository.js:63:19)
2024-12-19 13:47:57 immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2024-12-19 13:47:57 immich_server            |     at async VersionService.handleVersionCheck (/usr/src/app/dist/services/version.service.js:94:77)
2024-12-19 13:47:57 immich_server            |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
2024-12-19 13:47:57 immich_server            |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:134:13)
2024-12-19 13:47:57 immich_server            |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
2024-12-19 13:47:57 immich_server            |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)] Unable to run version check: Error: Failed to fetch GitHub release: TypeError: fetch failed
```

**Comment by mmomjian** [comment]
Please enter the container shell and run `curl https://github.com`

The template does request the compose and env. Please include them

**Comment by jt3204** [comment]
Output: https://pastebin.com/qSWyjTvv
Compose: https://pastebin.com/QyvSvQZT
ENV: https://pastebin.com/sNpn2G4n

**Comment by mmomjian** [comment]
Can you show how the curl command was run inside the container?

**Comment by jt3204** [comment]
Interesting. I re-ran the command and got the output you were probably initially expecting, then ran it once more a minute later with the original result.
![Screenshot 2024-12-19 at 18 03 20](https://github.com/user-attachments/assets/274fb1a0-9603-409f-96c0-109fb7d3d489)

**Comment by mmomjian** [comment]
Yes, that makes sense. I would recommend to do some work and debugging on your network as to why these are failing as Immich has no control on this. Thanks
