### ISSUE TITLE
App Severely Reduced Function With Very Large Library 1.123.0+

### ISSUE THREAD

**Issue by TransRapid** [immich-app/immich#14841]
### The bug

App does not work at all aside from background backup. Constantly freezes up on launch if it opens. Cache has been cleared. App deleted, phone rebooted, then installed again. This issue started with this version. 

Albums also fail to populate from the server.  Timeline loads, but scroll causes freeze and then black screen. 

Search causes instant freeze and then everything disappears and goes black. Server works perfectly fine, web app on the same device fine as well. Issue seems to be with this release.

### The OS that Immich Server is running on

Android 14 November 2024 Security Update

### Version of Immich Server

v1. 123.0

### Version of Immich Mobile App

v1. 123.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

1. Open App
2. Tap or scroll.
3.
...

### Additional information

Issue started with v 1.123.0
Sony Xperia Mark 1 V
Over 68% available space free. 
Unrestricted power usage. Occurs locally and over WAN.

Seems that on airplane mode the app doesn't freeze. Otherwise it is useless at this point. 3TB library. Forgot to include that. 

Excessive battery drain as well. Full permissions for the app. Nothing withheld. No error logs.

**Comment by alextran1502** [comment]
Can you try using the APK from this release to see if you are experiencing the same issue? https://github.com/immich-app/immich/releases/tag/v1.122.3

**Comment by alextran1502** [comment]
Please help me do this. When you open the app, can you wait until the spinning icon at the bottom app bar stops spinning before using any action? I would class this issue as optimization issue for large library

**Comment by TransRapid** [comment]
This seems to be a thing where the app doesn't function until my entire library is cached. That is pretty unrealistic. Hopefully that gets fixed as it eats a ton of battery doing this.

Outside of the issue, timeline and library loading is one area that needs a lot of work as far as the app goes. Even when the app works, the timeline takes way too long to load. It is always considerably slower than other hosted solutions as far as the app goes, and destroys the battery. Loading the web version on the same device is always faster to the point I only use the app for backup and use the web version for everything else.

**Comment by TransRapid** [comment]
> Can you try using the APK from this release to see if you are experiencing the same issue? https://github.com/immich-app/immich/releases/tag/v1.122.3
> 
> 


Instant fix. Albums still refreshing, but refreshing not freezing.

I can check sever logs and try doing the same to compare differences. Didn't have errors when I looked though. No app errors either.

**Comment by alextran1502** [comment]
I find it very strange that the APK works but the latest version doesn't I believe we did not changing anything that could have affected what you observed 🤔

**Comment by alextran1502** [comment]
If you don't mind, please try to use the APK in the latest release and see if it makes a different https://github.com/immich-app/immich/releases/tag/v1.123.0

**Comment by TransRapid** [comment]
> Please help me do this. When you open the app, can you wait until the spinning icon at the bottom app bar stops spinning before using any action? I would class this issue as an optimization issue for a large library.
> 
> Please also try to use the local IP


I did try just waiting for it to stop spinning and it still freezes after a moment, then becomes unresponsive, goes black, and I can't gracefully exit.

I didn't try the local IP. and actually, but it does the same behavior locally on the same network when using FQDN with loopback/local.

I thought the same too. I left it plugged in, and on Wi-Fi overnight and during the day and it still crashed. I can try to reproduce with a smaller test library.


By optimization do you mean within PSQL? I actually forgot about that and might need to take a look at those settings, but what is weird is the web app runs it perfectly fine.

**Comment by alextran1502** [comment]
Optimize of how the sync mechanism works on the mobile app. The web app and the mobile app use different rendering and data sourcing techniques since the mobile app also supports offline mode, so it has its own database. So that there is an overhead in keeping the data synchronized between the server and mobile databases. 

We have a plan that will improve it, though, which we want to start work on after some other PRs merge. 

However, the current issue is that it works fine on the previous version, not on the latest one.

**Comment by TransRapid** [comment]
Looking forward to those changes, obviously these are the sorts of things you run into as software is under very active development, but overall stability has been pretty good. Tradeoffs are more positive than not, hence I was willing to work around, because ultimately there are far fewer limitations with this, and I'm not wondering where or who has my data, and at their mercy. It was a bit unexpected to have that non functional app to where I couldn't even go into setting menu.

More surprising is how much faster that works though, and the noticeable difference in phone temperature as well as battery. I can duplicate the 1.123.0 release to have a secondary install and test different versions with a smaller test library and see how that does. 

Going to keep this 1.123.3 APK you linked installed for now, but I can also install any number of alternate versions concurrently with no impact to each other.

Let me know what you might want to get a better picture.

If you want library specifics I can get those too and put in the original report. Forgot to do that initially.

I'm not sure if it's item count or size, but I imagine count is more problematic.

**Comment by TransRapid** [comment]
Looking forward to those changes, obviously these are the sorts of things you run into as software is under very active development, but overall stability has been pretty good. Tradeoffs are more positive than not, hence I was willing to work around, because ultimately there are far fewer limitations with this, and I'm not wondering where or who has my data, and at their mercy. It was a bit unexpected to have that non functional app to where I couldn't even go into setting menu.

More surprising is how much faster that works though, and the noticeable difference in phone temperature as well as battery. I can duplicate the 1.123.0 release to have a secondary install and test different versions with a smaller test library and see how that does. 

Going to keep this 1.123.3 APK you linked installed for now, but I can also install any number of alternate versions concurrently with no impact to each other.

Let me know what you might want to get a better picture.

If you want library specifics I can get those too and put in the original report. Forgot to do that initially.

I'm not sure if it's item count or size, but I imagine count is more problematic.


**Update**

Albums all populated as intended on the 122.3 APK. 123.0 that is installed concurrently remains the same. I forgot I can't text via IP because of firewall rules I have setup, but my router can locally resolve my DNS without leaving my network.

**Comment by TransRapid** [comment]
Having this issue in the latest release. I have held back since, but thought maybe some improvements had been made. 

What suggestions do you have for this? The app is non-functional again. Not sure if the backup even works as things freeze immediately.

**Comment by alextran1502** [comment]
Can you describe non functional behavior? We haven't changed anything regarding the synchronization mechanism

**Comment by TransRapid** [comment]
It is the same as before. I can't scroll. Can't view albums. The app freezes and then the screen goes black if I go to another app and try to come back. It is a bit hard on the battery too. I can't tap anything or use the app for anything. I have tried leaving it plugged in for power and letting it load and it is unable to do anything.

I'm not sure what to do at this point other than use a much older version of the app.

**Comment by alextran1502** [comment]
That is strange, have you been using the playstore version prior to updating? 

Can you remind me how many assets do you have on your local device and on Immich?

**Comment by TransRapid** [comment]
I have probably around 150k assets. That's the first issue. That's not on your end. I am on the extreme side of media collection here, but this is going back 30 years as I also have prints and negatives scanned in.

I just tried something now and it seems to have helped. When the screen went black I switched back to it and just left it. It seems that when it does that it's not frozen as much as it has nothing to display as it is refreshing. I left it there for a few minutes and I can scroll again, and very fast too. If or when it does it again, and hopefully it doesn't I will try to capture logs.

Also, I have been on the GitHub track for almost the entire time. If all else fails the web version works, but if the backup doesn't work that's the issue.

**Comment by TransRapid** [comment]
```
PlatformDispatcher - Catch all
```

```
Bad state: Unable to fetch properties for path -1106254366.
```

```
#0      AssetPathEntity.obtainPathFromProperties (package:photo_manager/src/types/entity.dart:162)
<asynchronous suspension>
#1      AssetPathEntity.fromId (package:photo_manager/src/types/entity.dart:59)
<asynchronous suspension>
#2      AlbumMediaRepository.getAssets (package:immich_mobile/repositories/album_media.repository.dart:44)
<asynchronous suspension>
#3      HashService.getHashedAssets (package:immich_mobile/services/hash.service.dart:38)
<asynchronous suspension>
#4      SyncService._syncDeviceAlbumFast (package:immich_mobile/services/sync.service.dart:656)
<asynchronous suspension>
#5      SyncService._syncAlbumInDbAndOnDevice (package:immich_mobile/services/sync.service.dart:563)
<asynchronous suspension>
#6      diffSortedLists (package:immich_mobile/utils/diff.dart:23)
<asynchronous suspension>
#7      SyncService._syncLocalAlbumAssetsToDb (package:immich_mobile/services/sync.service.dart:510)
<asynchronous suspension>
#8      AlbumService.refreshDeviceAlbums (package:immich_mobile/services/album.service.dart:132)
<asynchronous suspension>
#9      AssetNotifier.getAllAsset (package:immich_mobile/providers/asset.provider.dart:56)
<asynchronous suspension>
#10     AppLifeCycleNotifier.handleAppResume (package:immich_mobile/providers/app_life_cycle.provider.dart:67)
<asynchronous suspension>

```

![Screenshot_20250113-163100.png](https://github.com/user-attachments/assets/5fd8799d-54b4-4f09-992e-bec0207269c1)

**Comment by alextran1502** [comment]
Hmm looks like some files are deleted off the phone but the app is still trying to access. Do you mind logout and log back in?

**Comment by TransRapid** [comment]
> Hmm looks like some files are deleted off the phone but the app is still trying to access. Do you mind logout and log back in?

Going to try this in a little bit here.

**Comment by TransRapid** [comment]
```
PlatformDispatcher - Catch all
```

```
Bad state: Unable to fetch properties for path -1679170491.
```

```
#0      AssetPathEntity.obtainPathFromProperties (package:photo_manager/src/types/entity.dart:162)
<asynchronous suspension>
#1      AssetPathEntity.fromId (package:photo_manager/src/types/entity.dart:59)
<asynchronous suspension>
#2      AlbumMediaRepository.getAssets (package:immich_mobile/repositories/album_media.repository.dart:44)
<asynchronous suspension>
#3      HashService.getHashedAssets (package:immich_mobile/services/hash.service.dart:38)
<asynchronous suspension>
#4      SyncService._syncDeviceAlbumFast (package:immich_mobile/services/sync.service.dart:656)
<asynchronous suspension>
#5      SyncService._syncAlbumInDbAndOnDevice (package:immich_mobile/services/sync.service.dart:563)
<asynchronous suspension>
#6      diffSortedLists (package:immich_mobile/utils/diff.dart:23)
<asynchronous suspension>
#7      SyncService._syncLocalAlbumAssetsToDb (package:immich_mobile/services/sync.service.dart:510)
<asynchronous suspension>
#8      AlbumService.refreshDeviceAlbums (package:immich_mobile/services/album.service.dart:132)
<asynchronous suspension>
#9      AssetNotifier.getAllAsset (package:immich_mobile/providers/asset.provider.dart:56)
<asynchronous suspension>

```

**Comment by TransRapid** [comment]
Issue seems to be documented by others here as well. Thought this was a different issue, but it now seems the same as https://github.com/immich-app/immich/issues/12674.

@alextran1502 
I am going to close this as duplicate on my end.
