### ISSUE TITLE
[BUG] microservice panic 

### ISSUE THREAD

**Issue by kosmgco** [immich-app/immich#2243]
### The bug

microservices container always restart

### The OS that Immich Server is running on

Ubuntu 20.04.6 LTS(GNU/Linux 5.4.0-139-generic x86_64)

### Version of Immich Server

v1.53.0

### Version of Immich Mobile App

v1.5.0 build.73

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Same with doc
```

### Your .env content

```Shell
Same with doc, only change path
```

### Reproduction steps

```bash
Upload some asset, and run the jobs automaticly
```

### Additional information

The container log:

```
[Nest] 1  - 04/13/2023, 3:21:09 AM     LOG [NestFactory] Starting Nest application...
[Nest] 1  - 04/13/2023, 3:21:09 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +305ms
[Nest] 1  - 04/13/2023, 3:21:09 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 1  - 04/13/2023, 3:21:09 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +4ms
[Nest] 1  - 04/13/2023, 3:21:09 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +2ms
[Nest] 1  - 04/13/2023, 3:21:09 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +33ms
[Nest] 1  - 04/13/2023, 3:21:09 AM     LOG [InstanceLoader] BullModule dependencies initialized +2ms
[Nest] 1  - 04/13/2023, 3:21:09 AM     LOG [InstanceLoader] BullModule dependencies initialized +2ms
[Nest] 1  - 04/13/2023, 3:21:10 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +801ms
[Nest] 1  - 04/13/2023, 3:21:10 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +3ms
[Nest] 1  - 04/13/2023, 3:21:10 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 1  - 04/13/2023, 3:21:10 AM    WARN [MetadataExtractionProcessor] Reverse geocoding is enabled
[Nest] 1  - 04/13/2023, 3:21:10 AM     LOG [MetadataExtractionProcessor] Initializing Reverse Geocoding
/usr/src/app/node_modules/local-reverse-geocoder/index.js:746
            throw err;
            ^

CsvError: Invalid Record Length: expect 19, got 4 on line 488
    at Object.__onRecord (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:940:11)
    at Object.parse (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:903:36)
    at Parser._flush (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:1336:26)
    at Parser.final [as _final] (node:internal/streams/transform:112:25)
    at callFinal (node:internal/streams/writable:694:27)
    at prefinish (node:internal/streams/writable:723:7)
    at finishMaybe (node:internal/streams/writable:733:5)
    at afterWrite (node:internal/streams/writable:504:3)
    at onwrite (node:internal/streams/writable:477:7)
    at Parser.Transform._read (node:internal/streams/transform:245:5) {
  code: 'CSV_RECORD_INCONSISTENT_FIELDS_LENGTH',
  bytes: 114688,
  comment_lines: 0,
  empty_lines: 0,
  invalid_field_length: 0,
  lines: 488,
  records: 487,
  columns: false,
  error: undefined,
  header: false,
  index: 4,
  raw: undefined,
  column: 4,
  quoting: false,
  record: [
    '782843',
    'Këlcyrë',
    'Kelcyre',
    "Kel'cira,Kelcyra,Kelcyre,Kelcyres,Kelcyrës,Kleisoura,Klisura,Këlcyr"
  ]
}
```

**Comment by kosmgco** [comment]
Remove the image, and restart docker compose, it runs
