### ISSUE TITLE
[BUG] failed to convert video

### ISSUE THREAD

**Issue by alexlyee** [immich-app/immich#2271]
### The bug

Wondering if this is an expected issue?

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

latest

### Version of Immich Mobile App

latest

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
pretty much default
```

### Your .env content

```Shell
pretty much default
```

### Reproduction steps

```bash
1. turn on immich
2. connect, begin backup
```

### Additional information

```
immich_microservices     | [Nest] 1  - 04/18/2023, 3:29:54 AM   ERROR [MediaService] Failed to handle video conversion for asset: 5c43a8cc-5e38-41e4-b301-07503f94f4cb
immich_microservices     | Error: ffprobe exited with code 1
immich_microservices     | ffprobe version 4.4.1 Copyright (c) 2007-2021 the FFmpeg developers
immich_microservices     |   built with gcc 10.3.1 (Alpine 10.3.1_git20210424) 20210424
immich_microservices     |   configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --enable-vulkan --enable-libsoxr --enable-libwebp --enable-libaom --disable-debug
immich_microservices     |   libavutil      56. 70.100 / 56. 70.100
immich_microservices     |   libavcodec     58.134.100 / 58.134.100
immich_microservices     |   libavformat    58. 76.100 / 58. 76.100
immich_microservices     |   libavdevice    58. 13.100 / 58. 13.100
immich_microservices     |   libavfilter     7.110.100 /  7.110.100
immich_microservices     |   libavresample   4.  0.  0 /  4.  0.  0
immich_microservices     |   libswscale      5.  9.100 /  5.  9.100
immich_microservices     |   libswresample   3.  9.100 /  3.  9.100
immich_microservices     |   libpostproc    55.  9.100 / 55.  9.100
immich_microservices     | upload/upload/0efda8c8-3813-4d13-a139-c0f84fc80709/54166fa1-405d-45ef-80c9-d8d2e5c18c0c.mov: No such file or directory
immich_microservices     |
immich_microservices     |     at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
immich_microservices     |     at ChildProcess.emit (node:events:527:28)
immich_microservices     |     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by bo0tzz** [comment]
It can't find the file. Have you changed anything about the mounts, or manually played around in the upload folder?

**Comment by ddshd** [comment]
```
[Nest] 1  - 07/05/2023, 3:08:43 AM   ERROR [JobService] Error: ffprobe exited with code 1
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r10) 20220924
  configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gnutls --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   5.  0.100 /  5.  0.100
  libpostproc    57.  1.100 / 57.  1.100
upload/upload/9fdd6612-60dc-4e0f-af05-bb1f48b6ae5e/f5515de1-f86e-44b3-b649-2800b2694540.mov: No such file or directory

    at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
 ```
 
 This issue appeared again for me on the latest version...

**Comment by mertalev** [comment]
> ```
> [Nest] 1  - 07/05/2023, 3:08:43 AM   ERROR [JobService] Error: ffprobe exited with code 1
> ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
>   built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r10) 20220924
>   configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gnutls --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl
>   libavutil      58.  2.100 / 58.  2.100
>   libavcodec     60.  3.100 / 60.  3.100
>   libavformat    60.  3.100 / 60.  3.100
>   libavdevice    60.  1.100 / 60.  1.100
>   libavfilter     9.  3.100 /  9.  3.100
>   libswscale      7.  1.100 /  7.  1.100
>   libswresample   5.  0.100 /  5.  0.100
>   libpostproc    57.  1.100 / 57.  1.100
> upload/upload/9fdd6612-60dc-4e0f-af05-bb1f48b6ae5e/f5515de1-f86e-44b3-b649-2800b2694540.mov: No such file or directory
> 
>     at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
>     at ChildProcess.emit (node:events:513:28)
>     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
> ```
> 
> This issue appeared again for me on the latest version... I've checked, the file exists.

I believe this is fixed with #3071, so it should be in the next release.
