### ISSUE TITLE
[BUG] Map View crashes immich-web

### ISSUE THREAD

**Issue by peterkappelt** [immich-app/immich#2525]
### The bug

Hi, I've just upgraded to 1.57.0 and observed reproducible crashes of the immich-web container when opening the Map view in the browser. I didn't see that issue before upgrading to 1.57.0.

Crash log of immich-web: 
```
Listening on 0.0.0.0:3000
/usr/src/app/node_modules/leaflet/dist/leaflet-src.js:230
  var requestFn = window.requestAnimationFrame || getPrefixed('RequestAnimationFrame') || timeoutDefer;
                  ^

ReferenceError: window is not defined
    at /usr/src/app/node_modules/leaflet/dist/leaflet-src.js:230:19
    at /usr/src/app/node_modules/leaflet/dist/leaflet-src.js:7:66
    at Object.<anonymous> (/usr/src/app/node_modules/leaflet/dist/leaflet-src.js:10:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.16.0
```

Let me known if there are any more information I can provide

### The OS that Immich Server is running on

Debian Bullseye

### Version of Immich Server

1.57.0

### Version of Immich Mobile App

--

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
none (running in Kubernetes)
```

### Your .env content

```Shell
DB_DATABASE_NAME=immich
DB_HOSTNAME=...
DB_PASSWORD=...
DB_USERNAME=...
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_WEB_URL=http://immich-web:3000
REDIS_HOSTNAME=immich-redis-master
TYPESENSE_API_KEY=typesene
TYPESENSE_ENABLED=true
TYPESENSE_HOST=immich-typesense
```

### Reproduction steps

```bash
1. Upgrade to 1.57.0
2. Open `https://photos.youdomain.com/map`
3. immich-web will crash
```

**Comment by michelheusschen** [comment]
Confirmed, but only happens in production builds. Using the sidebar to navigate to the map should work without issues, only directly going to `/map` should have this error. I will open a PR soon that fixes this.

**Comment by peterkappelt** [comment]
That was incredibly fast, thanks guys!
