### ISSUE TITLE
[BUG] Error when deleting users with partner sharing

### ISSUE THREAD

**Issue by wittymap** [immich-app/immich#2691]
### The bug

Right now, if a user is deleted that has partner sharing enabled with others, those others cannot view the `/sharing` page without an error being thrown and being sent back to the login screen.

See details in reproduction instructions below.

### The OS that Immich Server is running on

Windows 10

### Version of Immich Server

v1.60.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Reproduction steps

1. While logged in as User-B, enable partner sharing with User-A (administrator).
2. While logged in as User-A (administrator),  delete User-B account from admin console.
3. While logged in as User-A, visit `/sharing`. Instead of seeing the sharing page, you're logged out and an error is thrown in the console.

### Additional information (Error Stack)
```
immich_server            | [Nest] 1  - 06/07/2023, 7:54:31 PM   ERROR [ExceptionsHandler] Cannot read properties of null (reading 'id')
immich_server            | TypeError: Cannot read properties of null (reading 'id')
immich_server            |     at mapUser (/usr/src/app/dist/apps/immich/libs/domain/src/user/response-dto/user-response.dto.js:13:20)
immich_server            |     at PartnerService.map (/usr/src/app/dist/apps/immich/libs/domain/src/partner/partner.service.js:45:35)
immich_server            |     at /usr/src/app/dist/apps/immich/libs/domain/src/partner/partner.service.js:42:47
immich_server            |     at Array.map (<anonymous>)
immich_server            |     at PartnerService.getAll (/usr/src/app/dist/apps/immich/libs/domain/src/partner/partner.service.js:42:25)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
immich_server            |     at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
immich_web               | [AxiosError: Request failed with status code 500] {
immich_web               |   code: 'ERR_BAD_RESPONSE',
immich_web               |   config: {
immich_web               |     transitional: {
immich_web               |       silentJSONParsing: true,
immich_web               |       forcedJSONParsing: true,
immich_web               |       clarifyTimeoutError: false
immich_web               |     },
immich_web               |     adapter: [Function: httpAdapter],
immich_web               |     transformRequest: [ [Function: transformRequest] ],
immich_web               |     transformResponse: [ [Function: transformResponse] ],
immich_web               |     timeout: 0,
immich_web               |     xsrfCookieName: 'XSRF-TOKEN',
immich_web               |     xsrfHeaderName: 'X-XSRF-TOKEN',
immich_web               |     maxContentLength: -1,
immich_web               |     maxBodyLength: -1,
immich_web               |     env: { FormData: [Function] },
immich_web               |     validateStatus: [Function: validateStatus],
immich_web               |     headers: {
immich_web               |       Accept: 'application/json, text/plain, */*',
immich_web               |       Authorization: 'Bearer <redacted>',
immich_web               |       'User-Agent': 'axios/0.27.2'
immich_web               |     },
immich_web               |     method: 'get',
immich_web               |     url: 'http://immich-server:3001/partner?direction=shared-with',
immich_web               |     data: undefined
immich_web               |   },
immich_web               |   request: <ref *1> ClientRequest {
immich_web               |     _events: [Object: null prototype] {
immich_web               |       abort: [Function (anonymous)],
immich_web               |       aborted: [Function (anonymous)],
immich_web               |       connect: [Function (anonymous)],
immich_web               |       error: [Function (anonymous)],
immich_web               |       socket: [Function (anonymous)],
immich_web               |       timeout: [Function (anonymous)],
immich_web               |       finish: [Function: requestOnFinish]
immich_web               |     },
immich_web               |     _eventsCount: 7,
immich_web               |     _maxListeners: undefined,
immich_web               |     outputData: [],
immich_web               |     outputSize: 0,
immich_web               |     writable: true,
immich_web               |     destroyed: false,
immich_web               |     _last: true,
immich_web               |     chunkedEncoding: false,
immich_web               |     shouldKeepAlive: false,
immich_web               |     maxRequestsOnConnectionReached: false,
immich_web               |     _defaultKeepAlive: true,
immich_web               |     useChunkedEncodingByDefault: false,
immich_web               |     sendDate: false,
immich_web               |     _removedConnection: false,
immich_web               |     _removedContLen: false,
immich_web               |     _removedTE: false,
immich_web               |     strictContentLength: false,
immich_web               |     _contentLength: 0,
immich_web               |     _hasBody: true,
immich_web               |     _trailer: '',
immich_web               |     finished: true,
immich_web               |     _headerSent: true,
immich_web               |     _closed: false,
immich_web               |     socket: Socket {
immich_web               |       connecting: false,
immich_web               |       _hadError: false,
immich_web               |       _parent: null,
immich_web               |       _host: 'immich-server',
immich_web               |       _closeAfterHandlingError: false,
immich_web               |       _readableState: [ReadableState],
immich_web               |       _events: [Object: null prototype],
immich_web               |       _eventsCount: 7,
immich_web               |       _maxListeners: undefined,
immich_web               |       _writableState: [WritableState],
immich_web               |       allowHalfOpen: false,
immich_web               |       _sockname: null,
immich_web               |       _pendingData: null,
immich_web               |       _pendingEncoding: '',
immich_web               |       server: null,
immich_web               |       _server: null,
immich_web               |       parser: null,
immich_web               |       _httpMessage: [Circular *1],
immich_web               |       [Symbol(async_id_symbol)]: 28847,
immich_web               |       [Symbol(kHandle)]: [TCP],
immich_web               |       [Symbol(lastWriteQueueSize)]: 0,
immich_web               |       [Symbol(timeout)]: null,
immich_web               |       [Symbol(kBuffer)]: null,
immich_web               |       [Symbol(kBufferCb)]: null,
immich_web               |       [Symbol(kBufferGen)]: null,
immich_web               |       [Symbol(kCapture)]: false,
immich_web               |       [Symbol(kSetNoDelay)]: true,
immich_web               |       [Symbol(kSetKeepAlive)]: true,
immich_web               |       [Symbol(kSetKeepAliveInitialDelay)]: 60,
immich_web               |       [Symbol(kBytesRead)]: 0,
immich_web               |       [Symbol(kBytesWritten)]: 0
immich_web               |     },
immich_web               |     _header: 'GET /partner?direction=shared-with HTTP/1.1\r\n' +
immich_web               |       'Accept: application/json, text/plain, */*\r\n' +
immich_web               |       'Authorization: Bearer <redacted>' +
immich_web               |       'User-Agent: axios/0.27.2\r\n' +
immich_web               |       'Host: immich-server:3001\r\n' +
immich_web               |       'Connection: close\r\n' +
immich_web               |       '\r\n',
immich_web               |     _keepAliveTimeout: 0,
immich_web               |     _onPendingData: [Function: nop],
immich_web               |     agent: Agent {
immich_web               |       _events: [Object: null prototype],
immich_web               |       _eventsCount: 2,
immich_web               |       _maxListeners: undefined,
immich_web               |       defaultPort: 80,
immich_web               |       protocol: 'http:',
immich_web               |       options: [Object: null prototype],
immich_web               |       requests: [Object: null prototype] {},
immich_web               |       sockets: [Object: null prototype],
immich_web               |       freeSockets: [Object: null prototype] {},
immich_web               |       keepAliveMsecs: 1000,
immich_web               |       keepAlive: false,
immich_web               |       maxSockets: Infinity,
immich_web               |       maxFreeSockets: 256,
immich_web               |       scheduling: 'lifo',
immich_web               |       maxTotalSockets: Infinity,
immich_web               |       totalSocketCount: 1,
immich_web               |       [Symbol(kCapture)]: false
immich_web               |     },
immich_web               |     socketPath: undefined,
immich_web               |     method: 'GET',
immich_web               |     maxHeaderSize: undefined,
immich_web               |     insecureHTTPParser: undefined,
immich_web               |     joinDuplicateHeaders: undefined,
immich_web               |     path: '/partner?direction=shared-with',
immich_web               |     _ended: true,
immich_web               |     res: IncomingMessage {
immich_web               |       _readableState: [ReadableState],
immich_web               |       _events: [Object: null prototype],
immich_web               |       _eventsCount: 4,
immich_web               |       _maxListeners: undefined,
immich_web               |       socket: [Socket],
immich_web               |       httpVersionMajor: 1,
immich_web               |       httpVersionMinor: 1,
immich_web               |       httpVersion: '1.1',
immich_web               |       complete: true,
immich_web               |       rawHeaders: [Array],
immich_web               |       rawTrailers: [],
immich_web               |       joinDuplicateHeaders: undefined,
immich_web               |       aborted: false,
immich_web               |       upgrade: false,
immich_web               |       url: '',
immich_web               |       method: null,
immich_web               |       statusCode: 500,
immich_web               |       statusMessage: 'Internal Server Error',
immich_web               |       client: [Socket],
immich_web               |       _consuming: false,
immich_web               |       _dumped: false,
immich_web               |       req: [Circular *1],
immich_web               |       responseUrl: 'http://immich-server:3001/partner?direction=shared-with',
immich_web               |       redirects: [],
immich_web               |       [Symbol(kCapture)]: false,
immich_web               |       [Symbol(kHeaders)]: [Object],
immich_web               |       [Symbol(kHeadersCount)]: 12,
immich_web               |       [Symbol(kTrailers)]: null,
immich_web               |       [Symbol(kTrailersCount)]: 0
immich_web               |     },
immich_web               |     aborted: false,
immich_web               |     timeoutCb: null,
immich_web               |     upgradeOrConnect: false,
immich_web               |     parser: null,
immich_web               |     maxHeadersCount: null,
immich_web               |     reusedSocket: false,
immich_web               |     host: 'immich-server',
immich_web               |     protocol: 'http:',
immich_web               |     _redirectable: Writable {
immich_web               |       _writableState: [WritableState],
immich_web               |       _events: [Object: null prototype],
immich_web               |       _eventsCount: 3,
immich_web               |       _maxListeners: undefined,
immich_web               |       _options: [Object],
immich_web               |       _ended: true,
immich_web               |       _ending: true,
immich_web               |       _redirectCount: 0,
immich_web               |       _redirects: [],
immich_web               |       _requestBodyLength: 0,
immich_web               |       _requestBodyBuffers: [],
immich_web               |       _onNativeResponse: [Function (anonymous)],
immich_web               |       _currentRequest: [Circular *1],
immich_web               |       _currentUrl: 'http://immich-server:3001/partner?direction=shared-with',
immich_web               |       [Symbol(kCapture)]: false
immich_web               |     },
immich_web               |     [Symbol(kCapture)]: false,
immich_web               |     [Symbol(kBytesWritten)]: 0,
immich_web               |     [Symbol(kNeedDrain)]: false,
immich_web               |     [Symbol(corked)]: 0,
immich_web               |     [Symbol(kOutHeaders)]: [Object: null prototype] {
immich_web               |       accept: [Array],
immich_web               |       authorization: [Array],
immich_web               |       'user-agent': [Array],
immich_web               |       host: [Array]
immich_web               |     },
immich_web               |     [Symbol(errored)]: null,
immich_web               |     [Symbol(kUniqueHeaders)]: null
immich_web               |   },
immich_web               |   response: {
immich_web               |     status: 500,
immich_web               |     statusText: 'Internal Server Error',
immich_web               |     headers: {
immich_web               |       'x-powered-by': 'Express',
immich_web               |       'content-type': 'application/json; charset=utf-8',
immich_web               |       'content-length': '52',
immich_web               |       etag: '<redacted>',
immich_web               |       date: 'Wed, 07 Jun 2023 19:54:31 GMT',
immich_web               |       connection: 'close'
immich_web               |     },
immich_web               |     config: {
immich_web               |       transitional: [Object],
immich_web               |       adapter: [Function: httpAdapter],
immich_web               |       transformRequest: [Array],
immich_web               |       transformResponse: [Array],
immich_web               |       timeout: 0,
immich_web               |       xsrfCookieName: 'XSRF-TOKEN',
immich_web               |       xsrfHeaderName: 'X-XSRF-TOKEN',
immich_web               |       maxContentLength: -1,
immich_web               |       maxBodyLength: -1,
immich_web               |       env: [Object],
immich_web               |       validateStatus: [Function: validateStatus],
immich_web               |       headers: [Object],
immich_web               |       method: 'get',
immich_web               |       url: 'http://immich-server:3001/partner?direction=shared-with',
immich_web               |       data: undefined
immich_web               |     },
immich_web               |     request: <ref *1> ClientRequest {
immich_web               |       _events: [Object: null prototype],
immich_web               |       _eventsCount: 7,
immich_web               |       _maxListeners: undefined,
immich_web               |       outputData: [],
immich_web               |       outputSize: 0,
immich_web               |       writable: true,
immich_web               |       destroyed: false,
immich_web               |       _last: true,
immich_web               |       chunkedEncoding: false,
immich_web               |       shouldKeepAlive: false,
immich_web               |       maxRequestsOnConnectionReached: false,
immich_web               |       _defaultKeepAlive: true,
immich_web               |       useChunkedEncodingByDefault: false,
immich_web               |       sendDate: false,
immich_web               |       _removedConnection: false,
immich_web               |       _removedContLen: false,
immich_web               |       _removedTE: false,
immich_web               |       strictContentLength: false,
immich_web               |       _contentLength: 0,
immich_web               |       _hasBody: true,
immich_web               |       _trailer: '',
immich_web               |       finished: true,
immich_web               |       _headerSent: true,
immich_web               |       _closed: false,
immich_web               |       socket: [Socket],
immich_web               |       _header: 'GET /partner?direction=shared-with HTTP/1.1\r\n' +
immich_web               |         'Accept: application/json, text/plain, */*\r\n' +
immich_web               |         'Authorization: Bearer <redacted>' +
immich_web               |         'User-Agent: axios/0.27.2\r\n' +
immich_web               |         'Host: immich-server:3001\r\n' +
immich_web               |         'Connection: close\r\n' +
immich_web               |         '\r\n',
immich_web               |       _keepAliveTimeout: 0,
immich_web               |       _onPendingData: [Function: nop],
immich_web               |       agent: [Agent],
immich_web               |       socketPath: undefined,
immich_web               |       method: 'GET',
immich_web               |       maxHeaderSize: undefined,
immich_web               |       insecureHTTPParser: undefined,
immich_web               |       joinDuplicateHeaders: undefined,
immich_web               |       path: '/partner?direction=shared-with',
immich_web               |       _ended: true,
immich_web               |       res: [IncomingMessage],
immich_web               |       aborted: false,
immich_web               |       timeoutCb: null,
immich_web               |       upgradeOrConnect: false,
immich_web               |       parser: null,
immich_web               |       maxHeadersCount: null,
immich_web               |       reusedSocket: false,
immich_web               |       host: 'immich-server',
immich_web               |       protocol: 'http:',
immich_web               |       _redirectable: [Writable],
immich_web               |       [Symbol(kCapture)]: false,
immich_web               |       [Symbol(kBytesWritten)]: 0,
immich_web               |       [Symbol(kNeedDrain)]: false,
immich_web               |       [Symbol(corked)]: 0,
immich_web               |       [Symbol(kOutHeaders)]: [Object: null prototype],
immich_web               |       [Symbol(errored)]: null,
immich_web               |       [Symbol(kUniqueHeaders)]: null
immich_web               |     },
immich_web               |     data: { statusCode: 500, message: 'Internal server error' }
immich_web               |   }
immich_web               | }
```
```[tasklist]
### Tasks
```

**Comment by alextran1502** [comment]
Thank you for the detail report, we will look into this.
