### ISSUE TITLE
[BUG] Something went awfully wrong uploading a large library using the CLI

### ISSUE THREAD

**Issue by alexlyee** [immich-app/immich#2844]
### The bug

I'm trying to upload a large library into immich using the command line and somewhere along the way it began throwing a huge number of errors. It looks like this:

```
immich_microservices     | [Nest] 1  - 06/18/2023, 9:46:44 PM   ERROR [JobService] Unable to run job handler: TypeError: Cannot read properties of null (reading 'to')
immich_microservices     | [Nest] 1  - 06/18/2023, 9:46:44 PM   ERROR [JobService] TypeError: Cannot read properties of null (reading 'to')
immich_microservices     |     at CommunicationRepository.send (/usr/src/app/dist/apps/microservices/libs/infra/src/repositories/communication.repository.js:20:24)
immich_microservices     |     at JobService.onDone (/usr/src/app/dist/apps/microservices/libs/domain/src/job/job.service.js:143:50)
immich_microservices     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_microservices     |     at async /usr/src/app/dist/apps/microservices/libs/domain/src/job/job.service.js:100:25
immich_microservices     |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:352:28)
immich_microservices     |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:535:24)
immich_microservices     | [Nest] 1  - 06/18/2023, 9:46:44 PM   ERROR [JobService] Object:
immich_microservices     | {
immich_microservices     |   "id": "c54b16d9-e1e0-4181-a473-1730e6df6704",
immich_microservices     |   "source": "upload"
immich_microservices     | }
```

```
Z:\PicturesandVideos>immich upload --key KEY --server http://IP:2283/api --recursive MobileDevicePhotographs/
Checking connectivity with Immich instance...
Server status: OK
Checking credentials...
Login status: OK
Successful authentication for user me@alexs.space
Indexing local assets...
Indexing complete, found 62358 local assets
Comparing local assets with those on the Immich instance...
A total of 62358 assets will be uploaded to the server
Do you want to start upload now? (y/n) y
Start uploading...
Upload Progress | ██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 26% || 16364/62358 || Current file [Z:\PicturesandVideos\M 
```

And when I connect to the web server it now says:

```
 Error - Something went wrong

Not found: /search/photos/02a077f5-0829-47aa-9229-115485624d52 (500)
Stacktrace

Error: Not found: /search/photos/02a077f5-0829-47aa-9229-115485624d52
    at resolve (file:///usr/src/app/build/server/index.js:3861:18)
    at resolve (file:///usr/src/app/build/server/index.js:3736:34)
    at Object.handle (file:///usr/src/app/build/server/chunks/hooks.server-5df290a2.js:21:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///usr/src/app/build/server/index.js:3734:22)
    at async Array.ssr (file:///usr/src/app/build/handler.js:1207:3)
```

What is happening? It says it's still uploading... I hope this isn't going to be a huge pain to fix.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.16.0

### Version of Immich Mobile App

v1.16.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
1. upload a large library using the CLI
2. wait
```

**Comment by alextran1502** [comment]
Is it the /search page you are accessing or the /photos page?

**Comment by jrasm91** [comment]
I believe the 404 error has been resolved.
