### ISSUE TITLE
[BUG] No such file or directory errors when uploading live photos

### ISSUE THREAD

**Issue by paulmorabito** [immich-app/immich#3047]
### The bug

Have noticed a few dead image links when accessing Immich on the web. Upon checking the microservices container logs, I can see this occurring a few times:

```

t] 7  - 06/30/2023, 1:24:10 PM     LOG [MediaService] Successfully generated video thumbnail 8559c7c6-1129-4518-b9d2-06d2462443cc
[Nest] 7  - 06/30/2023, 1:25:56 PM     LOG [MediaService] Start encoding video dc48b89a-f75e-4a2f-9167-9dedf19140e3 -vcodec h264,-acodec aac,-movflags faststart,-vf scale=-2:720,-preset ultrafast,-crf 23
[Nest] 7  - 06/30/2023, 1:25:56 PM     LOG [MediaService] Generating video thumbnail
[Nest] 7  - 06/30/2023, 1:25:57 PM     LOG [MediaService] Successfully generated video thumbnail dc48b89a-f75e-4a2f-9167-9dedf19140e3
[Nest] 7  - 06/30/2023, 1:26:08 PM     LOG [MediaService] Encoding success dc48b89a-f75e-4a2f-9167-9dedf19140e3
[Nest] 7  - 06/30/2023, 1:26:08 PM     LOG [MediaService] Start encoding video 7f32cbbf-c41c-4954-8307-71eae2d1fcfe -vcodec h264,-acodec aac,-movflags faststart,-vf scale=-2:720,-preset ultrafast,-crf 23
[Nest] 7  - 06/30/2023, 1:26:09 PM     LOG [MediaService] Encoding success 7f32cbbf-c41c-4954-8307-71eae2d1fcfe
[Nest] 7  - 06/30/2023, 1:26:10 PM     LOG [MediaService] Start encoding video 18393964-5477-4479-9286-3d749465d048 -vcodec h264,-acodec aac,-movflags faststart,-vf scale=720:-2,-preset ultrafast,-crf 23
[Nest] 7  - 06/30/2023, 1:26:11 PM     LOG [MediaService] Encoding success 18393964-5477-4479-9286-3d749465d048
[Nest] 7  - 06/30/2023, 1:26:19 PM     LOG [MediaService] Start encoding video bfcf2aaf-6cc1-4b61-aee9-61484cd5d547 -vcodec h264,-acodec aac,-movflags faststart,-vf scale=-2:720,-preset ultrafast,-crf 23
[Nest] 7  - 06/30/2023, 1:26:19 PM   ERROR [JobService] Unable to run job handler: Error: ffmpeg exited with code 1: upload/upload/b1f69b2c-d492-42fe-82de-9f8fc4d7aa47/201b003d-fcae-416b-ad2e-c16de8997393.mov: No such file or directory
[Nest] 7  - 06/30/2023, 1:26:19 PM   ERROR [JobService] Error: ffmpeg exited with code 1: upload/upload/b1f69b2c-d492-42fe-82de-9f8fc4d7aa47/201b003d-fcae-416b-ad2e-c16de8997393.mov: No such file or directory
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Nest] 7  - 06/30/2023, 1:26:19 PM   ERROR [JobService] Object:
{
  "id": "bfcf2aaf-6cc1-4b61-aee9-61484cd5d547"
}
```

I’m running the latest Immich (1.65) via docker and using the iOS app. Everything appears fine in the app but not in the web view.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.65

### Version of Immich Mobile App

1.64 (build 104)

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Take photos/videos
2. Load Immich app and upload photos.
```

### Additional information

Am traveling at the moment with limited connectivity so getting all the details in above is a bit difficult. Let me know if you need anything else to debug though and I will get as soon as I can.

**Comment by alextran1502** [comment]
Do you use the default ffmpeg config?

**Comment by mertalev** [comment]
It seems to work if you run missing jobs for thumbnails and transcoding. My guess is that when the files are moved, the paths aren't updated in these jobs.

**Comment by paulmorabito** [comment]
I can see in Job Status that three thumbnails are marked as failed. Tried to re-run thumbnails on missing only and get the following: 

```Nest] 7  - 07/01/2023, 5:29:00 PM   ERROR [JobService] Unable to run job handler: Error: Input file is missing: upload/upload/b1f69b2c-d492-42fe-82de-9f8fc4d7aa47/d75c5d27-e8d8-4360-a8a8-2847af8eda4a.jpg
[Nest] 7  - 07/01/2023, 5:29:00 PM   ERROR [JobService] Error: Input file is missing: upload/upload/b1f69b2c-d492-42fe-82de-9f8fc4d7aa47/d75c5d27-e8d8-4360-a8a8-2847af8eda4a.jpg
[Nest] 7  - 07/01/2023, 5:29:00 PM   ERROR [JobService] Object:
{
  "id": "e1fade0f-8268-44b2-914b-321e32f11d68"
}

[Nest] 7  - 07/01/2023, 5:29:00 PM   ERROR [JobService] Unable to run job handler: Error: Input file is missing: upload/upload/b1f69b2c-d492-42fe-82de-9f8fc4d7aa47/cca0bed6-6e5b-46fc-bf02-beab69eab483.HEIC
[Nest] 7  - 07/01/2023, 5:29:00 PM   ERROR [JobService] Error: Input file is missing: upload/upload/b1f69b2c-d492-42fe-82de-9f8fc4d7aa47/cca0bed6-6e5b-46fc-bf02-beab69eab483.HEIC
[Nest] 7  - 07/01/2023, 5:29:00 PM   ERROR [JobService] Object:
{
  "id": "477a8f7f-95a3-431d-bfb3-5bc56f079615"
}
```

For transcoding videos, I can see one has failed and running on missing only, I get:
```
Nest] 7  - 07/01/2023, 5:33:22 PM   ERROR [JobService] Unable to run job handler: Error: ffprobe exited with code 1
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r10) 20220924
  configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gnutls --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   5.  0.100 /  5.  0.100
  libpostproc    57.  1.100 / 57.  1.100
upload/upload/b1f69b2c-d492-42fe-82de-9f8fc4d7aa47/672029d5-7801-47b1-9451-babc4e70ca21.mov: No such file or directory

[Nest] 7  - 07/01/2023, 5:33:22 PM   ERROR [JobService] Error: ffprobe exited with code 1
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r10) 20220924
  configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gnutls --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   5.  0.100 /  5.  0.100
  libpostproc    57.  1.100 / 57.  1.100
upload/upload/b1f69b2c-d492-42fe-82de-9f8fc4d7aa47/672029d5-7801-47b1-9451-babc4e70ca21.mov: No such file or directory

    at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Nest] 7  - 07/01/2023, 5:33:22 PM   ERROR [JobService] Object:
{
  "id": "64503773-009a-4ab2-9efb-836493d998c5"
}

[Nest] 7  - 07/01/2023, 5:33:22 PM   ERROR [JobService] Unable to run job handler: Error: ffprobe exited with code 1
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r10) 20220924
  configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gnutls --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   5.  0.100 /  5.  0.100
  libpostproc    57.  1.100 / 57.  1.100
upload/upload/b1f69b2c-d492-42fe-82de-9f8fc4d7aa47/cbe8d925-19b7-400f-8eba-a30fbd32d55f.mov: No such file or directory

[Nest] 7  - 07/01/2023, 5:33:22 PM   ERROR [JobService] Error: ffprobe exited with code 1
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r10) 20220924
  configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gnutls --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   5.  0.100 /  5.  0.100
  libpostproc    57.  1.100 / 57.  1.100
upload/upload/b1f69b2c-d492-42fe-82de-9f8fc4d7aa47/cbe8d925-19b7-400f-8eba-a30fbd32d55f.mov: No such file or directory

    at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Nest] 7  - 07/01/2023, 5:33:22 PM   ERROR [JobService] Object:
{
  "id": "e1e72789-19ef-4a84-822c-d3916c9a7a59"
}

```

**Comment by mertalev** [comment]
Hmm, this is probably related to #2877. Also yes, there's a nightly job for generating thumbnails, but not for transcoding videos. Sorry there's no immediate fix for the ones where `missing` still fails, but I'll see if I can mitigate the issue for now by having transcoding run only after storage template migration.
