### ISSUE TITLE
[BUG] immich-learning Docker crashed

### ISSUE THREAD

**Issue by dp20eic** [immich-app/immich#3099]
### The bug

Hi,
I installed `immich` at my Synology into Docker Container, but after I upgrade from 1.63 to 1.65 the `immich-mashine-learning` container didn't start anymore.

### The OS that Immich Server is running on

Synologs DSM 7.2 with altran1502/immich-machine-learning

### Version of Immich Server

v1.65.0

### Version of Immich Mobile App

v1.65.0 build.88

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
      - /volume1/docker/immich/cache:/cache
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=user #### Dein Benutzername wählen ####
DB_PASSWORD=user #### Hier sicheres Passwort wählen ####
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

REDIS_HOSTNAME=immich_redis

# Optional Redis settings:
# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET

UPLOAD_LOCATION=/opt/containers/immich/upload

LOG_LEVEL=simple

JWT_SECRET=randomstringthatissolongandpowerfulthatnoonecanguess

# DISABLE_REVERSE_GEOCODING=false

# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM

# REVERSE_GEOCODING_PRECISION=3

# Custom message on the login page, should be written in HTML form.
# For example PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"

PUBLIC_LOGIN_PAGE_MESSAGE=

TYPESENSE_API_KEY=irgendein Kennwort ## Hier ein Kennwort eingeben##
```

### Reproduction steps

```bash
1.
2.
3.
...
```

### Additional information

```
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 11, in <module>
    from .config import settings
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 11, in <module>
    from .config import settings
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 11, in <module>
    from .config import settings
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 11, in <module>
    from .config import settings
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 11, in <module>
    from .config import settings
ImportError: attempted relative import with no known parent package
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 11, in <module>
    from .config import settings
ImportError: attempted relative import with no known parent package
```

**Comment by alextran1502** [comment]
Can you help update your docker-compose file to the latest version in the release note and then pull the images again?

**Comment by dp20eic** [comment]
> Can you help update your docker-compose file to the latest version in the release note and then pull the images again?

Hi,
thank you for the help, I delete everything, I'm at the beginning and this installation was for testing, so I install it with the standard `.yml` and `.env` file and it works.

After my new hardware arrived, I will install it like this.

With kind regards
Bernd

**Comment by dp20eic** [comment]
Install it with standard docker-compose and environment file solve my problem.
