### ISSUE TITLE
[BUG] Error: 500 getaddrinfo ENOTFOUND immich-server

### ISSUE THREAD

**Issue by maltokyo** [immich-app/immich#3666]
### The bug

Get simply "500 getaddrinfo ENOTFOUND immich-server" upon install of a brand new server, follwing exactly the docs.

Logs show this but not sure if this is the issue:

```
immich_server            | node:fs:1398
immich_server            |   handleErrorFromBinding(ctx);
immich_server            |   ^
immich_server            | 
immich_server            | Error: ENOENT: no such file or directory, mkdir 'upload/library'
immich_server            |     at mkdirSync (node:fs:1398:3)
immich_server            |     at FilesystemProvider.mkdirSync (/usr/src/app/dist/infra/repositories/filesystem.provider.js:98:32)
immich_server            |     at StorageService.init (/usr/src/app/dist/domain/storage/storage.service.js:28:32)
immich_server            |     at AppService.init (/usr/src/app/dist/immich/app.service.js:28:29)
immich_server            |     at bootstrap (/usr/src/app/dist/immich/main.js:31:45)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
immich_server            |   errno: -2,
immich_server            |   syscall: 'mkdir',
immich_server            |   code: 'ENOENT',
immich_server            |   path: 'upload/library'
immich_server            | }
immich_server            | 
immich_server            | Node.js v18.17.0
immich_server            | 
immich_server exited with code 0
```

Notice exit code 0

then a bit later this - More logs:

```
immich_machine_learning  | INFO:     Started server process [6]
immich_machine_learning  | INFO:     Waiting for application startup.
immich_microservices     | [Nest] 7  - 08/13/2023, 6:47:02 PM     LOG [MetadataExtractionProcessor] Reverse Geocoding Initialized
immich_microservices     | [Nest] 7  - 08/13/2023, 6:47:02 PM     LOG [NestApplication] Nest application successfully started +34ms
immich_microservices     | [Nest] 7  - 08/13/2023, 6:47:02 PM     LOG [ImmichMicroservice] Immich Microservices is listening on http://[::1]:3002 [v1.72.2] [PRODUCTION] 
immich_machine_learning  | Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [NestFactory] Starting Nest application...
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +75ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +9ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +241ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] InfraModule dependencies initialized +7ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] AppModule dependencies initialized +4ms
immich_server            | [Nest] 7  - 08/13/2023, 6:47:07 PM     LOG [InstanceLoader] DomainModule dependencies initialized +5ms
immich_server            | node:fs:1398
immich_server            |   handleErrorFromBinding(ctx);
immich_server            |   ^
immich_server            | 
immich_server            | Error: ENOENT: no such file or directory, mkdir 'upload/library'
immich_server            |     at mkdirSync (node:fs:1398:3)
immich_server            |     at FilesystemProvider.mkdirSync (/usr/src/app/dist/infra/repositories/filesystem.provider.js:98:32)
immich_server            |     at StorageService.init (/usr/src/app/dist/domain/storage/storage.service.js:28:32)
immich_server            |     at AppService.init (/usr/src/app/dist/immich/app.service.js:28:29)
immich_server            |     at bootstrap (/usr/src/app/dist/immich/main.js:31:45)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
immich_server            |   errno: -2,
immich_server            |   syscall: 'mkdir',
immich_server            |   code: 'ENOENT',
immich_server            |   path: 'upload/library'
immich_server            | }
immich_server            | 
immich_server            | Node.js v18.17.0
immich_server            | 
immich_server exited with code 1
```

### The OS that Immich Server is running on

Debian 12 latest updates applied

### Version of Immich Server

v1.72.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Exactly as here: https://github.com/immich-app/immich/blob/main/docker/docker-compose.yml
```

### Your .env content

```Shell
Exactly as here, with the mandatory ones including typesense all filled
https://github.com/immich-app/immich/blob/main/docker/example.env
```

### Reproduction steps

```bash
1. New install
```

**Comment by maltokyo** [comment]
Immich could not write to the upload directory, that was it.  Solved.  Apologies.

**Comment by ArduCrow** [comment]
> Immich could not write to the upload directory, that was it. Solved. Apologies.

Solved, how?
