### ISSUE TITLE
[BUG] mobile: map fails to load

### ISSUE THREAD

**Issue by klejejs** [immich-app/immich#4207]
### The bug

Opening map view on mobile, it says loading, after which it shows an empty map and says there are 0 assets although that is not the case.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.79.1

### Version of Immich Mobile App

v1.79.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open app
2. Open map
3. No assets are shown
```

### Additional information

The following error is thrown in the app:
```
Cannot get map markers Null check operator used on a null value

#0      MapMarkerResponseDto.fromJson (package:openapi/model/map_marker_response_dto.dart:60)
#1      ApiClient._deserialize (package:openapi/api_client.dart:315)
#2      ApiClient._deserialize.<anonymous closure> (package:openapi/api_client.dart:448)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:344)
#5      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#6      new _List.of (dart:core-patch/array.dart:127)
#7      new List.of (dart:core-patch/array_patch.dart:49)
#8      SetBase.toList (dart:collection/set.dart:119)
#9      ApiClient._deserialize (package:openapi/api_client.dart:449)
#10     ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#11     AssetApi.getMapMarkers (package:openapi/api/asset_api.dart:969)
<asynchronous suspension>
#12     MapSerivce.getMapMarkers (package:immich_mobile/modules/map/services/map.service.dart:30)
<asynchronous suspension>
#13     mapMarkersProvider.<anonymous closure> (package:immich_mobile/modules/map/providers/map_marker.provider.dart:23)
<asynchronous suspension>
#14     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:337)
<asynchronous suspension>
```

**Comment by Rihcus** [comment]
Issue seems to be resolved in v1.80.0
