### ISSUE TITLE
[BUG] First name needs to be set from OAuth

### ISSUE THREAD

**Issue by samip5** [immich-app/immich#5039]
### The bug

```
[Nest] 8  - 11/14/2023, 1:57:19 PM   ERROR [ExceptionsHandler] column UserTokenEntity__UserTokenEntity_user.firstName does not exist
QueryFailedError: column UserTokenEntity__UserTokenEntity_user.firstName does not exist
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2183:25)
    at async SelectQueryBuilder.getRawMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1973:26)
    at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getOne (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:711:25)
    at async AuthService.validateUserToken (/usr/src/app/dist/domain/auth/auth.service.js:319:21)
    at async AppGuard.canActivate (/usr/src/app/dist/immich/app.guard.js:81:25)
    at async GuardsConsumer.tryActivate (/usr/src/app/node_modules/@nestjs/core/guards/guards-consumer.js:16:17)
```

### The OS that Immich Server is running on

Kubernetes (k3s)

### Version of Immich Server

v1.83.0

### Version of Immich Mobile App

v1.83.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
Not entirely sure...
```

### Additional information

This is the first time I noticed that it is borked..

**Comment by schuhbacca** [comment]
From the discord: 
That column was removed in 1.86.0, are you sure you're running that version on all containers?

**Comment by samip5** [comment]
No, I was still running an older server replica and for some reason it had worked for a WHILE before I noticed it.
