### ISSUE TITLE
[BUG] The immich-machine-learning service reported an error: can't start new thread

### ISSUE THREAD

**Issue by hkaikai** [immich-app/immich#5222]
### The bug

immich-machine-learning service is always restarting,and reported an error: can't start new thread

### The OS that Immich Server is running on

CentOS 7.6

### Version of Immich Server

v1.88.1

### Version of Immich Mobile App

v1.88.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

services:
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.88.1
    volumes:
      - model-cache:/cache
    restart: always
    ports:
      - 3003:3003
    env_file:
      - .env

volumes:
  model-cache:
```

### Your .env content

```Shell
MACHINE_LEARNING_REQUEST_THREADS=1
MACHINE_LEARNING_MODEL_INTRA_OP_THREADS=1
```

### Reproduction steps

```bash
1.docker compose up -d
2.docker logs immich_machine_learning
```

### Additional information

```bash
Starting gunicorn 21.2.0                           
[11/21/23 10:55:39] INFO     Listening at: http://0.0.0.0:3003 (8)              
[11/21/23 10:55:39] INFO     Using worker: uvicorn.workers.UvicornWorker        
[11/21/23 10:55:39] INFO     Booting worker with pid: 9                         
[11/21/23 10:55:43] ERROR    Exception in worker process                        
                             Traceback (most recent call last):                 
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/gunicorn/ar
                             biter.py", line 609, in spawn_worker               
                                 worker.init_process()                          
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/uvicorn/wor
                             kers.py", line 66, in init_process                 
                                 super(UvicornWorker, self).init_process()      
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/gunicorn/wo
                             rkers/base.py", line 134, in init_process          
                                 self.load_wsgi()                               
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/gunicorn/wo
                             rkers/base.py", line 146, in load_wsgi             
                                 self.wsgi = self.app.wsgi()                    
                                             ^^^^^^^^^^^^^^^                    
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/gunicorn/ap
                             p/base.py", line 67, in wsgi                       
                                 self.callable = self.load()                    
                                                 ^^^^^^^^^^^                    
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/gunicorn/ap
                             p/wsgiapp.py", line 58, in load                    
                                 return self.load_wsgiapp()                     
                                        ^^^^^^^^^^^^^^^^^^^                     
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/gunicorn/ap
                             p/wsgiapp.py", line 48, in load_wsgiapp            
                                 return util.import_app(self.app_uri)           
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^           
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/gunicorn/ut
                             il.py", line 371, in import_app                    
                                 mod = importlib.import_module(module)          
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^          
                               File                                             
                             "/usr/local/lib/python3.11/importlib/__init__.py", 
                             line 126, in import_module                         
                                 return _bootstrap._gcd_import(name[level:],    
                             package, level)                                    
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^                                       
                               File "<frozen importlib._bootstrap>", line 1204, 
                             in _gcd_import                                     
                               File "<frozen importlib._bootstrap>", line 1176, 
                             in _find_and_load                                  
                               File "<frozen importlib._bootstrap>", line 1147, 
                             in _find_and_load_unlocked                         
                               File "<frozen importlib._bootstrap>", line 690,  
                             in _load_unlocked                                  
                               File "<frozen importlib._bootstrap_external>",   
                             line 940, in exec_module                           
                               File "<frozen importlib._bootstrap>", line 241,  
                             in _call_with_frames_removed                       
                               File "/usr/src/app/main.py", line 17, in <module>
                                 from app.models.base import InferenceModel     
                               File "/usr/src/app/models/__init__.py", line 8,  
                             in <module>                                        
                                 from .facial_recognition import FaceRecognizer 
                               File "/usr/src/app/models/facial_recognition.py",
                             line 7, in <module>                                
                                 from insightface.model_zoo import ArcFaceONNX, 
                             RetinaFace                                         
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/insightface
                             /__init__.py", line 18, in <module>                
                                 from . import app                              
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/insightface
                             /app/__init__.py", line 2, in <module>             
                                 from .mask_renderer import *                   
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/insightface
                             /app/mask_renderer.py", line 8, in <module>        
                                 from ..thirdparty import face3d                
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/insightface
                             /thirdparty/face3d/__init__.py", line 3, in        
                             <module>                                           
                                 from . import mesh                             
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/insightface
                             /thirdparty/face3d/mesh/__init__.py", line 11, in  
                             <module>                                           
                                 from . import vis                              
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/insightface
                             /thirdparty/face3d/mesh/vis.py", line 6, in        
                             <module>                                           
                                 import matplotlib.pyplot as plt                
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/matplotlib/
                             pyplot.py", line 56, in <module>                   
                                 import matplotlib.colorbar                     
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/matplotlib/
                             colorbar.py", line 19, in <module>                 
                                 from matplotlib import _api, cbook,            
                             collections, cm, colors, contour, ticker           
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/matplotlib/
                             contour.py", line 14, in <module>                  
                                 from matplotlib.backend_bases import           
                             MouseButton                                        
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/matplotlib/
                             backend_bases.py", line 46, in <module>            
                                 from matplotlib import (                       
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/matplotlib/
                             text.py", line 16, in <module>                     
                                 from .font_manager import FontProperties       
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/matplotlib/
                             font_manager.py", line 1582, in <module>           
                                 fontManager = _load_fontmanager()              
                                               ^^^^^^^^^^^^^^^^^^^              
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/matplotlib/
                             font_manager.py", line 1576, in _load_fontmanager  
                                 fm = FontManager()                             
                                      ^^^^^^^^^^^^^                             
                               File                                             
                             "/opt/venv/lib/python3.11/site-packages/matplotlib/
                             font_manager.py", line 1037, in __init__           
                                 timer.start()                                  
                               File "/usr/local/lib/python3.11/threading.py",   
                             line 964, in start                                 
                                 _start_new_thread(self._bootstrap, ())         
                             RuntimeError: can't start new thread               
[11/21/23 10:55:43] INFO     Worker exiting (pid: 9)                            
[11/21/23 10:55:43] ERROR    Worker (pid:9) exited with code 3                  
[11/21/23 10:55:43] ERROR    Shutting down: Master                              
[11/21/23 10:55:43] ERROR    Reason: Worker failed to boot.
```

**Comment by bo0tzz** [comment]
Does this still happen if you remove those env vars? cc @mertalev

**Comment by hkaikai** [comment]
> Does this still happen if you remove those env vars? cc @mertalev

still will

**Comment by mertalev** [comment]
Hmm, is this a normal server, or a SoC like a Raspberry Pi? How many cores does it have? What's the CPU model?

Setting `MACHINE_LEARNING_REQUEST_THREADS=0` disables the thread pool. Does that change anything?

**Comment by mertalev** [comment]
Oh, this doesn't seem to be getting far enough for that to make difference. It's a thread spun up by matplotlib while modules are still being imported. Not sure why it would fail to create a single thread.

**Comment by hkaikai** [comment]
> Hmm, is this a normal server, or a SoC like a Raspberry Pi? What's the CPU model?
> 
> Setting `MACHINE_LEARNING_REQUEST_THREADS=0` disables the thread pool. Does that change anything?

Tencent Cloud Lightweight Single Core Server

**Comment by mertalev** [comment]
There have been some optimizations to the machine learning service that might have fixed this. I'm closing this, but feel free to re-open if you're still having the issue on the latest version.
