### ISSUE TITLE
[BUG] Can't upload a single file with CLI

### ISSUE THREAD

**Issue by rupebac** [immich-app/immich#5460]
### The bug

Uploading a single file, reports back "No assets found, exiting" with: immich upload "blabla.jpeg", if you point to the directory it is fine, "immich upload .". This is no happening in 1.87.0.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

1.89.0

### Version of Immich Mobile App

1.89.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
irrelevant
```

### Your .env content

```Shell
irrelevant
```

### Reproduction steps

```bash
immich upload "blabla.jpeg"
```

**Comment by AhmedSoliman** [comment]
Same problem here (server 1.88.2, CLI: 2.0.4). Trying `--skip-hash` gets me a different result. Http 502 and a server crash. 

The CLI logs a massive output, here is the first few lines:
```
/usr/lib/node_modules/@immich/cli/node_modules/axios/dist/node/axios.cjs:1967
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 502
    at settle (/usr/lib/node_modules/@immich/cli/node_modules/axios/dist/node/axios.cjs:1967:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/@immich/cli/node_modules/axios/dist/node/axios.cjs:3062:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1589:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_RESPONSE',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
```

The server on the other hand logs this before crashing:
```
2023-12-03 23:39:59.913238+00:00node:events:492
2023-12-03 23:39:59.913333+00:00throw er; // Unhandled 'error' event
2023-12-03 23:39:59.913363+00:00^
2023-12-03 23:39:59.913381+00:002023-12-03T23:39:59.913381964Z
2023-12-03 23:39:59.913488+00:00Error: Unexpected end of form
2023-12-03 23:39:59.913518+00:00at Multipart._final (/usr/src/app/node_modules/busboy/lib/types/multipart.js:588:17)
2023-12-03 23:39:59.913537+00:00at callFinal (node:internal/streams/writable:757:12)
2023-12-03 23:39:59.913555+00:00at prefinish (node:internal/streams/writable:769:7)
2023-12-03 23:39:59.913574+00:00at finishMaybe (node:internal/streams/writable:779:5)
2023-12-03 23:39:59.913591+00:00at Writable.end (node:internal/streams/writable:687:5)
2023-12-03 23:39:59.913637+00:00at IncomingMessage.onend (node:internal/streams/readable:756:10)
2023-12-03 23:39:59.913656+00:00at Object.onceWrapper (node:events:628:28)
2023-12-03 23:39:59.913676+00:00at IncomingMessage.emit (node:events:514:28)
2023-12-03 23:39:59.913704+00:00at endReadableNT (node:internal/streams/readable:1408:12)
2023-12-03 23:39:59.913733+00:00at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-12-03 23:39:59.913772+00:00Emitted 'error' event on Multipart instance at:
2023-12-03 23:39:59.913804+00:00at emitErrorNT (node:internal/streams/destroy:151:8)
2023-12-03 23:39:59.913834+00:00at emitErrorCloseNT (node:internal/streams/destroy:116:3)
2023-12-03 23:39:59.913864+00:00at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2023-12-03 23:39:59.913895+00:00storageErrors: []
2023-12-03 23:39:59.913968+00:00}
```

**Comment by titro** [comment]
same behavior on 1.90

CLI always says "No assets found, exiting"

tried:
immich upload <file>

which directory "." it is working

**Comment by MrModest** [comment]
@rupebac thanks for the fix. Can you please suggest how can I use your fixed version of the CLI instead of original one that installed via npm?

**Comment by etnoy** [comment]
Thanks for the report
