### ISSUE TITLE
operator class "cosine_ops" does not exist for access method "vectors"

### ISSUE THREAD

**Issue by szinn** [immich-app/immich#5766]
### The bug

in a k8s system running 1.91.0

```
[Nest] 7  - 12/16/2023, 8:34:31 PM   ERROR [ExceptionHandler] operator class "cosine_ops" does not exist for access method "vectors"
QueryFailedError: operator class "cosine_ops" does not exist for access method "vectors"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddCLIPEmbeddingIndex1700713994428.up (/usr/src/app/dist/infra/migrations/1700713994428-AddCLIPEmbeddingIndex.js:9:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)```


### The OS that Immich Server is running on

Talos 1.6.0

### Version of Immich Server

v1.91.0

### Version of Immich Mobile App

latest

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
DB cluster definition

https://github.com/szinn/k8s-homelab/tree/main/kubernetes/apps/media/immich/app/db
```

### Your .env content

```Shell
N/a
```

### Reproduction steps

```bash
1. Deploy to cluster
2. immich-microservices starts green and then gets the error above
3.
...
```

**Comment by alextran1502** [comment]
what version of the database, database extension are you using?

**Comment by stavros-k** [comment]
@alextran1502 
Seems to be an upstream change, not sure if immich needs to take any actions
https://github.com/tensorchord/pgvecto.rs/issues/191
