### ISSUE TITLE
[BUG] after upgrade 1.92, DB error

### ISSUE THREAD

**Issue by naxiemolv** [immich-app/immich#5823]
### The bug

could not open extension control file "/usr/share/postgresql/14/extension/vectors.control": No such file or directory

[Nest] 12172  - 12/18/2023, 7:53:20 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
QueryFailedError: could not open extension control file "/usr/share/postgresql/14/extension/vectors.control": No such file or directory
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UsePgVectors1700713871511.up (/app/immich/server/dist/infra/migrations/1700713871511-UsePgVectors.js:18:9)
    at async MigrationExecutor.executePendingMigrations (/app/immich/server/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:148:17)
[Nest] 12172  - 12/18/2023, 7:53:20 PM   ERROR [ExceptionHandler] could not open extension control file "/usr/share/postgresql/14/extension/vectors.control": No such file or directory
QueryFailedError: could not open extension control file "/usr/share/postgresql/14/extension/vectors.control": No such file or directory
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UsePgVectors1700713871511.up (/app/immich/server/dist/infra/migrations/1700713871511-UsePgVectors.js:18:9)
    at async MigrationExecutor.executePendingMigrations (/app/immich/server/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:148:17)

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.9.2

### Version of Immich Mobile App

v1.9.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
hosted by unraid
```

### Your .env content

```Shell
hosted by unraid
```

### Reproduction steps

```bash
[Nest] 11942  - 12/18/2023, 7:52:54 PM     LOG [NestFactory] Starting Nest application...
[Nest] 11942  - 12/18/2023, 7:52:54 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 11942  - 12/18/2023, 7:52:54 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 11942  - 12/18/2023, 7:52:54 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 11942  - 12/18/2023, 7:52:54 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 11942  - 12/18/2023, 7:52:54 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 11942  - 12/18/2023, 7:52:54 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 11942  - 12/18/2023, 7:52:54 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 11942  - 12/18/2023, 7:52:54 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 11942  - 12/18/2023, 7:52:54 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 12172  - 12/18/2023, 7:53:20 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
QueryFailedError: could not open extension control file "/usr/share/postgresql/14/extension/vectors.control": No such file or directory
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UsePgVectors1700713871511.up (/app/immich/server/dist/infra/migrations/1700713871511-UsePgVectors.js:18:9)
    at async MigrationExecutor.executePendingMigrations (/app/immich/server/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:148:17)
```

**Comment by zackpollard** [comment]
Please read the [release notes](https://github.com/immich-app/immich/releases/tag/v1.91.0) when you perform updates.

**Comment by naxiemolv** [comment]
thanks, change 「postgresql14」 to 「tensorchord/pgvecto-rs:pg14-v0.1.11」

**Comment by zyystudio** [comment]
> Please read the [release notes](https://github.com/immich-app/immich/releases/tag/v1.91.0) when you perform updates.

is it possible to make it compatible with official postgresql vector name like /usr/share/postgresql/14/extension/vector.control instead of /usr/share/postgresql/14/extension/vectors.control.
eg after apt-get install postgresql-15-pgvector, I found my postgresql15 pgvector with /usr/share/postgresql/15/extension/vector.control which leading to the docker start failure



   length: 314,
    severity: 'ERROR',
    code: '0A000',
    detail: 'Could not open extension control file "/usr/share/postgresql/15/extension/vectors.control": No such file or directory.',
    hint: 'The extension must first be installed on the system where PostgreSQL is running.',
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'extension.c',
    line: '539',
    routine: 'parse_extension_control_file'
