### ISSUE TITLE
[BUG] web build fails with 'Named export 'APIKeyApi' not found'

### ISSUE THREAD

**Issue by waclaw66** [immich-app/immich#6393]
### The bug

I'm trying to build web according `immich/server/Dockerfile` as usual, however it fails on `npm run build` with following message...
Not sure what could be wrong, open-api is already built.

```
node:internal/event_target:1088
  process.nextTick(() => { throw err; });
                           ^
file:///home/waclaw/src/immich/web/.svelte-kit/output/server/chunks/api.js:1
import { configuration, ActivityApi, AlbumApi, AuditApi, LibraryApi, AssetApi, AuthenticationApi, FaceApi, JobApi, APIKeyApi, OAuthApi, PartnerApi, SearchApi, ServerInfoApi, SharedLinkApi, PersonApi, SystemConfigApi, UserApi, common, base, JobName, AssetJobName } from "@immich/sdk";
                                                                                                                   ^^^^^^^^^
SyntaxError: Named export 'APIKeyApi' not found. The requested module '@immich/sdk' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@immich/sdk';
const { configuration, ActivityApi, AlbumApi, AuditApi, LibraryApi, AssetApi, AuthenticationApi, FaceApi, JobApi, APIKeyApi, OAuthApi, PartnerApi, SearchApi, ServerInfoApi, SharedLinkApi, PersonApi, SystemConfigApi, UserApi, common, base, JobName, AssetJobName } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async analyse (file:///home/waclaw/src/immich/web/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:60:16)
    at async MessagePort.<anonymous> (file:///home/waclaw/src/immich/web/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

latest

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
manual execution of commands from immich/server/Dockerfile
```

**Comment by martabal** [comment]
Have you moved any folders ? Just updated the AIO folders for v1.93.0 without any issues

**Comment by waclaw66** [comment]
Not sure, what folders do you mean? I haven't moved any folders, I'm just trying to execute build commands from `server/Dockerfile` without using Docker.

**Comment by martabal** [comment]
> Not sure, what folders do you mean?

Root folders in the repo such as `web`, `server`, `open-api` ...

> I'm just trying to execute build commands from server/Dockerfile

Oh sorry, according to your logs, I thought the error occurred when building the web app

**Comment by waclaw66** [comment]
> Root folders in the repo such as `web`, `server`, `open-api` ...

Haven't touch them.
 
> Oh sorry, according to your logs, I thought the error occurred when building the web app

Yes, I'm building web app, open-api and server has been built without any error, but web is failing.
