### ISSUE TITLE
[BUG]  Override year time value on upload

### ISSUE THREAD

**Issue by jflattery** [immich-app/immich#670]
**Describe the bug**
When syncing (backup) on iOS several images fail with the following error.

```
QueryFailedError: date/time field value out
of range: "0000-12-29T19:00:00.000"
```

**Task List**

- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Begin syncing on iOS

**Expected behavior**
Sync without errors.

**System**
- Phone OS [iOS, Android]: `iOS 15.6`
- Server Version: `1.28.2`
- Mobile App Version: `1.28.0 build.55`

**Comment by panoti** [comment]
Hi @jflattery, can you provide us a demo pic to reproduce this issue? thank you very much.

**Comment by jflattery** [comment]
I sent them to @alextran1502 on discord. If you require a copy, I can send them to you as well.

**Comment by panoti** [comment]
Ah, if someone has seen it, you don't need to send it to me. I replied because no one responded. Thanks @jflattery.

**Comment by mattalat1** [comment]
I have this issue as well.

987 photos that fail to upload.

`Nest] 695  - 02/03/2025, 1:40:53 PM   ERROR [Api:AssetMediaService~a4l0c5ul] Error uploading file PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
    at ErrorResponse (/app/immich/server/node_modules/postgres/cjs/src/connection.js:788:26)
    at handle (/app/immich/server/node_modules/postgres/cjs/src/connection.js:474:6)
    at Socket.data (/app/immich/server/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 695  - 02/03/2025, 1:40:53 PM   ERROR [Api:ErrorInterceptor~a4l0c5ul] Unknown error: PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
    at ErrorResponse (/app/immich/server/node_modules/postgres/cjs/src/connection.js:788:26)
    at handle (/app/immich/server/node_modules/postgres/cjs/src/connection.js:474:6)
    at Socket.data (/app/immich/server/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)`

**Comment by gardz** [comment]
Same error here for approximately 9715 assets when trying to upload to Immich via the iOS app. The other 28k images/videos uploaded fine though. 


[Nest] 17  - 02/25/2025, 4:38:47 PM   ERROR [Api:AssetMediaService~s22e3kvm] Error uploading file PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 17  - 02/25/2025, 4:38:47 PM   ERROR [Api:ErrorInterceptor~s22e3kvm] Unknown error: PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Query failed : {
  durationMs: 1.0748189985752106,
  error: PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
      at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
      at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
      at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '22008',
    where: "unnamed portal parameter $8 = '...'",
    file: 'datetime.c',
    line: '3773',
    routine: 'DateTimeParseError'
  },
  sql: 'insert into "assets" ("ownerId", "libraryId", "checksum", "originalPath", "deviceAssetId", "deviceId", "fileCreatedAt", "fileModifiedAt", "localDateTime", "type", "isFavorite", "isArchived", "duration", "isVisible", "originalFileName") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) returning *',
  params: [
    '83120ac5-f7db-42c1-9cc5-e9228ed3911e',
    null,
    <Buffer 61 a4 07 cd 83 d0 46 88 47 36 c5 1a ab f3 1a 08 98 ab de 54>,
    'upload/upload/83120ac5-f7db-42c1-9cc5-e9228ed3911e/dd/e0/dde02153-99f7-4ccd-90d1-9ef47b2a1564.JPG',
    '440343F4-9F2E-488D-A6A8-14675D06DC3F/L0/001',
    '8ec37b6e1ecfb6098b7421263583df16d12dfbc7f5596c2a24159350219e1ab6',
    2013-11-30T16:05:41.000Z,
    0000-12-30T00:00:00.000Z,
    2013-11-30T16:05:41.000Z,
    'IMAGE',
    false,
    false,
    '0:00:00.000000',
    true,
    'P1130367.JPG'
  ]

**Comment by w4vz** [comment]
I have the same error: 1300 assets failed to upload. I have the latest version v1.136.0

```
[Nest] 18  - 07/28/2025, 11:21:16 AM   ERROR [Api:AssetMediaService~n6lbsium] Error uploading file PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
    at ErrorResponse (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:794:26)
    at handle (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:480:6)
    at Socket.data (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 18  - 07/28/2025, 11:21:16 AM   ERROR [Api:ErrorInterceptor~n6lbsium] Unknown error: PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
    at ErrorResponse (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:794:26)
    at handle (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:480:6)
    at Socket.data (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Query failed : {
  durationMs: 0.7416470000171103,
  error: PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
      at ErrorResponse (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:794:26)
      at handle (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:480:6)
      at Socket.data (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '22008',
    where: "unnamed portal parameter $8 = '...'",
    file: 'datetime.c',
    line: '3773',
    routine: 'DateTimeParseError'
  },
  sql: 'insert into "asset" ("ownerId", "libraryId", "checksum", "originalPath", "deviceAssetId", "deviceId", "fileCreatedAt", "fileModifiedAt", "localDateTime", "type", "isFavorite", "duration", "visibility", "originalFileName") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) returning *',
  params: [
    '7ec67c0e-98bb-4ffa-a6a0-c8df35b36ab5',
    null,
    <Buffer 6f 93 fe 63 8e 6c c4 63 4a 0c b0 87 93 d2 e6 12 fd e7 3a 07>,
    '/usr/src/app/upload/upload/7ec67c0e-98bb-4ffa-a6a0-c8df35b36ab5/08/8c/088c19b2-3619-4263-acc7-0a2ac33db86d.gif',
    '7AD16682-39C0-4713-9837-29B5CBCF7C34/L0/001',
    '28f6f5e1dca1fb75020446d3fcae22fab8667353dcf1a9d956fd32c0842df4e2',
    2011-09-10T16:39:16.000Z,
    0000-12-30T00:00:00.000Z,
    2011-09-10T16:39:16.000Z,
    'IMAGE',
    false,
    '0:00:00.000000',
    'timeline',
    'audio_tape.gif'
  ]
}
[Nest] 18  - 07/28/2025, 11:21:16 AM   ERROR [Api:AssetMediaService~s89tig54] Error uploading file PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
    at ErrorResponse (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:794:26)
    at handle (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:480:6)
    at Socket.data (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 18  - 07/28/2025, 11:21:16 AM   ERROR [Api:ErrorInterceptor~s89tig54] Unknown error: PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
    at ErrorResponse (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:794:26)
    at handle (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:480:6)
    at Socket.data (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Query failed : {
  durationMs: 0.8386460000183433,
  error: PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
      at ErrorResponse (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:794:26)
      at handle (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:480:6)
      at Socket.data (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '22008',
    where: "unnamed portal parameter $8 = '...'",
    file: 'datetime.c',
    line: '3773',
    routine: 'DateTimeParseError'
  },
  sql: 'insert into "asset" ("ownerId", "libraryId", "checksum", "originalPath", "deviceAssetId", "deviceId", "fileCreatedAt", "fileModifiedAt", "localDateTime", "type", "isFavorite", "duration", "visibility", "originalFileName") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) returning *',
  params: [
    '7ec67c0e-98bb-4ffa-a6a0-c8df35b36ab5',
    null,
    <Buffer 64 05 77 01 30 4f 72 89 26 0d 03 86 8f aa 41 82 a2 14 91 ae>,
    '/usr/src/app/upload/upload/7ec67c0e-98bb-4ffa-a6a0-c8df35b36ab5/56/94/5694c540-2e75-421f-8332-994f37982f98.gif',
    'D7692BEE-7E88-4E53-A7A9-0F18A0F6A61C/L0/001',
    '28f6f5e1dca1fb75020446d3fcae22fab8667353dcf1a9d956fd32c0842df4e2',
    2007-04-22T13:23:32.000Z,
    0000-12-30T00:00:00.000Z,
    2007-04-22T13:23:32.000Z,
    'IMAGE',
    false,
    '0:00:00.000000',
    'timeline',
    'chakras.gif'
  ]
}
[Nest] 18  - 07/28/2025, 11:21:16 AM   ERROR [Api:AssetMediaService~eylf2njk] Error uploading file PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
    at ErrorResponse (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:794:26)
    at handle (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:480:6)
    at Socket.data (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 18  - 07/28/2025, 11:21:16 AM   ERROR [Api:ErrorInterceptor~eylf2njk] Unknown error: PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
    at ErrorResponse (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:794:26)
    at handle (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:480:6)
    at Socket.data (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Query failed : {
  durationMs: 0.7255160000058822,
  error: PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
      at ErrorResponse (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:794:26)
      at handle (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:480:6)
      at Socket.data (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '22008',
    where: "unnamed portal parameter $8 = '...'",
    file: 'datetime.c',
    line: '3773',
    routine: 'DateTimeParseError'
  },
  sql: 'insert into "asset" ("ownerId", "libraryId", "checksum", "originalPath", "deviceAssetId", "deviceId", "fileCreatedAt", "fileModifiedAt", "localDateTime", "type", "isFavorite", "duration", "visibility", "originalFileName") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) returning *',
  params: [
    '7ec67c0e-98bb-4ffa-a6a0-c8df35b36ab5',
    null,
    <Buffer 2d 77 50 00 9e 36 3e b1 60 3a e3 75 c1 bd 99 90 21 5e ae eb>,
    '/usr/src/app/upload/upload/7ec67c0e-98bb-4ffa-a6a0-c8df35b36ab5/ce/6f/ce6fe101-381f-4349-b3b9-c843defd67ca.gif',
    'C52A4461-D390-45EC-AD94-6E92C423201B/L0/001',
    '28f6f5e1dca1fb75020446d3fcae22fab8667353dcf1a9d956fd32c0842df4e2',
    2007-03-23T19:55:18.000Z,
    0000-12-30T00:00:00.000Z,
    2007-03-23T19:55:18.000Z,
    'IMAGE',
    false,
    '0:00:00.000000',
    'timeline',
    'my-sweet-shadow.gif'
  ]
}
[Nest] 18  - 07/28/2025, 11:21:16 AM   ERROR [Api:AssetMediaService~n2bt3xwi] Error uploading file PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
    at ErrorResponse (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:794:26)
    at handle (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:480:6)
    at Socket.data (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 18  - 07/28/2025, 11:21:16 AM   ERROR [Api:ErrorInterceptor~n2bt3xwi] Unknown error: PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
    at ErrorResponse (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:794:26)
    at handle (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:480:6)
    at Socket.data (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Query failed : {
  durationMs: 0.6847019999986514,
  error: PostgresError: date/time field value out of range: "0000-12-30T00:00:00.000Z"
      at ErrorResponse (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:794:26)
      at handle (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:480:6)
      at Socket.data (/usr/src/app/server/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '22008',
    where: "unnamed portal parameter $8 = '...'",
    file: 'datetime.c',
    line: '3773',
    routine: 'DateTimeParseError'
  },
  sql: 'insert into "asset" ("ownerId", "libraryId", "checksum", "originalPath", "deviceAssetId", "deviceId", "fileCreatedAt", "fileModifiedAt", "localDateTime", "type", "isFavorite", "duration", "visibility", "originalFileName") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) returning *',
  params: [
    '7ec67c0e-98bb-4ffa-a6a0-c8df35b36ab5',
    null,
    <Buffer 94 e9 87 10 e3 a1 f8 36 f1 9e 7d 91 fb 59 be b7 7a 22 42 dc>,
    '/usr/src/app/upload/upload/7ec67c0e-98bb-4ffa-a6a0-c8df35b36ab5/ec/72/ec728d78-faa9-4a63-ac67-5360f01faa1e.gif',
    '8D6451E7-1E1F-4BFE-A137-138B9DB5430E/L0/001',
    '28f6f5e1dca1fb75020446d3fcae22fab8667353dcf1a9d956fd32c0842df4e2',
    2006-08-05T01:36:30.000Z,
    0000-12-30T00:00:00.000Z,
    2006-08-05T01:36:30.000Z,
    'IMAGE',
    false,
    '0:00:00.000000',
    'timeline',
    'lotus.gif'
  ]
}
```
