### ISSUE TITLE
Database not created while using podman pods

### ISSUE THREAD

**Issue by ygaeon** [immich-app/immich#6778]
### The bug

Using the "release" tagged versions as of today.

Based off of https://github.com/immich-app/immich/blob/main/docker/docker-compose.yml 

As seen in the Reproduction steps, there's no database created.

Been searching the code base for an "old school" sql definition to manually create the database. None found .. guess it's generated :-)

Please advice!

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.93.3

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
DB_HOSTNAME=localhost
DB_USERNAME=postgres
DB_PASSWORD=<PWD>
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
# podman pod create --name pod-immich --publish 2283:3001

# podman pull redis:6.2-alpine
# podman run -d --pod pod-immich --name immich_redis redis:6.2-alpine

# podman pull tensorchord/pgvecto-rs:pg14-v0.1.11
# podman run -d --pod pod-immich --name immich_postgres --env-file <ENV_FILE> --volume <...>/pod-immich/postgres:/var/lib/postgresql/data tensorchord/pgvecto-rs:pg14-v0.1.11

# podman pull ghcr.io/immich-app/immich-server:v1.93.3
# podman run -d --pod pod-immich --name immich_server --env-file <ENV_FILE> --volume <...>/pod-immich/upload:/usr/src/app/upload --volume /etc/localtime:/etc/localtime:ro immich-server:v1.93.3 start.sh immich
```
**immich_server log**
```
[Nest] 2  - 01/30/2024, 7:25:26 PM     LOG [NestFactory] Starting Nest application...
[Nest] 2  - 01/30/2024, 7:25:26 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 2  - 01/30/2024, 7:25:26 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 2  - 01/30/2024, 7:25:26 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 2  - 01/30/2024, 7:25:26 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 2  - 01/30/2024, 7:25:26 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 2  - 01/30/2024, 7:25:26 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 2  - 01/30/2024, 7:25:26 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 2  - 01/30/2024, 7:25:26 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 2  - 01/30/2024, 7:25:26 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 2  - 01/30/2024, 7:25:26 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
error: database "immich" does not exist
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
<...>
```

**immich_postgres log**
```
2024-01-30 19:25:26.104 UTC [111] FATAL:  database "immich" does not exist
```

**No database created**
```
# podman exec -it immich_postgres bash
root@immich:/# su - postgres
postgres@immich:~$ psql
psql (14.10 (Debian 14.10-1.pgdg120+1))
Type "help" for help.

postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)

postgres=#
```
```


### Additional information

_No response_

**Comment by bo0tzz** [comment]
The docker-compose.yml is set up to have postgres automatically create the database
```yaml
  database:
    (...)
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
```

Is that in your setup as well?

**Comment by ygaeon** [comment]
Thanks for your prompt reply @bo0tzz 
Indeed I had missed those and now added them.
Seems to be connecting OK now.

Now I just need to deal with wrong timezone :)

(issue can be closed)
