### ISSUE TITLE
Can't select photos for an album before entering a name

### ISSUE THREAD

**Issue by HarHarLinks** [immich-app/immich#7056]
### The bug

```
Not found or no album.read access - 400 - Bad Request
AxiosError: Request failed with status code 400
    at nn (https://immich/_app/immutable/chunks/api.hDXpMC_1.js:3:1042)
    at XMLHttpRequest.b (https://immich/_app/immutable/chunks/api.hDXpMC_1.js:3:4227)
    at ze.request (https://immich/_app/immutable/chunks/api.hDXpMC_1.js:5:3105)
    at async Jr (https://immich/_app/immutable/nodes/5.JdjrRsMm.js:1:2725)
    at async be (https://immich/_app/immutable/chunks/entry.XM6ES_OL.js:1:12873)
```

### The OS that Immich Server is running on

debian

### Version of Immich Server

v1.94.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
according to example
```

### Your .env content

```Shell
only added TZ=Europe/Berlin
```

### Reproduction steps

```bash
1. create new album
2. don't enter a name
3. select pictures
4. click done
5. it does not work
6. try to escape by reloading the page
```

**Comment by waclaw66** [comment]
Cannot reproduce.

**Comment by HarHarLinks** [comment]
me either :/

**Comment by HarHarLinks** [comment]
me either :/
