### ISSUE TITLE
Error "type "vecf16" already exists" migrating pgvecto.rs to 0.2.0

### ISSUE THREAD

**Issue by p4block** [immich-app/immich#7302]
### The bug

Immich by itself or using the query described in the new version docs
```
ALTER EXTENSION vectors UPDATE TO '0.2.0';
QueryFailedError: type "vecf16" already exists
```

### The OS that Immich Server is running on

Container

### Version of Immich Server

v1.95.1

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Not relevant
```

### Your .env content

```Shell
Not relevant
```

### Reproduction steps

```bash
Get into your database, run the migration
```

### Additional information

This is likely to be a pgvecto.rs issue or something specific to my database, leaving here for other people to see

**Comment by isole** [comment]
I've run into this issue myself, (but with pg16-v0.2.0). I created the missing extension `vectors` befor the `ALTER EXTENSION` statement, i.e. 

```
BEGIN;

CREATE SCHEMA IF NOT EXISTS vectors;
ALTER DATABASE immich SET search_path TO "$user", public, vectors;
SET search_path TO "$user", public, vectors;

UPDATE pg_catalog.pg_extension SET extversion = '0.1.11' WHERE extname = 'vectors';
UPDATE pg_catalog.pg_extension SET extrelocatable = true WHERE extname = 'vectors';

CREATE EXTENSION vectors;

ALTER EXTENSION vectors SET SCHEMA vectors;
UPDATE pg_catalog.pg_extension SET extrelocatable = false WHERE extname = 'vectors';
ALTER EXTENSION vectors UPDATE TO '0.2.0';

SELECT pgvectors_upgrade();

COMMIT;
```

Got past the `QueryFailedError`, but I am still getting this:
```
[Nest] 303  - 02/21/2024, 11:43:35 AM     LOG [CommunicationRepository] Initialized websocket server
[Nest] 303  - 02/21/2024, 11:43:35 AM     LOG [DatabaseService] Updating pgvecto.rs extension to 0.2.0
[Nest] 303  - 02/21/2024, 11:43:35 AM    WARN [DatabaseService] 
        The pgvecto.rs extension version is 0.1.11, but 0.2.0 is available.
        Immich attempted to update the extension, but failed to do so.
        This may be because Immich does not have the necessary permissions to update the extension.

        Please run 'ALTER EXTENSION vectors UPDATE' manually as a superuser.
        See https://immich.app/docs/guides/database-queries for how to query the database.
[Nest] 303  - 02/21/2024, 11:43:35 AM   ERROR [DatabaseService] QueryFailedError: permission denied for table pg_extension
/app/immich/server/dist/domain/database/database.service.js:137
            throw new Error(`
                  ^

Error: 
        The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.

        If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it.
        In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser.
        See https://immich.app/docs/guides/database-queries for how to query the database.

        Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version.
    at DatabaseService.assertVectorExtension (/app/immich/server/dist/domain/database/database.service.js:137:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/domain/database/database.service.js:39:13
    at async /app/immich/server/dist/infra/repositories/database.repository.js:185:23
```

Note that the extension vectors is in `0.2.0.`

```
postgres=# alter extension vectors update;
NOTICE:  version "0.2.0" of extension "vectors" is already installed
ALTER EXTENSION
```

**Comment by isole** [comment]
Btw, granting superuser privileges to immich, gets the job done.

`# alter user immich with superuser;`

**Comment by andonovski** [comment]
For me, this helped:

```
CREATE SCHEMA IF NOT EXISTS vectors;
UPDATE pg_catalog.pg_extension SET extversion = '0.1.11' WHERE extname = 'vectors';
UPDATE pg_catalog.pg_extension SET extrelocatable = true WHERE extname = 'vectors';

CREATE EXTENSION vectors;

ALTER EXTENSION vectors SET SCHEMA vectors;
UPDATE pg_catalog.pg_extension SET extrelocatable = false WHERE extname = 'vectors';
ALTER EXTENSION vectors UPDATE TO '0.2.0';

SELECT pgvectors_upgrade();
```

It started to work immediately.

**Comment by JannesV** [comment]
I'm having the same issue I can't seem to upgrade no matter what I try. My immich user is set to superuser but it seems to fail aswell.

**Comment by njzhenghao** [comment]
> For me, this helped:
> 
> ```
> CREATE SCHEMA IF NOT EXISTS vectors;
> UPDATE pg_catalog.pg_extension SET extversion = '0.1.11' WHERE extname = 'vectors';
> UPDATE pg_catalog.pg_extension SET extrelocatable = true WHERE extname = 'vectors';
> 
> CREATE EXTENSION vectors;
> 
> ALTER EXTENSION vectors SET SCHEMA vectors;
> UPDATE pg_catalog.pg_extension SET extrelocatable = false WHERE extname = 'vectors';
> ALTER EXTENSION vectors UPDATE TO '0.2.0';
> 
> SELECT pgvectors_upgrade();
> ```
> 
> It started to work immediately.

could you tell me about your upgrading steps?

for me ,i use this commands to upgrade (docker compose pull && docker compose up -d).
Then the issuse ([Error "type "vecf16" already exists" migrating pgvecto.rs to 0.2.0](https://github.com/immich-app/immich/issues/7302#top))  comes.

**Comment by TheChrisK** [comment]
> ALTER EXTENSION vectors UPDATE TO '0.2.0';

I get extension `"vectors" has no update path from version "0.1.11" to version "0.2.0"` when I run that.
