### ISSUE TITLE
After upgrading to 1.95.1, PostgreS encountered the following error: "could not receive data from client: Connection reset by peer"

### ISSUE THREAD

**Issue by nodis** [immich-app/immich#7347]
### The bug

1."Immich" cannot open the homepage
2.PostgreSql encountered the following error: "could not receive data from client: Connection reset by peer"
3.The 'immich_server' container keeps restarting indefinitely

'immich_server' container log：
```

2024-02-22T12:57:28. Node.js v20.11.0
2024-02-22T13:00:43 [32m[Nest] 7  - [39m02/22/2024, 1:00:43 PM [32m    LOG[39m [38;5;3m[CommunicationRepository] [39m[32mInitialized websocket server[39m
2024-02-22T13:00:46. [32m[Nest] 7  - [39m02/22/2024, 1:00:46 PM [32m    LOG[39m [38;5;3m[SystemConfigService] [39m[32mLogLevel=log (set via system config)[39m
2024-02-22T13:00:50. [32m[Nest] 7  - [39m02/22/2024, 1:00:46 PM [32m    LOG[39m [38;5;3m[LibraryService] [39m[32mStarting to watch library 8bxxxxxxxxxxxxxxxf1bbdda with import path(s) /media/volume2/photo[39m
2024-02-22T13:01:52.node:internal/errors:563
2024-02-22T13:01:52. ErrorCaptureStackTrace(err);
2024-02-22T13:01:52. Error: ENOSPC: System limit for number of file watchers reached, watch '/media/volume2/photo/ALL_PHOTOS/@eaDir/TG-2023-06-14-220412366.mp4@SynoEAStream'
2024-02-22T13:01:52.    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
2024-02-22T13:01:52. at Object.watch (node:fs:2473:36)
2024-02-22T13:01:52. at createFsWatchInstance (/usr/src/app/node_modules/chokidar/lib/nodefs-handler.js:119:15)
2024-02-22T13:01:52. at setFsWatchListener (/usr/src/app/node_modules/chokidar/lib/nodefs-handler.js:166:15)
2024-02-22T13:01:52. at NodeFsHandler._watchWithNodeFs (/usr/src/app/node_modules/chokidar/lib/nodefs-handler.js:331:14)
2024-02-22T13:01:52.at NodeFsHandler._handleFile (/usr/src/app/node_modules/chokidar/lib/nodefs-handler.js:395:23)
2024-02-22T13:01:52.at NodeFsHandler._addToNodeFs (/usr/src/app/node_modules/chokidar/lib/nodefs-handler.js:637:21)
2024-02-22T13:01:52.Emitted 'error' event on FSWatcher instance at:
2024-02-22T13:01:52.at FSWatcher._handleError (/usr/src/app/node_modules/chokidar/index.js:647:10)
2024-02-22T13:01:52. at NodeFsHandler._addToNodeFs (/usr/src/app/node_modules/chokidar/lib/nodefs-handler.js:645:18) {
2024-02-22T13:01:52. errno: -28,
2024-02-22T13:01:52.syscall: 'watch',
2024-02-22T13:01:52.code: 'ENOSPC',
2024-02-22T13:01:52. path: '/media/volume2/photo/Google Photos_20231006/ALL_PHOTOS/@eaDir/TG-2023-06-14-220412366.mp4@SynoEAStream',
2024-02-22T13:01:52.869283747Z   filename: '/media/volume2/photo/ALL_PHOTOS/@eaDir/TG-2023-06-14-220412366.mp4@SynoEAStream'
2024-02-22T13:01:52.869293918Z }
2024-02-22T13:01:52.869301290Z 
2024-02-22T13:01:52.869309220Z Node.js v20.11.0
2024-02-22T13:03:26.696009186Z [32m[Nest] 7  - [39m02/22/2024, 1:03:26 PM [32m    LOG[39m [38;5;3m[CommunicationRepository] [39m[32mInitialized websocket server[39m
2024-02-22T13:03:29.177758096Z [32m[Nest] 7  - [39m02/22/2024, 1:03:26 PM [32m    LOG[39m [38;5;3m[SystemConfigService] [39m[32mLogLevel=log (set via system config)[39m
2024-02-22T13:03:36.157477709Z [32m[Nest] 7  - [39m02/22/2024, 1:03:26 PM [32m    LOG[39m [38;5;3m[LibraryService] [39m[32mStarting to watch library 8b05xxxxxxxxxxxxxxxxxbdda with import path(s) /media/volume2/photo[39m
2024-02-22T13:04:14.266204499Z node:internal/errors:563
2024-02-22T13:04:15.314774509Z     ErrorCaptureStackTrace(err);
2024-02-22T13:04:15.314846165Z     ^
2024-02-22T13:04:15.314861993Z 
2024-02-22T13:04:15.314875386Z Error: ENOSPC: System limit for number of file watchers reached, watch '/media/volume2/photo/ALL_PHOTOS/@eaDir/IMG_20230520_145355(1).jpg/SYNOINDEX_MEDIA_INFO'
2024-02-22T13:04:15.314910252Z     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
2024-02-22T13:04:15.314948530Z     at Object.watch (node:fs:2473:36)
2024-02-22T13:04:15.314961246Z     at createFsWatchInstance (/usr/src/app/node_modules/chokidar/lib/nodefs-handler.js:119:15)
2024-02-22T13:04:15.314977801Z     at setFsWatchListener (/usr/src/app/node_modules/chokidar/lib/nodefs-handler.js:166:15)
2024-02-22T13:04:15.314991071Z     at NodeFsHandler._watchWithNodeFs (/usr/src/app/node_modules/chokidar/lib/nodefs-handler.js:331:14)
2024-02-22T13:04:15.315004187Z     at NodeFsHandler._handleFile (/usr/src/app/node_modules/chokidar/lib/nodefs-handler.js:395:23)
2024-02-22T13:04:15.315019110Z     at NodeFsHandler._addToNodeFs (/usr/src/app/node_modules/chokidar/lib/nodefs-handler.js:637:21)
2024-02-22T13:04:15.315054923Z Emitted 'error' event on FSWatcher instance at:
2024-02-22T13:04:15.315081498Z     at FSWatcher._handleError (/usr/src/app/node_modules/chokidar/index.js:647:10)
2024-02-22T13:04:15.315126485Z     at NodeFsHandler._addToNodeFs (/usr/src/app/node_modules/chokidar/lib/nodefs-handler.js:645:18) {
2024-02-22T13:04:15.315143748Z   errno: -28,
2024-02-22T13:04:15.315154655Z   syscall: 'watch',
2024-02-22T13:04:15.315164634Z   code: 'ENOSPC',
2024-02-22T13:04:15.315174051Z   path: '/media/volume2/photo/ALL_PHOTOS/@eaDir/IMG_20230520_145355(1).jpg/SYNOINDEX_MEDIA_INFO',
2024-02-22T13:04:15.315186078Z   filename: '/media/volume2/photo/ALL_PHOTOS/@eaDir/IMG_20230520_145355(1).jpg/SYNOINDEX_MEDIA_INFO'
2024-02-22T13:04:15.315198348Z }
2024-02-22T13:04:15.315207338Z 
2024-02-22T13:04:15.315216818Z Node.js v20.11.0

``` 

The log of the "immich_postgresr" container：
```typescript
2024-02-22T12:49:37.555825223Z 
2024-02-22T12:49:37.841966348Z PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-02-22T12:49:37.842042015Z 
2024-02-22T12:49:45.258272680Z 2024-02-22 12:49:45.258 UTC [1] LOG:  starting PostgreSQL 14.10 (Debian 14.10-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-02-22T12:49:45.373213096Z 2024-02-22 12:49:45.373 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-02-22T12:49:45.373308501Z 2024-02-22 12:49:45.373 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-02-22T12:49:47.195783490Z 2024-02-22 12:49:47.195 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-02-22T12:49:48.832742537Z 2024-02-22 12:49:48.832 UTC [27] LOG:  database system was shut down at 2024-02-22 12:47:42 UTC
2024-02-22T12:49:48.833577932Z [2024-02-22T12:49:48Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/1624042".
2024-02-22T12:49:48.833635322Z [2024-02-22T12:49:48Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/2031252".
2024-02-22T12:49:48.833662910Z [2024-02-22T12:49:48Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/1624042/segments/0d78e21b-5906-4a03-b38f-4d562fb1edf4".
2024-02-22T12:49:51.183880212Z 2024-02-22 12:49:51.183 UTC [1] LOG:  database system is ready to accept connections
2024-02-22T12:50:05.064818406Z [2024-02-22T12:50:05Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/2031252/segments/ce1ed2dc-5b6b-4749-a7de-61b536c3948d".
2024-02-22T12:55:01.658516564Z 2024-02-22 12:55:01.658 UTC [32] LOG:  using stale statistics instead of current ones because stats collector is not responding
2024-02-22T12:56:01.702212608Z 2024-02-22 12:56:01.702 UTC [32] LOG:  using stale statistics instead of current ones because stats collector is not responding
2024-02-22T12:56:25.337828479Z 2024-02-22 12:56:11.840 UTC [63] LOG:  using stale statistics instead of current ones because stats collector is not responding
2024-02-22T12:57:07.220005236Z 2024-02-22 12:57:07.219 UTC [49] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T12:59:01.782688717Z 2024-02-22 12:59:01.782 UTC [32] LOG:  using stale statistics instead of current ones because stats collector is not responding
2024-02-22T12:59:12.192747688Z 2024-02-22 12:59:11.869 UTC [66] LOG:  using stale statistics instead of current ones because stats collector is not responding
2024-02-22T13:01:54.390062628Z 2024-02-22 13:01:54.389 UTC [70] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:01:54.477878439Z 2024-02-22 13:01:54.389 UTC [69] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:07:52.708710845Z 2024-02-22 13:07:52.708 UTC [86] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:10:44.552362483Z 2024-02-22 13:10:44.552 UTC [94] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:13:23.309377646Z 2024-02-22 13:13:23.309 UTC [102] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:15:02.587246993Z 2024-02-22 13:15:02.587 UTC [32] LOG:  using stale statistics instead of current ones because stats collector is not responding
2024-02-22T13:16:57.699396086Z 2024-02-22 13:16:57.699 UTC [111] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:19:49.382342487Z 2024-02-22 13:19:49.382 UTC [120] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:19:50.086129533Z 2024-02-22 13:19:49.382 UTC [119] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:22:25.792435119Z 2024-02-22 13:22:25.792 UTC [133] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:22:39.589378600Z 2024-02-22 13:22:39.589 UTC [128] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:22:41.436574382Z 2024-02-22 13:22:39.589 UTC [129] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:25:40.313361579Z 2024-02-22 13:25:40.313 UTC [138] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:25:40.313830716Z 2024-02-22 13:25:40.313 UTC [137] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:27:35.488390533Z 2024-02-22 13:27:35.488 UTC [145] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:27:35.488918627Z 2024-02-22 13:27:35.488 UTC [144] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:29:12.154535941Z 2024-02-22 13:29:12.154 UTC [153] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:30:48.963502996Z 2024-02-22 13:30:48.963 UTC [159] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:30:51.842829963Z 2024-02-22 13:30:48.963 UTC [160] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:35:01.453368938Z 2024-02-22 13:35:01.453 UTC [175] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:36:32.728415375Z 2024-02-22 13:36:32.728 UTC [181] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:44:50.204362935Z 2024-02-22 13:44:50.204 UTC [221] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:46:45.812329492Z 2024-02-22 13:46:45.812 UTC [229] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:46:45.812747350Z 2024-02-22 13:46:45.812 UTC [228] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:49:49.968357400Z 2024-02-22 13:49:49.968 UTC [241] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T13:58:32.738362673Z 2024-02-22 13:58:32.738 UTC [256] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:05:37.583638342Z 2024-02-22 14:05:37.583 UTC [277] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:14:31.571468585Z 2024-02-22 14:14:31.571 UTC [306] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:16:58.890823711Z 2024-02-22 14:16:58.890 UTC [314] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:18:35.020945962Z 2024-02-22 14:18:35.020 UTC [326] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:18:49.435387937Z 2024-02-22 14:18:49.435 UTC [321] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:18:49.435801145Z 2024-02-22 14:18:49.435 UTC [322] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:20:35.418487556Z 2024-02-22 14:20:35.418 UTC [330] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:20:35.923033939Z 2024-02-22 14:20:35.418 UTC [329] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:22:07.900903439Z 2024-02-22 14:22:07.900 UTC [337] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:22:08.407588584Z 2024-02-22 14:22:07.900 UTC [336] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:23:48.806848007Z 2024-02-22 14:23:48.806 UTC [344] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:23:49.425348281Z 2024-02-22 14:23:48.806 UTC [343] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:25:53.827547341Z 2024-02-22 14:25:53.827 UTC [352] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:27:29.296899780Z 2024-02-22 14:27:29.296 UTC [358] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:28:59.030422834Z 2024-02-22 14:28:59.030 UTC [365] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:28:59.030820975Z 2024-02-22 14:28:59.030 UTC [366] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:30:33.452298294Z 2024-02-22 14:30:33.452 UTC [372] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:30:33.837199671Z 2024-02-22 14:30:33.452 UTC [371] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:32:06.270421303Z 2024-02-22 14:32:06.270 UTC [380] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:32:06.966580393Z 2024-02-22 14:32:06.270 UTC [379] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:33:42.372758614Z 2024-02-22 14:33:42.372 UTC [386] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:33:42.373212288Z 2024-02-22 14:33:42.372 UTC [387] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:34:58.841589587Z 2024-02-22 14:34:58.841 UTC [393] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:36:16.082162912Z 2024-02-22 14:36:16.082 UTC [401] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:37:32.928425597Z 2024-02-22 14:37:32.928 UTC [407] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:38:55.297318981Z 2024-02-22 14:38:55.297 UTC [415] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:38:55.299130314Z 2024-02-22 14:38:55.297 UTC [414] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:40:09.835427490Z 2024-02-22 14:40:09.835 UTC [421] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:44:05.624378314Z 2024-02-22 14:44:05.624 UTC [441] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:44:05.624819135Z 2024-02-22 14:44:05.624 UTC [440] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:45:17.852144929Z 2024-02-22 14:45:17.852 UTC [446] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:49:02.016956546Z 2024-02-22 14:49:02.016 UTC [465] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:49:02.263811031Z 2024-02-22 14:49:02.016 UTC [466] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:51:31.971344404Z 2024-02-22 14:51:31.971 UTC [477] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T14:51:46.325792838Z 2024-02-22 14:51:46.325 UTC [1] LOG:  received fast shutdown request
2024-02-22T14:51:46.894249528Z 2024-02-22 14:51:46.894 UTC [1] LOG:  aborting any active transactions
2024-02-22T14:51:46.896062823Z 2024-02-22 14:51:46.895 UTC [1] LOG:  background worker "logical replication launcher" (PID 34) exited with exit code 1
2024-02-22T14:51:46.950567701Z 2024-02-22 14:51:46.950 UTC [55] FATAL:  terminating connection due to administrator command
2024-02-22T14:51:46.950670282Z 2024-02-22 14:51:46.950 UTC [54] FATAL:  terminating connection due to administrator command
2024-02-22T14:51:47.396590043Z 2024-02-22 14:51:47.396 UTC [29] LOG:  shutting down
2024-02-22T14:51:50.724388389Z 2024-02-22 14:51:49.539 UTC [483] FATAL:  the database system is shutting down
2024-02-22T14:51:50.724450535Z 2024-02-22 14:51:50.143 UTC [484] FATAL:  the database system is shutting down
2024-02-22T14:51:52.268611541Z 2024-02-22 14:51:52.268 UTC [485] FATAL:  the database system is shutting down
2024-02-22T14:51:54.209734454Z 2024-02-22 14:51:54.209 UTC [1] LOG:  database system is shut down
2024-02-22T14:52:38.350400167Z 
2024-02-22T14:52:38.370377182Z PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-02-22T14:52:38.370450215Z 
2024-02-22T14:52:47.894625525Z 2024-02-22 14:52:47.894 UTC [1] LOG:  starting PostgreSQL 14.10 (Debian 14.10-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-02-22T14:52:48.120055473Z 2024-02-22 14:52:48.119 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-02-22T14:52:48.120177135Z 2024-02-22 14:52:48.119 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-02-22T14:52:53.439233955Z 2024-02-22 14:52:53.439 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-02-22T14:52:55.161793262Z 2024-02-22 14:52:55.161 UTC [27] LOG:  database system was shut down at 2024-02-22 14:51:51 UTC
2024-02-22T14:52:55.162457788Z 2024-02-22 14:52:55.162 UTC [32] FATAL:  the database system is starting up
2024-02-22T14:52:55.162565118Z [2024-02-22T14:52:55Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/1624042".
2024-02-22T14:52:55.162603440Z [2024-02-22T14:52:55Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/2031252".
2024-02-22T14:52:55.162662279Z [2024-02-22T14:52:55Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/1624042/segments/0d78e21b-5906-4a03-b38f-4d562fb1edf4".
2024-02-22T14:52:55.163107853Z 2024-02-22 14:52:55.163 UTC [29] FATAL:  the database system is starting up
2024-02-22T14:52:55.164580407Z 2024-02-22 14:52:55.164 UTC [30] FATAL:  the database system is starting up
2024-02-22T14:52:55.166147428Z 2024-02-22 14:52:55.166 UTC [31] FATAL:  the database system is starting up
2024-02-22T14:52:56.183032118Z 2024-02-22 14:52:56.182 UTC [33] FATAL:  the database system is starting up
2024-02-22T14:53:02.639725848Z 2024-02-22 14:52:58.242 UTC [34] FATAL:  the database system is starting up
2024-02-22T14:53:02.639776826Z 2024-02-22 14:53:00.130 UTC [35] FATAL:  the database system is starting up
2024-02-22T14:53:02.639811662Z 2024-02-22 14:53:00.157 UTC [36] FATAL:  the database system is starting up
2024-02-22T14:53:02.639836309Z 2024-02-22 14:53:01.658 UTC [1] LOG:  database system is ready to accept connections
2024-02-22T14:53:10.840031725Z [2024-02-22T14:53:10Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/2031252/segments/ce1ed2dc-5b6b-4749-a7de-61b536c3948d".
2024-02-22T14:55:28.031200107Z 2024-02-22 14:55:28.030 UTC [60] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:02:16.415390514Z 2024-02-22 15:02:16.415 UTC [83] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:06:32.873342663Z 2024-02-22 15:06:32.873 UTC [97] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:10:07.070193869Z 2024-02-22 15:10:07.070 UTC [105] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:14:31.043287904Z 2024-02-22 15:14:31.043 UTC [116] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:18:44.711113326Z 2024-02-22 15:18:44.710 UTC [133] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:18:45.690490187Z 2024-02-22 15:18:44.710 UTC [134] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:22:32.015110404Z 2024-02-22 15:22:32.015 UTC [147] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:22:32.015564508Z 2024-02-22 15:22:32.015 UTC [148] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:24:35.089066936Z 2024-02-22 15:24:35.088 UTC [156] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:24:35.089539247Z 2024-02-22 15:24:35.088 UTC [155] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:27:59.623347952Z 2024-02-22 15:27:59.623 UTC [170] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:27:59.623731239Z 2024-02-22 15:27:59.623 UTC [169] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:29:53.967403669Z 2024-02-22 15:29:53.966 UTC [175] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:29:54.926650711Z 2024-02-22 15:29:53.966 UTC [176] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:31:39.719378046Z 2024-02-22 15:31:39.719 UTC [184] LOG:  could not receive data from client: Connection reset by peer
2024-02-22T15:31:40.571641131Z 2024-02-22 15:31:39.719 UTC [183] LOG:  could not receive data from client: Connection reset by peer

``` 

### The OS that Immich Server is running on

Synology DSM 7.2

### Version of Immich Server

1.95.1

### Version of Immich Mobile App

1.95.1

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /volume1:/media/volume1:rw
      - /volume2:/media/volume2:rw
      - /volume3:/media/volume3:rw
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /volume1:/media/volume1:rw
      - /volume2:/media/volume2:rw
      - /volume3:/media/volume3:rw
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /volume2/docker/immich/machine/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /volume2/docker/immich/pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume2/Immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=mypassword

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=immich
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by alextran1502** [comment]
Increase the amount of allowed file watch on your system will fix this
