### ISSUE TITLE
Some photos are completely ignored by the app. 

### ISSUE THREAD

**Issue by untenops** [immich-app/immich#776]
I've been trying immich for a little over month now an have been very happy with it.  Really liking it but was wondering if maybe I'm doing something wrong or maybe there is a bug.  Every once in a while some photos I take get completely ignored by the app.  They don't show up in the web interface, and the app never shows them.  But if I go to the Backup settings in the app and double check under Backup Albums, and look in the Camera folder there, the app see the pictures.  But the main page still does not recognize them.

_Originally posted by @untenops in https://github.com/immich-app/immich/discussions/775_

**Comment by alextran1502** [comment]
Can you help providing the required information like docker compose file, your setup information, your phone model...etc? Thanks

**Comment by alextran1502** [comment]
Can you check to see if all the container is functioning, i.e the microservices container. It looks like it was uploaded but the thumbnail aren't generated

**Comment by untenops** [comment]
my compose file 

version: "3.8"

services:
  immich-server:
    user: "${UID}:${GID}" # added this line to get a specific user / group id
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    user: "${UID}:${GID}" # added this line to get a specific user / group id
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    user: "${UID}:${GID}" # added this line to get a specific user / group id
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always
  immich-web:
    user: "${UID}:${GID}" # we added this line to get a specific user / group id
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:

UID and GID were added for permissions, Not sure if I needed it in so many places, but without it I was getting errors. 

Docker is running on a Ubuntu server 22.04 
Upload location is on a NFS shared folder from my main server also Ubuntu server 22.04.  

Phone is a Pixel XL

**Comment by alextran1502** [comment]
If you bring down all the container and bring them back up, does the problem still persist?

**Comment by untenops** [comment]
Restarting didn't fix anything.  But I'm using Portainer and noticed this.

**In microservices Log**

[Nest] 7  - 10/04/2022, 2:16:09 AM     LOG [InstanceLoader] MicroservicesModule dependencies initialized +0ms

node:fs:1349
  handleErrorFromBinding(ctx);

  ^

Error: EACCES: permission denied, mkdir '/usr/src/app/.reverse-geocoding-dump/'

    at Object.mkdirSync (node:fs:1349:3)

    at Object.init (/usr/src/app/node_modules/local-reverse-geocoder/index.js:659:10)

    at /usr/src/app/dist/apps/microservices/apps/microservices/src/processors/metadata-extraction.processor.js:64:42

    at new Promise (<anonymous>)

    at geocoderInit (/usr/src/app/dist/apps/microservices/apps/microservices/src/processors/metadata-extraction.processor.js:63:12)

    at new MetadataExtractionProcessor (/usr/src/app/dist/apps/microservices/apps/microservices/src/processors/metadata-extraction.processor.js:86:13)

    at Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:330:19)

    at callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:48:41)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:122:24) {

  errno: -13,

  syscall: 'mkdir',

  code: 'EACCES',

  path: '/usr/src/app/.reverse-geocoding-dump/'

}

**And Under Web Logs**

Listening on 0.0.0.0:3000

Error: Not found: /_app/immutable/chunks/4-aa16452b.js

    at resolve (file:///usr/src/app/build/server/index.js:2368:18)

    at Object.handle (file:///usr/src/app/build/server/hooks.server-E3O5L5GT.js:5:16)

    at respond (file:///usr/src/app/build/server/index.js:2389:42)

    at runNextTicks (node:internal/process/task_queues:61:5)

    at processImmediate (node:internal/timers:437:9)

Error: Not found: /_app/immutable/components/pages/albums/_page.svelte-a4ab0996.js

    at resolve (file:///usr/src/app/build/server/index.js:2368:18)

    at Object.handle (file:///usr/src/app/build/server/hooks.server-E3O5L5GT.js:5:16)

    at respond (file:///usr/src/app/build/server/index.js:2389:42)

Error: Not found: /_app/immutable/chunks/menu-option-764d05fd.js

    at resolve (file:///usr/src/app/build/server/index.js:2368:18)

    at Object.handle (file:///usr/src/app/build/server/hooks.server-E3O5L5GT.js:5:16)

    at respond (file:///usr/src/app/build/server/index.js:2389:42)

    at runNextTicks (node:internal/process/task_queues:61:5)

    at processImmediate (node:internal/timers:437:9)

Error: Not found: /_app/immutable/chunks/4-aa16452b.js

    at resolve (file:///usr/src/app/build/server/index.js:2368:18)

    at Object.handle (file:///usr/src/app/build/server/hooks.server-E3O5L5GT.js:5:16)

    at respond (file:///usr/src/app/build/server/index.js:2389:42)

Error: Not found: /_app/immutable/chunks/stores-fae4c55c.js

    at resolve (file:///usr/src/app/build/server/index.js:2368:18)

    at Object.handle (file:///usr/src/app/build/server/hooks.server-E3O5L5GT.js:5:16)

    at respond (file:///usr/src/app/build/server/index.js:2389:42)

Error: Not found: /_app/immutable/chunks/notification-b3d7e3df.js

    at resolve (file:///usr/src/app/build/server/index.js:2368:18)

    at Object.handle (file:///usr/src/app/build/server/hooks.server-E3O5L5GT.js:5:16)

    at respond (file:///usr/src/app/build/server/index.js:2389:42)

    at runNextTicks (node:internal/process/task_queues:61:5)

    at processImmediate (node:internal/timers:437:9)

Error: Not found: /_app/immutable/chunks/1-216a61ee.js

    at resolve (file:///usr/src/app/build/server/index.js:2368:18)

    at Object.handle (file:///usr/src/app/build/server/hooks.server-E3O5L5GT.js:5:16)

    at respond (file:///usr/src/app/build/server/index.js:2389:42)

    at runNextTicks (node:internal/process/task_queues:61:5)

    at processImmediate (node:internal/timers:437:9)

Error: Not found: /_app/immutable/chunks/navigation-8e9af8a7.js

    at resolve (file:///usr/src/app/build/server/index.js:2368:18)

    at Object.handle (file:///usr/src/app/build/server/hooks.server-E3O5L5GT.js:5:16)

    at respond (file:///usr/src/app/build/server/index.js:2389:42)

    at runNextTicks (node:internal/process/task_queues:61:5)

    at processImmediate (node:internal/timers:437:9)

Error: Not found: /_app/immutable/chunks/1-216a61ee.js

    at resolve (file:///usr/src/app/build/server/index.js:2368:18)

    at Object.handle (file:///usr/src/app/build/server/hooks.server-E3O5L5GT.js:5:16)

    at respond (file:///usr/src/app/build/server/index.js:2389:42)

Error: Not found: /_app/immutable/chunks/10-54ea7921.js

    at resolve (file:///usr/src/app/build/server/index.js:2368:18)

    at Object.handle (file:///usr/src/app/build/server/hooks.server-E3O5L5GT.js:5:16)

    at respond (file:///usr/src/app/build/server/index.js:2389:42)

Error: Not found: /_app/immutable/chunks/10-54ea7921.js

    at resolve (file:///usr/src/app/build/server/index.js:2368:18)

    at Object.handle (file:///usr/src/app/build/server/hooks.server-E3O5L5GT.js:5:16)

    at respond (file:///usr/src/app/build/server/index.js:2389:42)

Listening on 0.0.0.0:3000

**Comment by alextran1502** [comment]
Ah that would explain why you don't see the new images since `microservies` crashes/not starting up with that error. And `microservices` container handles all of the thumbnail generation process so that the photos/videos can be displayed on the client.

I think it might be related you to your additional parameter of the of the container such as `user: "${UID}:${GID}"`. What would happen if you use the original, unmodified `docker-compose` file?

**Comment by untenops** [comment]
If I remove the  `user: "${UID}:${GID}"` lines form the compose file I think I lose access to the upload folder and get this in immich-immich-server-1 Logs

```
[Nest] 7  - 10/04/2022, 1:27:07 PM     LOG [NestApplication] Nest application successfully started +26ms

[Nest] 7  - 10/04/2022, 1:27:07 PM     LOG [ImmichServer] Running Immich Server in PRODUCTION environment - version 1.30.0

[Nest] 7  - 10/04/2022, 1:27:37 PM   ERROR [getAssetThumbnail] Cannot create read stream for asset 400e169d-11d8-41cb-9599-f19022fae589

[Nest] 7  - 10/04/2022, 1:27:37 PM   ERROR [getAssetThumbnail] Cannot create read stream for asset 48bc3089-d7c9-457b-bce5-74a9b8e17101

[Nest] 7  - 10/04/2022, 1:27:37 PM   ERROR [getAssetThumbnail] Cannot create read stream for asset 0a002be5-1814-4335-b1da-5e746061f9f8

[Nest] 7  - 10/04/2022, 1:27:37 PM   ERROR [getAssetThumbnail] Cannot create read stream for asset 139c3dae-a729-47e5-b0f0-3f6aed53e87c

[Nest] 7  - 10/04/2022, 1:27:37 PM   ERROR [getAssetThumbnail] Cannot create read stream for asset 1f8cba3c-bfd3-44b2-8d1c-25f8ef3acdba
```

And the web page no longer shows the thumb nails or photos.

**Comment by alextran1502** [comment]
Hmm interesting issue with the user permission here. @zoodyy Do you have any suggestion for this issue?

**Comment by zoodyy** [comment]
To solve the issue with geocoding:

Add the following to `docker-compose.yml`:
```yml
immich-microservices:
  volumes:
     - ${GEOCODING_DATA}:${REVERSE_GEOCODING_DUMP_DIRECTORY}
```
and add (and configure) this to `.env`:
```
GEOCODING_DATA=/path/to/an/empty/folder/with/full/permissions/to/immich/user
REVERSE_GEOCODING_DUMP_DIRECTORY=/usr/src/app/geocoding
```

the UID/GID needs write access to the folder pointed to by `GEOCODING_DATA`.

**Comment by untenops** [comment]
Thank you. Just now got to try this out.  Seems to have fixed the issue, except that the pictures that were skipped are still gone.  But I understand this is still beta.  I'll try restarted from scratch and see how it goes this time.
