### ISSUE TITLE
Unable to run job handler 'library/library-refresh' since migration to 1.98.1

### ISSUE THREAD

**Issue by zp4rand0miz31** [immich-app/immich#7814]
### The bug

Hi,

After performing an upgrade to 1.98.1 (from version 1.97.0), I encounter the following error when triggering a full scan of an external library:
```

immich_microservices     | [Nest] 6  - 03/10/2024, 6:39:59 AM   ERROR [JobService] Unable to run job handler (library/library-refresh): TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
immich_microservices     | [Nest] 6  - 03/10/2024, 6:39:59 AM   ERROR [JobService] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
immich_microservices     |     at validateString (node:internal/validators:162:11)
immich_microservices     |     at Object.normalize (node:path:1131:5)
immich_microservices     |     at /usr/src/app/dist/domain/library/library.service.js:262:48
immich_microservices     |     at Array.map (<anonymous>)
immich_microservices     |     at LibraryService.scanAssets (/usr/src/app/dist/domain/library/library.service.js:258:54)
immich_microservices     |     at LibraryService.handleQueueAssetRefresh (/usr/src/app/dist/domain/library/library.service.js:534:24)
immich_microservices     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_microservices     |     at async /usr/src/app/dist/domain/job/job.service.js:137:37
immich_microservices     |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_microservices     |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_microservices     | [Nest] 6  - 03/10/2024, 6:39:59 AM   ERROR [JobService] Object:
immich_microservices     | {
immich_microservices     |   "id": "166e5e9c-9bea-4257-9091-9383230bc41b",
immich_microservices     |   "refreshModifiedFiles": false,
immich_microservices     |   "refreshAllFiles": false
immich_microservices     | }
immich_microservices     | 
```

Not really sure of the consequences of this error, as some indexing seems to oper nonetheless (thumbnail generation does work).

### The OS that Immich Server is running on

ubuntu 20.04, docker compose 

### Version of Immich Server

v1.98.1

### Version of Immich Mobile App

v1.98.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I think it's not relevant as it's a data contract problem between core and jobs components.
```

### Your .env content

```Shell
I think it's not relevant as it's a data contract problem between core and jobs components.
```

### Reproduction steps

```bash
1. docker compose up -d 
2. log in to immich web ui
3. configure an external library
4. trigger a full scan on this external library
5. Observe exception in immich_microservices container logs
...
```

### Additional information

I did not have this problem with immich 1.97.0.

**Comment by bitforker** [comment]
Same for me: Scanning external library no more possible since upgrade to v1.98.1

**Comment by jrasm91** [comment]
This has been fixed.
