### ISSUE TITLE
Error / Crash: y8.p: lateinit property backgroundChannel has not been initialized 

### ISSUE THREAD

**Issue by gabriel20xx** [immich-app/immich#8158]
### The bug

App crashes on phone boot
[app.alextran.immich_2024-03-21T15_52_26.687.log](https://github.com/immich-app/immich/files/14697057/app.alextran.immich_2024-03-21T15_52_26.687.log)

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.99.0

### Version of Immich Mobile App

v1.99.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not needed
```

### Your .env content

```Shell
Not needed
```

### Reproduction steps

```bash
1. Reboot phone
2. Crash dialog appears
```

### Additional information

Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: POCO
[Device Model]: M2012K11AG
[Display]: UQ1A.240205.004
[Android Version]: 14
[Android API Level]: 34
[System Locale]: en_CH_#u-fw-mon-mu-celsius
[Process ID]: 12848
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: app.alextran.immich
[Version Name]: 1.99.0
[Version Code]: 129
[Target SDK]: 33
[Min SDK]: 26
[Error Type]: JVM
[Crash Time]: 2024-03-21T15:52:26.687
[Stack Trace]:
y8.p: lateinit property backgroundChannel has not been initialized
	at app.alextran.immich.BackupWorker.C(Unknown Source:12)
	at app.alextran.immich.BackupWorker.t(Unknown Source:0)
	at f1.a.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8246)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by alextran1502** [comment]
Which phone model is it?

**Comment by gabriel20xx** [comment]
It is a Xiaomi Poco F3

**Comment by alextran1502** [comment]
Does it always crash upon opening?

**Comment by gabriel20xx** [comment]
No, only when there are pending uploads. When closing and opening the app after the error, the error won't appear again. I think the problem lies within the background service of uploading

**Comment by alextran1502** [comment]
Thank you for the report

**Comment by danieldietzler** [comment]
Hey, it's been over a year and we have a completely new backup system. I expect this to be resolved with the new beta timeline, if not please let us know and we can re-open
