### ISSUE TITLE
UND_ERR_SOCKET while uploading 6000 photos. 

### ISSUE THREAD

**Issue by chengguangnan** [immich-app/immich#8300]
### The bug

I got this error while uploading photos. I can't reproduce it. The second run, it has a different error, 'Failed to add assets to album' error, the same as https://github.com/immich-app/immich/issues/8046. 

### The OS that Immich Server is running on

MacOS M1

### Version of Immich Server

1.99.0

### Version of Immich Mobile App

CLI 2.2.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
/
```

### Your .env content

```Shell
/
```

### Reproduction steps

```bash
`time immich upload -r -a <folder>`
```

### Additional information

server log

```
2024-03-27 11:37:22 [Nest] 7  - 03/27/2024, 3:37:22 AM     LOG [MediaService] Successfully generated JPEG video thumbnail for asset dd76d596-d8db-4f21-a4b2-c5b7af9ee3ab
2024-03-27 11:37:22 [Nest] 7  - 03/27/2024, 3:37:22 AM     LOG [MediaService] Successfully generated WEBP image thumbnail for asset 6771ada5-559f-401a-a208-d8fa18c6be62
2024-03-27 11:37:22 [Nest] 7  - 03/27/2024, 3:37:22 AM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset f57cb7c7-0f7f-435e-a76f-c34b73c1ac37
2024-03-27 11:37:05 [Nest] 7  - 03/27/2024, 3:37:05 AM   ERROR [JobService] Unable to run job handler (metadataExtraction/link-live-photos): QueryFailedError: duplicate key value violates unique constraint "UQ_16294b83fa8c0149719a1f631ef"
2024-03-27 11:37:05 [Nest] 7  - 03/27/2024, 3:37:05 AM   ERROR [JobService] QueryFailedError: duplicate key value violates unique constraint "UQ_16294b83fa8c0149719a1f631ef"
2024-03-27 11:37:05     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
2024-03-27 11:37:05     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-27 11:37:05     at async UpdateQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33)
2024-03-27 11:37:05     at async AssetRepository.update (/usr/src/app/dist/infra/repositories/asset.repository.js:193:9)
2024-03-27 11:37:05     at async MetadataService.handleLivePhotoLinking (/usr/src/app/dist/domain/metadata/metadata.service.js:139:9)
2024-03-27 11:37:05     at async /usr/src/app/dist/domain/job/job.service.js:137:36
2024-03-27 11:37:05     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
2024-03-27 11:37:05     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
2024-03-27 11:37:05 [Nest] 7  - 03/27/2024, 3:37:05 AM   ERROR [JobService] Object:
2024-03-27 11:37:05 {
2024-03-27 11:37:05   "id": "34f77b70-df1d-4302-84d7-5bac697fa96f",
2024-03-27 11:37:05   "source": "upload"
2024-03-27 11:37:05 }
2024-03-27 11:37:05 
2024-03-27 11:37:22 [Nest] 7  - 03/27/2024, 3:37:22 AM   ERROR [JobService] Unable to run job handler (metadataExtraction/link-live-photos): QueryFailedError: duplicate key value violates unique constraint "UQ_16294b83fa8c0149719a1f631ef"
2024-03-27 11:37:22 [Nest] 7  - 03/27/2024, 3:37:22 AM   ERROR [JobService] QueryFailedError: duplicate key value violates unique constraint "UQ_16294b83fa8c0149719a1f631ef"
2024-03-27 11:37:22     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
2024-03-27 11:37:22     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-27 11:37:22     at async UpdateQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33)
2024-03-27 11:37:22     at async AssetRepository.update (/usr/src/app/dist/infra/repositories/asset.repository.js:193:9)
2024-03-27 11:37:22     at async MetadataService.handleLivePhotoLinking (/usr/src/app/dist/domain/metadata/metadata.service.js:139:9)
2024-03-27 11:37:22     at async /usr/src/app/dist/domain/job/job.service.js:137:36
2024-03-27 11:37:22     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
2024-03-27 11:37:22     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
2024-03-27 11:37:22 [Nest] 7  - 03/27/2024, 3:37:22 AM   ERROR [JobService] Object:
2024-03-27 11:37:22 {
2024-03-27 11:37:22   "id": "4fe448cd-6fe0-4012-bcdb-9552d17c7ad2",
2024-03-27 11:37:22   "source": "upload"
2024-03-27 11:37:22 }
```

cli log
```
Crawling for assets...
Checking files | ████████████████████████████████████████ | 100% | ETA: 0s | 65s
Found 6503 new files and 11 duplicates
Uploading assets | ██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░ | 34% | ETA: 31m55sB
node:internal/deps/undici/undici:12443
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:12443:11
    at async uploadFile (file:///opt/homebrew/lib/node_modules/@immich/cli/dist/index.js:17924:20)
    at async file:///opt/homebrew/lib/node_modules/@immich/cli/dist/index.js:17883:28
    at async Promise.all (index 1)
    at async uploadFiles (file:///opt/homebrew/lib/node_modules/@immich/cli/dist/index.js:17880:7)
    at async upload (file:///opt/homebrew/lib/node_modules/@immich/cli/dist/index.js:17811:21) {
  cause: SocketError: other side closed
      at Socket.onSocketEnd (node:internal/deps/undici/undici:8994:26)
      at Socket.emit (node:events:531:35)
      at endReadableNT (node:internal/streams/readable:1696:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '::1',
      localPort: 49521,
      remoteAddress: '::1',
      remotePort: 2283,
      remoteFamily: 'IPv6',
      timeout: undefined,
      bytesWritten: 108601573,
      bytesRead: 12937
    }
  }
}

Node.js v21.6.2

________________________________________________________
Executed in  418.73 secs    fish           external
   usr time   68.63 secs  207.00 micros   68.63 secs
   sys time   33.79 secs  818.00 micros   33.78 secs
```

**Comment by HansAndreManfredson** [comment]
Looks like the same problem as #8608 
Did you do a de-duplication of your image library?

You can do that with fclone (https://github.com/pkolaczk/fclones)!
It works pretty well, even with a large image library.

**Comment by chengguangnan** [comment]
I switched to immich-go for uploading.
