### ISSUE TITLE
Machine learning request for facial recognition failed with status 500: Internal Server Error

### ISSUE THREAD

**Issue by sendev1** [immich-app/immich#8455]
### The bug

Hi, I am running https://github.com/imagegenius/docker-immich/pkgs/container/immich image in my docker and I am seeing error 

```
[04/01/24 22:16:15] ERROR    Exception in ASGI application                      
                                                                                
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /app/immich/machine-learning/app/main.py:118 in │
                             │ predict                                         │
                             │                                                 │
                             │   115 │                                         │
                             │   116 │   model = await load(await model_cache. │
                             │       ttl=settings.model_ttl, **kwargs))        │
                             │   117 │   model.configure(**kwargs)             │
                             │ ❱ 118 │   outputs = await run(model.predict, in │
                             │   119 │   return ORJSONResponse(outputs)        │
                             │   120                                           │
                             │   121                                           │
                             │                                                 │
                             │ /app/immich/machine-learning/app/main.py:125 in │
                             │ run                                             │
                             │                                                 │
                             │   122 async def run(func: Callable[..., Any], i │
                             │   123 │   if thread_pool is None:               │
                             │   124 │   │   return func(inputs)               │
                             │ ❱ 125 │   return await asyncio.get_running_loop │
                             │   126                                           │
                             │   127                                           │
                             │   128 async def load(model: InferenceModel) ->  │
                             │                                                 │
                             │ /usr/lib/python3.11/concurrent/futures/thread.p │
                             │ y:58 in run                                     │
                             │                                                 │
                             │ /app/immich/machine-learning/app/models/base.py │
                             │ :59 in predict                                  │
                             │                                                 │
                             │    56 │   │   self.load()                       │
                             │    57 │   │   if model_kwargs:                  │
                             │    58 │   │   │   self.configure(**model_kwargs │
                             │ ❱  59 │   │   return self._predict(inputs)      │
                             │    60 │                                         │
                             │    61 │   @abstractmethod                       │
                             │    62 │   def _predict(self, inputs: Any) -> An │
                             │                                                 │
                             │ /app/immich/machine-learning/app/models/facial_ │
                             │ recognition.py:45 in _predict                   │
                             │                                                 │
                             │   42 │                                          │
                             │   43 │   def _predict(self, image: NDArray[np.u │
                             │   44 │   │   if isinstance(image, bytes):       │
                             │ ❱ 45 │   │   │   decoded_image = cv2.imdecode(n │
                             │      cv2.IMREAD_COLOR)                          │
                             │   46 │   │   else:                              │
                             │   47 │   │   │   decoded_image = image          │
                             │   48 │   │   assert is_ndarray(decoded_image, n │
                             ╰─────────────────────────────────────────────────╯
                             error: OpenCV(4.9.0)                               
                             /io/opencv/modules/imgcodecs/src/loadsave.cpp:801: 
                             error: (-215:Assertion failed) !buf.empty() in     
                             function 'imdecode_'                               
                                                                                
[Nest] 186  - 04/01/2024, 10:16:15 PM   ERROR [JobService] Unable to run job handler (faceDetection/face-detection): Error: Machine learning request for facial recognition failed with status 500: Internal Server Error
[Nest] 186  - 04/01/2024, 10:16:15 PM   ERROR [JobService] Error: Machine learning request for facial recognition failed with status 500: Internal Server Error
    at MachineLearningRepository.predict (/app/immich/server/dist/repositories/machine-learning.repository.js:23:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PersonService.handleDetectFaces (/app/immich/server/dist/services/person.service.js:257:23)
    at async /app/immich/server/dist/services/job.service.js:147:36
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 186  - 04/01/2024, 10:16:15 PM   ERROR [JobService] Object:
{
  "id": "4b153bd4-257b-4aef-9296-cbed72387d04"
}```
any help would be appreciated

### The OS that Immich Server is running on

Raspberry pi os

### Version of Immich Server

v100

### Version of Immich Mobile App

v100

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    mem_limit: 2500m
    environment:
      - PUID=1003
      - PGID=100
      - TZ=America/Chicago
      - DB_HOSTNAME=*************
      - DB_USERNAME=**************
      - DB_PASSWORD=*************
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=**********
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_GPU_ACCELERATION= #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - ./config:/config
      - ./Photo_Library:/photos
    ports:
      - 8088:8080
    restart: unless-stopped
    network_mode: bridge
  # This container requires an external application to be run separately to be run separately.
  # By default, ports for the databases are opened, be careful when deploying it
  # Redis:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
  # PostgreSQL 14:
  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      POSTGRES_USER: ****
      POSTGRES_PASSWORD: ****
      POSTGRES_DB: ****
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    network_mode: bridge
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
Seeing ML related error in container logs
```

**Comment by mertalev** [comment]
I think it means it was sent a 0 byte "image".

**Comment by sendev1** [comment]
seeing more errors like this 
```
[Nest] 186  - 04/03/2024, 12:00:00 AM   ERROR [JobService] Unable to run job handler (thumbnailGeneration/generate-jpeg-thumbnail): Error: Input file is missing: /photos/upload/1ce0bb5f-31b5-408f-a4c5-fdfab5d2d236/42/2e/422e2dab-8730-48a5-b4da-99b1fae88a62.HEIC
[Nest] 186  - 04/03/2024, 12:00:00 AM   ERROR [JobService] Error: Input file is missing: /photos/upload/1ce0bb5f-31b5-408f-a4c5-fdfab5d2d236/42/2e/422e2dab-8730-48a5-b4da-99b1fae88a62.HEIC
    at Sharp.toFile (/app/immich/server/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.resize (/app/immich/server/dist/repositories/media.repository.js:48:14)
    at MediaService.generateThumbnail (/app/immich/server/dist/services/media.service.js:136:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MediaService.handleGenerateJpegThumbnail (/app/immich/server/dist/services/media.service.js:123:28)
    at async /app/immich/server/dist/services/job.service.js:147:36
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 186  - 04/03/2024, 12:00:00 AM   ERROR [JobService] Object:
{
  "id": "59e4bb96-e5d7-474e-a889-537457d8ae0f"
}
[Nest] 186  - 04/03/2024, 12:00:00 AM   ERROR [JobService] Unable to run job handler (thumbnailGeneration/generate-thumbhash-thumbnail): Error: Input file contains unsupported image format
[Nest] 186  - 04/03/2024, 12:00:00 AM   ERROR [JobService] Error: Input file contains unsupported image format
    at Sharp.toBuffer (/app/immich/server/node_modules/sharp/lib/output.js:161:17)
    at MediaRepository.generateThumbhash (/app/immich/server/dist/repositories/media.repository.js:116:14)
    at MediaService.handleGenerateThumbhashThumbnail (/app/immich/server/dist/services/media.service.js:173:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/immich/server/dist/services/job.service.js:147:36
    at async Worker.processJob (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/app/immich/server/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 186  - 04/03/2024, 12:00:00 AM   ERROR [JobService] Object:
{
  "id": "4b153bd4-257b-4aef-9296-cbed72387d04"
}```

**Comment by mertalev** [comment]
I think you might have a few corrupt/invalid images.

**Comment by mertalev** [comment]
Closing this as I don't think this is a bug with machine learning.
