### ISSUE TITLE
Immich thinks jpg is corrupt, but image can be opened in Windows

### ISSUE THREAD

**Issue by yurividal** [immich-app/immich#8510]
### The bug

I have uploaded a few photos from my daughter's play camera. Most of them show fine, but a few are showing as blank images in immich. The log shows this:

````
[Nest] 6  - 04/04/2024, 8:08:23 AM   ERROR [JobService] Unable to run job handler (thumbnailGeneration/generate-jpeg-thumbnail): Error: VipsJpeg: Corrupt JPEG data: 9 extraneous bytes before marker 0xd2
VipsJpeg: Corrupt JPEG data: 9 extraneous bytes before marker 0xd1
[Nest] 6  - 04/04/2024, 8:08:23 AM   ERROR [JobService] Error: VipsJpeg: Corrupt JPEG data: 9 extraneous bytes before marker 0xd2
VipsJpeg: Corrupt JPEG data: 9 extraneous bytes before marker 0xd1
    at Sharp.toFile (/usr/src/app/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.resize (/usr/src/app/dist/repositories/media.repository.js:48:14)
    at MediaService.generateThumbnail (/usr/src/app/dist/services/media.service.js:136:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MediaService.handleGenerateJpegThumbnail (/usr/src/app/dist/services/media.service.js:123:28)
    at async /usr/src/app/dist/services/job.service.js:147:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 04/04/2024, 8:08:23 AM   ERROR [JobService] Object:
{
  "id": "ac647da7-dd40-4e1d-aa05-a85a18834170",
  "source": "upload"
}

[Nest] 6  - 04/04/2024, 8:08:23 AM   ERROR [JobService] Unable to run job handler (thumbnailGeneration/generate-jpeg-thumbnail): Error: VipsJpeg: Corrupt JPEG data: 14 extraneous bytes before marker 0xd0
VipsJpeg: Corrupt JPEG data: 9 extraneous bytes before marker 0xd5
[Nest] 6  - 04/04/2024, 8:08:23 AM   ERROR [JobService] Error: VipsJpeg: Corrupt JPEG data: 14 extraneous bytes before marker 0xd0
VipsJpeg: Corrupt JPEG data: 9 extraneous bytes before marker 0xd5
    at Sharp.toFile (/usr/src/app/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.resize (/usr/src/app/dist/repositories/media.repository.js:48:14)
    at MediaService.generateThumbnail (/usr/src/app/dist/services/media.service.js:136:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MediaService.handleGenerateJpegThumbnail (/usr/src/app/dist/services/media.service.js:123:28)
    at async /usr/src/app/dist/services/job.service.js:147:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 04/04/2024, 8:08:23 AM   ERROR [JobService] Object:
{
  "id": "3526b46a-29ee-4dc0-a998-4be7dad24067",
  "source": "upload"
}````


````

Here is an exa ple file that immich thinks is corrupt:

[

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.100.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Same as example
```

### Your .env content

```Shell
Same as recommended
```

### Reproduction steps

```bash
1.Upload image to immich using the web browser
2. Check logs with  docker logs immich_microservices
```

**Comment by mmomjian** [comment]
This file is indeed corrupt. I don't think it is reasonable for Immich to handle corrupted input images.

```
# convert 319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg 1.jpg
convert-im6.q16: Corrupt JPEG data: 12 extraneous bytes before marker 0xd0 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 10 extraneous bytes before marker 0xd1 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 7 extraneous bytes before marker 0xd3 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 14 extraneous bytes before marker 0xd6 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 10 extraneous bytes before marker 0xd7 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 10 extraneous bytes before marker 0xd0 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 10 extraneous bytes before marker 0xd2 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 12 extraneous bytes before marker 0xd3 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 12 extraneous bytes before marker 0xd4 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 11 extraneous bytes before marker 0xd6 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 9 extraneous bytes before marker 0xd7 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 11 extraneous bytes before marker 0xd1 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 7 extraneous bytes before marker 0xd2 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 2 extraneous bytes before marker 0xd3 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
convert-im6.q16: Corrupt JPEG data: 4 extraneous bytes before marker 0xd4 `319500846-631418f2-926d-4c5f-9d9a-1cba0bea410c.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
......<snip>......
convert-im6.q16: TooManyExceptions (exception processing is suspended) @ warning/exception.c/ThrowException/1054.
```
