### ISSUE TITLE
[BUG] OOM triggered when a lot of items are in the redis queue

### ISSUE THREAD

**Issue by oddlama** [immich-app/immich#861]
This occurred when the 1.30.0 version (presumably) filled the redis queue with geocoding tasks. After upgrading to `1.32.1_51` the immich-server crashes due to OOM with the log from below. Clearing the redis dump fixes the problem. Coincidentally, while the redis queue was full the microservices container didn't crash but consumed 100% of one cpu core.

```
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [NestFactory] Starting Nest application...
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] DatabaseModule dependencies initialized +54ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] JwtModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] ServerInfoModule dependencies initialized +1ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +7ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +146ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] CommunicationModule dependencies initialized +1ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] ImmichJwtModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] BackgroundTaskModule dependencies initialized +1ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] ScheduleTasksModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] DeviceInfoModule dependencies initialized +4ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] AuthModule dependencies initialized +1ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] AlbumModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] UserModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] JobModule dependencies initialized +0ms
[Nest] 1031  - 10/24/2022, 10:15:30 PM     LOG [InstanceLoader] AssetModule dependencies initialized +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RoutesResolver] AppController {/}: +224ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RoutesResolver] UserController {/user}: +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/user, GET} route +2ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/user/info/:userId, GET} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/user/me, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/user, POST} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/user/count, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/user, PUT} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/user/profile-image, POST} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/user/profile-image/:userId, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RoutesResolver] AssetController {/asset}: +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/upload, POST} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/download, GET} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/file, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/thumbnail/:assetId, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/curated-objects, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/curated-locations, GET} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/search-terms, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/search, POST} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/count-by-time-bucket, POST} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/count-by-user-id, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/time-bucket, POST} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/:deviceId, GET} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/assetById/:assetId, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset, DELETE} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/asset/check, POST} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RoutesResolver] AuthController {/auth}: +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/auth/login, POST} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/auth/admin-sign-up, POST} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/auth/validateToken, POST} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/auth/logout, POST} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RoutesResolver] DeviceInfoController {/device-info}: +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/device-info, POST} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/device-info, PATCH} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RoutesResolver] ServerInfoController {/server-info}: +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/server-info, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/server-info/ping, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/server-info/version, GET} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RoutesResolver] AlbumController {/album}: +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/count-by-user-id, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album, POST} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId/users, PUT} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId/assets, PUT} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId, GET} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId/assets, DELETE} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId, DELETE} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId/user/:userId, DELETE} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId, PATCH} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RoutesResolver] JobController {/jobs}: +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/jobs, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/jobs/:jobId, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/jobs/:jobId, PUT} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [NestApplication] Nest application successfully started +18ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [ImmichServer] Running Immich Server in PRODUCTION environment - version 1.32.1
/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:179
    return new ReplyError(string)
           ^
ReplyError: EXECABORT Transaction discarded because of previous errors.
    at parseError (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'exec', args: [] },
  previousErrors: [
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'lrange',
        args: [ 'immich_bull:thumbnail-generation-queue:wait', '0', '-1' ]
      }
    },
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'lrange',
        args: [ 'immich_bull:thumbnail-generation-queue:paused', '0', '-1' ]
      }
    },
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'keys',
        args: [ 'immich_bull:thumbnail-generation-queue:*:limited' ]
      }
    },
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'del',
        args: [
          'immich_bull:thumbnail-generation-queue:wait',
          'immich_bull:thumbnail-generation-queue:paused',
          'immich_bull:thumbnail-generation-queue:meta-paused',
          'immich_bull:thumbnail-generation-queue:delayed',
          'immich_bull:thumbnail-generation-queue:priority',
          'immich_bull:thumbnail-generation-queue:limiter',
          'immich_bull:thumbnail-generation-queue:limiter:index'
        ]
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RoutesResolver] DeviceInfoController {/device-info}: +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/device-info, POST} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/device-info, PATCH} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RoutesResolver] ServerInfoController {/server-info}: +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/server-info, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/server-info/ping, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/server-info/version, GET} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RoutesResolver] AlbumController {/album}: +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/count-by-user-id, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album, POST} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId/users, PUT} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId/assets, PUT} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId, GET} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId/assets, DELETE} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId, DELETE} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId/user/:userId, DELETE} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/album/:albumId, PATCH} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RoutesResolver] JobController {/jobs}: +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/jobs, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/jobs/:jobId, GET} route +0ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [RouterExplorer] Mapped {/jobs/:jobId, PUT} route +1ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [NestApplication] Nest application successfully started +18ms
[Nest] 1031  - 10/24/2022, 10:15:31 PM     LOG [ImmichServer] Running Immich Server in PRODUCTION environment - version 1.32.1
/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:179
    return new ReplyError(string)
           ^
ReplyError: EXECABORT Transaction discarded because of previous errors.
    at parseError (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'exec', args: [] },
  previousErrors: [
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'lrange',
        args: [ 'immich_bull:thumbnail-generation-queue:wait', '0', '-1' ]
      }
    },
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'lrange',
        args: [ 'immich_bull:thumbnail-generation-queue:paused', '0', '-1' ]
      }
    },
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'keys',
        args: [ 'immich_bull:thumbnail-generation-queue:*:limited' ]
      }
    },
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/var/lib/immich/app/server/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'del',
        args: [
          'immich_bull:thumbnail-generation-queue:wait',
          'immich_bull:thumbnail-generation-queue:paused',
          'immich_bull:thumbnail-generation-queue:meta-paused',
          'immich_bull:thumbnail-generation-queue:delayed',
          'immich_bull:thumbnail-generation-queue:priority',
          'immich_bull:thumbnail-generation-queue:limiter',
          'immich_bull:thumbnail-generation-queue:limiter:index'
        ]
      }
    }
  ]
}
Node.js v18.9.0
```

**System**
- Server Version: `v1.32.1_51-dev`

**Comment by bo0tzz** [comment]
My worry was that this would be an issue in our (use of) the queueing library. After a little bit of investigation however, it looks like the `OOM command not allowed when used memory > 'maxmemory'` message is returned by the redis server if its memory usage is too high. `maxmemory` should usually not be limited, however. @oddlama AFAIK you don't use the standard redis container - do you have a (default) value configured for `maxmemory`?

**Comment by oddlama** [comment]
You're absolutely right, it seems like my distribution's default includes a `maxmemory 256MB` statement. I removed that for now.

**Comment by bo0tzz** [comment]
Thanks for investigating!
