### ISSUE TITLE
Files in upload folder fail to move to library

### ISSUE THREAD

**Issue by kevinanderson1** [immich-app/immich#8969]
### The bug

Two photos appear stuck in the upload folder and are not moved to the library folder as expected.

I've rerun the extract metadata jobs and storage migration jobs without success. In the microservices container there are logs that state `TypeError: Cannot read properties of undefined (reading 'Semantic')`.

I can confirm both files are readable by the container and they contain valid exif data.

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

v1.102.2

### Version of Immich Mobile App

v1.102.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Podman Quadlets.
```

### Your .env content

```Shell
I am running Immich using Podman Quadlets and providing the following environment variables to containers.

Environment=DB_DATABASE_NAME=immich
Environment=DB_HOSTNAME=immich-db
Environment=DB_PASSWORD=redacted
Environment=DB_USERNAME=postgres
Environment=LOG_LEVEL=verbose
Environment=NODE_ENV=production
Environment=POSTGRES_DB=immich
Environment=POSTGRES_PASSWORD=redacted
Environment=POSTGRES_USER=postgres
Environment=REDIS_HOSTNAME=immich-redis
```

### Reproduction steps

```bash
1. Upload a photo and observe that the storage template fails to migrate it to the library as expected.
```

### Relevant log output

```shell
I only found related logs in the microservices container. I assume the asset ID is the ending of the log output and the lines before it are the actual error message. If this is incorrect let me know and I can grab the logs again. The logs are for the two assets with ID's of b91969b0-4013-4c72-97c8-2a2855ea26b9 and c175dab0-b86a-40a5-ad6b-d28e41ea6c5b.


immich-microservices[3109713]: [Nest] 2  - 04/20/2024, 5:29:45 PM   ERROR [JobService] Unable to run job handler (metadataExtraction/metadata-extraction): TypeError: Cannot read properties of undefined (reading 'Semantic')
immich-microservices[3109713]: [Nest] 2  - 04/20/2024, 5:29:45 PM   ERROR [JobService] TypeError: Cannot read properties of undefined (reading 'Semantic')
immich-microservices[3109713]:     at MetadataService.applyMotionPhotos (/usr/src/app/dist/services/metadata.service.js:297:32)
immich-microservices[3109713]:     at MetadataService.handleMetadataExtraction (/usr/src/app/dist/services/metadata.service.js:202:20)
immich-microservices[3109713]:     at async /usr/src/app/dist/services/job.service.js:149:36
immich-microservices[3109713]:     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich-microservices[3109713]:     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich-microservices[3109713]: [Nest] 2  - 04/20/2024, 5:29:45 PM   ERROR [JobService] Object:
immich-microservices[3109713]: {
immich-microservices[3109713]:   "id": "c175dab0-b86a-40a5-ad6b-d28e41ea6c5b"
immich-microservices[3109713]: }
immich-microservices[3109713]: [Nest] 2  - 04/20/2024, 5:29:45 PM   ERROR [JobService] Unable to run job handler (metadataExtraction/metadata-extraction): TypeError: Cannot read properties of undefined (reading 'Semantic')
immich-microservices[3109713]: [Nest] 2  - 04/20/2024, 5:29:45 PM   ERROR [JobService] TypeError: Cannot read properties of undefined (reading 'Semantic')
immich-microservices[3109713]:     at MetadataService.applyMotionPhotos (/usr/src/app/dist/services/metadata.service.js:297:32)
immich-microservices[3109713]:     at MetadataService.handleMetadataExtraction (/usr/src/app/dist/services/metadata.service.js:202:20)
immich-microservices[3109713]:     at async /usr/src/app/dist/services/job.service.js:149:36
immich-microservices[3109713]:     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich-microservices[3109713]:     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich-microservices[3109713]: [Nest] 2  - 04/20/2024, 5:29:45 PM   ERROR [JobService] Object:
immich-microservices[3109713]: {
immich-microservices[3109713]:   "id": "b91969b0-4013-4c72-97c8-2a2855ea26b9"
immich-microservices[3109713]: }
immich-microservices[3109713]:
```

**Comment by mmomjian** [comment]
Where did these files come from, i.e. where were they taken? How have you confirmed that the files are valid? Are you able to share one or both of the files in this issue? It seems like Immich is not able to read the file.

**Comment by kevinanderson1** [comment]
They were taken with a Pixel 4. 

I verified that `exiftool` ran against the files without issue. Additionally I opened both of those on my desktop successfully and ran `jpeginfo -c` against them successfully.

```
jpeginfo -c b*
b15684e6-6369-4c32-8ca5-f462ea1c6709.jpg 4032 x 3024 24bit N Exif,XMP,JFIF,ICC        5037602 OK      
bd563e33-525c-4995-9d16-41edb06adf17.jpg 4032 x 3024 24bit N Exif,XMP,JFIF,ICC        7023459 OK
```

I'll have to check with my family member as they are their photos before I can provide them.

**Comment by danieldietzler** [comment]
Where are these files stored? Unreliable network share maybe?

**Comment by kevinanderson1** [comment]
@danieldietzler the files are stored on a btrfs RAID10 array so I don't believe it's an issue with the underlying storage.
