### ISSUE TITLE
Login/password not recognised on android app

### ISSUE THREAD

**Issue by mikerjensen** [immich-app/immich#9013]
### The bug

App was working fine last week. On the weekend i upgraded the server and android app to the latest version and now the app cannot log in (reports 'Error logging you in, check server URL, email and password') but i can log in no problem with the same credentials via web browser.  Log info pasted below. I have Immich set up as a local instance, and oddly, since the weekend Immich cannot be found at the URL i was using before (http://photos.local) but can be found at http://photos.lan - via the web browser either url works fine.

------
Logout failed for [lankamike@gmail.com](mailto:lankamike@gmail.com)

ApiException 400: Socket operation failed: POST /auth/logout (Inner exception: Failed host lookup: 'photos.local')

#0      IOClient.send (package:http/src/io_client.dart:94)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      ApiClient.invokeAPI (package:openapi/api_client.dart:96)
<asynchronous suspension>
#3      AuthenticationApi.logout (package:openapi/api/authentication_api.dart:140)
<asynchronous suspension>
#4      AuthenticationNotifier.logout.<anonymous closure> (package:immich_mobile/modules/login/providers/authentication.provider.dart:106)
<asynchronous suspension>

#0      ApiClient.invokeAPI (package:openapi/api_client.dart:104)
<asynchronous suspension>
#1      AuthenticationApi.logout (package:openapi/api/authentication_api.dart:140)
<asynchronous suspension>
#2      AuthenticationNotifier.logout.<anonymous closure> (package:immich_mobile/modules/login/providers/authentication.provider.dart:106)
<asynchronous suspension>

### The OS that Immich Server is running on

Debian Bullseye

### Version of Immich Server

latest ver - 1.102.0~ynh1

### Version of Immich Mobile App

v1.102.2

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
none
```

### Your .env content

```Shell
not sure where to find this
```

### Reproduction steps

```bash
1. load http://photos.lan  on the android app
2. Responds with login and passwords field for immich
3. After entering the correct details (known to be correct due to logging in on web), the app says error logging in.
...
```

### Relevant log output

```shell
Logout failed for [lankamike@gmail.com](mailto:lankamike@gmail.com)

ApiException 400: Socket operation failed: POST /auth/logout (Inner exception: Failed host lookup: 'photos.local')

#0      IOClient.send (package:http/src/io_client.dart:94)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      ApiClient.invokeAPI (package:openapi/api_client.dart:96)
<asynchronous suspension>
#3      AuthenticationApi.logout (package:openapi/api/authentication_api.dart:140)
<asynchronous suspension>
#4      AuthenticationNotifier.logout.<anonymous closure> (package:immich_mobile/modules/login/providers/authentication.provider.dart:106)
<asynchronous suspension>


#0      ApiClient.invokeAPI (package:openapi/api_client.dart:104)
<asynchronous suspension>
#1      AuthenticationApi.logout (package:openapi/api/authentication_api.dart:140)
<asynchronous suspension>
#2      AuthenticationNotifier.logout.<anonymous closure> (package:immich_mobile/modules/login/providers/authentication.provider.dart:106)
<asynchronous suspension>
```

**Comment by alextran1502** [comment]
Can you try updating your server to v1.102.3?

**Comment by alextran1502** [comment]
can you also use direct IP address please?
