### ISSUE TITLE
Exception : AuditDeletesResponseDto.fromJson

### ISSUE THREAD

**Issue by jeanmatthieud** [immich-app/immich#9052]
### The bug

The mobile app doesn't sync well:
- The files seems uploaded to the server (or at least I did it manually)
- The mobile app display the "not synced" icon on the files

Please note that I'm not sure that the error in the log is linked to the issue, but I discovered this error at the same time that the sync issue appeared

### The OS that Immich Server is running on

TrueNas

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

v1.102.2 build.135

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open the mobile app
2. Sync the files manually
3. Open the logs
```

### Relevant log output

```shell
2024-04-24 09:27:32.498911 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 27 available albums |
2024-04-24 09:27:32.494592 | INFO     | BackupNotifier       | Found 27 local albums |
2024-04-24 09:27:32.436121 | INFO     | AssetNotifier        | Load partner assets: 255ms |
2024-04-24 09:27:32.382549 | SEVERE   | ImmichErrorLogger    | PlatformDispatcher - Catch all | type '_Map<String, dynamic>' is not a subtype of type 'String' in type cast |
#0      _CastListBase.[] (dart:_internal/cast.dart:99)
#1      ListBase.toList (dart:collection/list.dart:225)
#2      AuditDeletesResponseDto.fromJson (package:openapi/model/audit_deletes_response_dto.dart:54)
#3      ApiClient.fromJson (package:openapi/api_client.dart:252)
#4      ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#5      AuditApi.getAuditDeletes (package:openapi/api/audit_api.dart:74)
<asynchronous suspension>
#6      AssetService._getRemoteAssetChanges (package:immich_mobile/shared/services/asset.service.dart:55)
<asynchronous suspension>
#7      SyncService._syncRemoteAssetChanges (package:immich_mobile/shared/services/sync.service.dart:161)
<asynchronous suspension>
#8      SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/shared/services/sync.service.dart:53)
<asynchronous suspension>
#9      AssetService.refreshRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:43)
<asynchronous suspension>
#10     AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:52)
<asynchronous suspension>
```

**Comment by zaggash** [comment]
Seems like it is the same behavior as explained here
https://github.com/immich-app/immich/discussions/9093
