### ISSUE TITLE
addAssetsToAlbum endpoint does not handle repeated IDs

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich#9368]
```bash
curl -X 'PUT' \
  'https://demo.immich.app/api/album/c757a1dc-afae-4cce-8f14-cf0adf5bea8e/assets' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "ids": [
    "7f7e71ab-a630-449d-b7c1-c52fc8b44733",
    "7f7e71ab-a630-449d-b7c1-c52fc8b44733"
  ]
}'
```

Results in
```json
{
  "message": "Failed to add assets to album",
  "error": "Internal Server Error",
  "statusCode": 500
}
```

Because of this server error:
```
demo-immich-server-1            |     at async AlbumService.addAssets (/usr/src/app/dist/services/album.service.js:154:25)] Failed to add assets to album
demo-immich-server-1            | [Nest] 7  - 05/10/2024, 11:52:47 AM   ERROR [QueryFailedError: duplicate key value violates unique constraint "PK_c67bc36fa845fb7b18e0e398180"
demo-immich-server-1            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
demo-immich-server-1            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
demo-immich-server-1            |     at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
demo-immich-server-1            |     at async AlbumRepository.addAssetIds (/usr/src/app/dist/repositories/album.repository.js:216:9)
demo-immich-server-1            |     at async addAssets (/usr/src/app/dist/utils/asset.util.js:29:9)
demo-immich-server-1            |     at async AlbumService.addAssets (/usr/src/app/dist/services/album.service.js:154:25)] QueryFailedError: duplicate key value violates unique constraint "PK_c67bc36fa845fb7b18e0e398180"
```

Repeated asset IDs should probably just get removed by using a Set.

**Comment by eric-barch** [comment]
If this is unclaimed, I'd like to take a stab at it.
