### ISSUE TITLE
Failed to scan new files on external library

### ISSUE THREAD

**Issue by alsvartr** [immich-app/immich#9598]
### The bug

After 1.105.1 when trying to scan new files on external library I get erros from immich-microservices container:
```
[Nest] 7  - 05/19/2024, 1:21:11 PM   ERROR [JobService] Unable to run job handler (library/library-refresh-asset): QueryFailedError: column AssetEntity.isReadOnly does not exist
[Nest] 7  - 05/19/2024, 1:21:11 PM   ERROR [JobService] QueryFailedError: column AssetEntity.isReadOnly does not exist
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.getRawMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1979:26)
    at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getOne (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:711:25)
    at async LibraryService.handleAssetRefresh (/usr/src/app/dist/services/library.service.js:343:37)
    at async /usr/src/app/dist/services/job.service.js:149:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
[Nest] 7  - 05/19/2024, 1:21:11 PM   ERROR [JobService] Object:
{
  "id": "2570d716-c2d4-42c1-ae03-0ac98ce1417c",
  "assetPath": "/mnt/data/2014/IMG_20140810_181241.jpg",
  "ownerId": "4677f99e-4885-4f66-b721-4b4d7067f7ba",
  "force": false
}
```

### The OS that Immich Server is running on

Ubuntu 20.04, container environment

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Standart docker-compose.yml from docs
```

### Your .env content

```Shell
Standart env from docs
```

### Reproduction steps

```bash
1. Add external library
2. Copy new files to it on filesystem
3. Run "Scan new library files"
```

**Comment by bo0tzz** [comment]
The isReadOnly column was removed in 1.104.0. Your microservices container probably failed to update, make sure it is running the latest image.

**Comment by alsvartr** [comment]
> The isReadOnly column was removed in 1.104.0. Your microservices container probably failed to update, make sure it is running the latest image.

My bad, thanks!
