### ISSUE TITLE
Slow cold startup time for mobile app

### ISSUE THREAD

**Issue by justin13888** [immich-app/immich#9707]
### The bug

The immich mobile app on Android takes 6-10 seconds regularly for it to startup.

For some context....
Device: Samsung S22 Ultra
Number of photos: 1000 ish
Misc: I'm using mobile data (20Mbps down)

I think it's fine if it takes a moment for the app to fetch metadata about the photos in the album but it should try to optimistically display all local photos, and previously cached photos (if possible). That'd be a much better user experience.

If any dev is able to give some insight as to the reasons for these behaviours, I would love to know. If the issue isn't isolated, I could make a PR

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. Force close app or restart device
2. Open immich app

It takes 6-10 seconds on the loading screen before rendering any gallery timelines
```

```[tasklist]
### Tasks
```

**Comment by AlmightyFrog** [comment]
I have some more assets in my library (about 180000 in total) and can also confirm that startup time sometimes is all over the place.

What I want to add is, that maybe not pure network connection is the issue as i have same issue when being at home in my 5 GHz WLAN just few meters away from accespoint.

Sometimes load feels like instant, mostly it takes a few seconds, but sometimes it also takes at least a minute. I then switch to use the webinterface in browser on same smartphone which shows pictures instant with no delay.

**Comment by justin13888** [comment]
> I have some more assets in my library (about 180000 in total) and can also confirm that startup time sometimes is all over the place.
> 
> What I want to add is, that maybe not pure network connection is the issue as i have same issue when being at home in my 5 GHz WLAN just few meters away from accespoint.
> 
> Sometimes load feels like instant, mostly it takes a few seconds, but sometimes it also takes at least a minute. I then switch to use the webinterface in browser on same smartphone which shows pictures instant with no delay.
> 
> My guess would be my home server might cause the bottleneck but not sure where, as it is not a banana but also not top tier and mostly idleing:
> 
>     * i5-7500
> 
>     * 32 GB RAM in total; RAM used by immich currently is machine learning uses 800 MB, microservices 1.3 GB, postgres 2,7 GB, redis 30 MB and server 350 MB; still about 15 GB RAM free so can't be the issue.
> 
>     * gigabit lan
> 
>     * OS, assets and database on same SSD
> 
> 
> Best guess would be postgres is the bottleneck but not sure.

Glad to hear I'm not the only one.

Database and library storage may be part of the story but based on my hardware and setup, and the fact that the web app also loads the latest images in the timeline significantly faster than the other images, I'm confident there's definitely room for improvement for the mobile app itself.

For the record, my hardware situation is as follows:

- CPU: AMD Ryzen 7900X
- 64 GB DDR5 RAM
- Storage: 
- 900 Mbps wifi connection

As @AlmightyFrog said, hardware shouldn't be the problem because resources are idling anyways.

Even if I "warmed" up the server by scrolling through the whole timeline, the perceived load speed on the web app on another device is obviously faster for me than that of the mobile app.

A few more observations:
- After not viewing the libraries for a while, the time to first seeing images is visibly slower on both web and mobile
- On mobile app, I have medium-quality images loaded first.
- On web app, it seems to load more images simultaneously than mobile app
- Mobile app clears out images after moving away in timeline

I have a few hypotheses so far:
- Server does a poor job caching lower-quality images used for timeline.
- Mobile app loads a medium-quality image first and so server is blocked by generating the medium-quality image first.
- Mobile app clears loaded photos prematurely

**Comment by justin13888** [comment]
These are a few things I believe should be investigated:
- Server's caching mechanism of generated assets (e.g. thumbnail, medium-quality images) and original assets
- Differences between caching of rendered images in web app and mobile app's timeline

For any devs who worked on Immich, would appreciate any guidance or ideas here!

**Comment by alextran1502** [comment]
The issue is the way we currently use to initial rendered, which we will need to fetch all data from the server in chunk, parse them all then render. We are working towards a refactor to fetch then render then fetch then render to help with the initial "blank state" on slow network

**Comment by SHU-red** [comment]
+1 for this!

- **At home with connection to server:** Immich starts very fast and i like the experience
- **Not at home (e.g. only cellular connection):** Immich starts up slow (feeling like it searches for the server for a long time), which is a bit annoying when quickly trying to send a camera snapshot

So i hope (not being a person knowing much about the technical details) the suggestions above include something like:
- Immich doesnt care if a server is availalble when opened
- Immich tries to open up the app (?cached? thumbnails, local files) as fast as possible being available for views/shares
- "In the background" looks concurrently for a server connection and updates the content in chunks

**Comment by heri3x** [comment]
I'm using the Immich app v1.111.0 build 167 on iOS 17.5.1.
- When Wi-Fi is ON and there's no server available, the app takes 75 seconds to start.
- With Wi-Fi OFF, the app starts immediately.
- The "Automatic foreground backup" and "Automatic background backup" settings don't seem to affect the startup time.

**Comment by ptartarian** [comment]
Was having the same issue. One thing helped is that in network settings on the app, i had as a priority to look for the server on my lan (192.168...) and then to my external domain(immich.example.com), so looking at the logs, the app was searching first for 192 and not finding it(when I'm outside my place not connected to my lan) and timing out, and then resuming the connection to my external domain.
Switching priorities or even removing the 192 entry fixed the issue like in 90% of the time. Since it's still rarely startup slow now I think this ticket is still valid.

**Comment by johansmolinski** [comment]
Is there any work happening on this one? In my opinion, the app should really have a local cache of sort, to load before updating from network.

**Comment by alextran1502** [comment]
@johansmolinski yep, actively working on it before stable release

**Comment by gaaat98** [comment]
Hello, I am affected by the same problem opening the app while the server is unreachable! 
Probably you already know but disabling "Automatic URL Switching" makes the app boot instantly because it doesn't try to perform the server lookup, while with the option enabled the lookup fails multiple times (seven errors/warnings are logged and I assume that each one corresponds to a hostname lookup that waits for its timeout before throwing an exception)

**Comment by jaimetur** [comment]
Me too. This is the only thing that stop me to use Immich as my primary Photo Storage

**Comment by alextran1502** [comment]
Consolidate into #19370

**Comment by DenisMir** [comment]
The slow startup is still valid at least for Android on a Pixel 8 Pro with the latest Android version. Pretty annoying to be honest. The app itself is pretty fast but the startup is damn slow. It takes about 5-10 seconds to open even on local network. (the web application is fast)

**Comment by mpsecondacc** [comment]
I still have this issue on Pixel 7 Pro, latest version - more than 12 secs to load the app - really frustrating

**Comment by joostthehost** [comment]
I was experiencing this issue too, but also remembered that this didn't used to be an issue for me. I also did remember that my external URL had changed in the meantime. Although I updated that in the app, this startup issue was something I only recently noticed.

I now re-set the URLs because in the logs of the app (click account icon in the top right, then logs) I noticed some errors regarding AuthService and local endpoint. After updating the URLs and explicitly setting my local URL to include an http://.. prefix (previously I just had the local IP without http://.. prefix) things were fast again!

Perhaps this works for others too.

**Comment by harveydobson** [comment]
I'm also on Pixel 8 Pro. This is my biggest issue with the app at the moment. Otherwise it works really well. But I find myself having to use Google photos still just to access photos that I might have taken 5 minutes ago, as the app is so incredibly slow to cold start.

**Comment by DalbyTech** [comment]
This is my only issue with Immich, it is super frustrating when I want to quickly show someone a photo on my phone and I have to awkwardly wait 10-15 seconds for it to realise its offline and show me my pictures.

**Comment by joostthehost** [comment]
@harveydobson and @DalbyTech dit you check my comment for a possible solution?
https://github.com/immich-app/immich/issues/9707#issuecomment-4170591934

**Comment by DalbyTech** [comment]
@joostthehost yes I did indeed and no difference :(
This has been an issue for me since I started using Immich at least a year ago.

> Automatic URL switching - enabled
> Local network: http://192.168.1.100:2283
> External network: http://[vpn-ip]:2283

**Comment by joostthehost** [comment]
Anything in the logs of the app that might be helpful? 
Open the app, then click account icon in the top right, then logs.

**Comment by DalbyTech** [comment]
I deleted the logs, set log level to 'finest' and opened the app at 15:00:00, the app displayed thumbnails at around 15:00:12
I then put the log file here with my vpn ip removed if you would like to take a look: pastebin.com/DmnpaQ06

These lines look like they may be relevant:
```
2026-06-07 15:00:15.923804 | severe   | AuthenticationNotifier | Error getting user information from the server [CATCH ALL] | TimeoutException after 0:00:07.000000: Future not completed |
#0      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:1042)
<asynchronous suspension>
#1      AuthNotifier.saveAuthInfo (package:immich_mobile/providers/auth.provider.dart:139)
<asynchronous suspension>
#2      SplashScreenPageState.resumeSession.<anonymous closure> (package:immich_mobile/pages/common/splash_screen.page.dart:321)
<asynchronous suspension>

2026-06-07 15:00:08.907876 | severe   | AuthService          | Cannot resolve endpoint | ApiException 503: Server is not reachable |
```

**Comment by joostthehost** [comment]
Reading through the logs there are a bunch of entries stating 'failed to connect' and reconnections. Like there is perhaps some failed routing in your (internal) network. I would start troubleshooting the connection through your vpn to the machine hosting immich to make sure there are no problems there.

There's no real indication this is (just) an Immich issue in your case.

P.s. exposing your vpn over http is a bad idea.

**Comment by DalbyTech** [comment]
@joostthehost Thanks for taking a look. I'm using Tailscale so all the http traffic is encrypted. Perhaps the lag is a Tailscale thing, as in if I'm not connected to tailscale then the wan ip resolves but times out? It feels like Immich has a timeout value set to about 5 seconds somewhere which is perhaps excessive.
I have noticed that if I turn off Wifi and Mobile data on my phone then Immich loads normally.
