### ISSUE TITLE
Unable to download RAW (NEF) image on iOS client

### ISSUE THREAD

**Issue by roolrz** [immich-app/immich#9799]
### The bug

RAW pictures (mine is NEF) failed to download on iOS client, but works fine on web page

For JPEG images, it works perfectly, on both mobile and web client.

Immich Server: v1.105.1 (Installed through TrueNas scale charts)
Immich Client: v1.105.1 (iOS 17.5.1)

The server is installed from TrueNas Charts, which seems to be using k3s, I don't know if there is a way to get equivalent docker-compose.yaml on k3s.

### The OS that Immich Server is running on

TrueNas

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Not applicable
```

### Your .env content

```Shell
Not applicable
```

### Reproduction steps

```bash
1. Upload an RAW image (NEF in my case) using Mobile client
2. Delete the local image on iPhone's album
3. Try to download it on Mobile client
```

### Relevant log output

```shell
1st logged error

MESSAGE
Error saving downloaded asset

DETAILS
ApiException 400: HTTP connection failed: POST /download/asset/c557ee04-56eb-4b8f-8c52-58c3713c2e72 (Inner exception: Connection closed while receiving data)

#0      IOClient.send.<anonymous closure> (package:http/src/io_client.dart:82)
#1      Stream.handleError.<anonymous closure> (dart:async/stream.dart:931)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:269)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157)
#4      _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:720)
#5      _RootZone.runBinaryGuarded (dart:async/zone.dart:1606)
#6      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#7      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376)
#8      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280)
#9      _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128)
#10     _addErrorWithReplacement (dart:async/stream_pipe.dart:176)
#11     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:274)
#12     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157)
#13     _RootZone.runBinaryGuarded (dart:async/zone.dart:1606)
#14     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#15     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376)
#16     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280)
#17     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:788)
#18     _StreamController._addError (dart:async/stream_controller.dart:666)
#19     _StreamController.addError (dart:async/stream_controller.dart:620)
#20     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1201)
#21     _HttpParser._onDone (dart:_http/http_parser.dart:899)
#22     _RootZone.runGuarded (dart:async/zone.dart:1582)
#23     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392)
#24     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402)
#25     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291)
#26     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792)
#27     _StreamController._closeUnchecked (dart:async/stream_controller.dart:647)
#28     _StreamController.close (dart:async/stream_controller.dart:640)
#29     _Socket._onError (dart:io-patch/socket_patch.dart:2471)
#30     _RootZone.runBinaryGuarded (dart:async/zone.dart:1606)
#31     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#32     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:373)
#33     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280)
#34     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:788)
#35     _StreamController._addError (dart:async/stream_controller.dart:666)
#36     _StreamController.addError (dart:async/stream_controller.dart:620)
#37     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1949)
#38     _RootZone.runBinaryGuarded (dart:async/zone.dart:1606)
#39     _RootZone.bindBinaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1638)
#40     _NativeSocket.reportError (dart:io-patch/socket_patch.dart:1647)
#41     _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1461)
#42     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

FROM
ImageViewerService

STACK TRACE
#0      ApiClient.invokeAPI (package:openapi/api_client.dart:125)
<asynchronous suspension>
#1      ImageViewerService.downloadAssetToDevice (package:immich_mobile/services/image_viewer.service.dart:76)
<asynchronous suspension>
#2      ImageViewerStateNotifier.downloadAsset (package:immich_mobile/providers/asset_viewer/image_viewer_page_state.provider.dart:39)
<asynchronous suspension>

--------------------------------------------------------------------------------
2nd logged error
MESSAGE
PlatformDispatcher - Catch all

DETAILS
Null check operator used on a null value

FROM
ImmichErrorLogger

STACK TRACE
#0      MediaQuery._of (package:flutter/src/widgets/media_query.dart:1187)
#1      MediaQuery.of (package:flutter/src/widgets/media_query.dart:1182)
#2      FToast.showToast (package:fluttertoast/fluttertoast.dart:242)
#3      ImmichToast.show (package:immich_mobile/widgets/common/immich_toast.dart:49)
#4      ImageViewerStateNotifier.downloadAsset (package:immich_mobile/providers/asset_viewer/image_viewer_page_state.provider.dart:53)
<asynchronous suspension>
```

**Comment by jrasm91** [comment]
I believe this issue is fixed on the latest version of the app.
