### ISSUE TITLE
[BUG] 500 Internal Error "Error: Not found: /api/user/count"

### ISSUE THREAD

**Issue by bdr99** [immich-app/immich#984]
**Describe the bug**
Thanks for creating Immich! I'm trying to set up a dev environment so I can contribute. I'm using a VM running Ubuntu Server 22.04. My `docker-compose.yml` and `.env` are unchanged from the defaults, except for setting the `UPLOAD_LOCATION` and `JWT_SECRET`. When I run `make dev`, the containers all seem to start up fine, but when I access http://localhost:3000/ in my browser, I get this error:

![image](https://user-images.githubusercontent.com/2292715/202358841-80553dc9-320c-4a03-aa41-01b78ca89010.png)

In the server logs, I see this:

```
[4:45:07 AM] Starting compilation in watch mode...
docker-immich-microservices-1     |
docker-immich-web-1               |
docker-immich-web-1               |   VITE v3.1.1  ready in 837 ms
docker-immich-web-1               |
docker-immich-web-1               |   ➜  Local:   http://localhost:3000/
docker-immich-web-1               |   ➜  Network: http://172.18.0.7:3000/
docker-immich-web-1               | copy-image-clipboard doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
docker-immich-machine-learning-1  | [4:45:09 AM] Found 0 errors. Watching for file changes.
docker-immich-machine-learning-1  |
docker-immich-machine-learning-1  | 2022-11-17 04:45:09.949291: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
docker-immich-machine-learning-1  | To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
docker-immich-machine-learning-1  | [Nest] 31  - 11/17/2022, 4:45:10 AM     LOG [NestFactory] Starting Nest application...
docker-immich-machine-learning-1  | [Nest] 31  - 11/17/2022, 4:45:10 AM     LOG [ImageClassifier] Running Node TensorFlow Version : 3.19.0
docker-immich-machine-learning-1  | [Nest] 31  - 11/17/2022, 4:45:10 AM     LOG [ObjectDetection] Running Node TensorFlow Version : 3.19.0
docker-immich-machine-learning-1  | [Nest] 31  - 11/17/2022, 4:45:10 AM     LOG [InstanceLoader] AppModule dependencies initialized +3ms
docker-immich-machine-learning-1  | [Nest] 31  - 11/17/2022, 4:45:10 AM     LOG [InstanceLoader] ImageClassifierModule dependencies initialized +0ms
docker-immich-machine-learning-1  | [Nest] 31  - 11/17/2022, 4:45:10 AM     LOG [InstanceLoader] ObjectDetectionModule dependencies initialized +1ms
docker-immich-machine-learning-1  | [Nest] 31  - 11/17/2022, 4:45:10 AM     LOG [RoutesResolver] ImageClassifierController {/image-classifier}: +5ms
docker-immich-machine-learning-1  | [Nest] 31  - 11/17/2022, 4:45:10 AM     LOG [RouterExplorer] Mapped {/image-classifier/tag-image, POST} route +3ms
docker-immich-machine-learning-1  | [Nest] 31  - 11/17/2022, 4:45:10 AM     LOG [RoutesResolver] ObjectDetectionController {/object-detection}: +0ms
docker-immich-machine-learning-1  | [Nest] 31  - 11/17/2022, 4:45:10 AM     LOG [RouterExplorer] Mapped {/object-detection/detect-object, POST} route +1ms
docker-immich-machine-learning-1  | [Nest] 31  - 11/17/2022, 4:45:10 AM     LOG [NestApplication] Nest application successfully started +2ms
docker-immich-machine-learning-1  | [Nest] 31  - 11/17/2022, 4:45:10 AM     LOG [IMMICH MICROSERVICES] Running Immich Machine Learning in DEVELOPMENT environment
docker-immich-microservices-1     | [4:45:12 AM] Found 0 errors. Watching for file changes.
docker-immich-microservices-1     |
docker-immich-server-1            | [4:45:13 AM] Found 0 errors. Watching for file changes.
docker-immich-server-1            |
docker-immich-server-1            | Debugger listening on ws://0.0.0.0:9230/fb7ff0b4-896e-41e5-977a-1fd769b201ba
docker-immich-server-1            | For help, see: https://nodejs.org/en/docs/inspector
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [NestFactory] Starting Nest application...
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] DatabaseModule dependencies initialized +48ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] JwtModule dependencies initialized +1ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +5ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +98ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG Initialising Reverse Geocoding
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] ImmichJwtModule dependencies initialized +35ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] ImmichConfigModule dependencies initialized +0ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] CommunicationModule dependencies initialized +1ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:14 AM     LOG [InstanceLoader] MicroservicesModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [NestFactory] Starting Nest application...
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] DatabaseModule dependencies initialized +57ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] DownloadModule dependencies initialized +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] JwtModule dependencies initialized +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +8ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +157ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] CommunicationModule dependencies initialized +2ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] ImmichJwtModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] BackgroundTaskModule dependencies initialized +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] ScheduleTasksModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] ImmichConfigModule dependencies initialized +2ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] DeviceInfoModule dependencies initialized +3ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] ServerInfoModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] OAuthModule dependencies initialized +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] AlbumModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] UserModule dependencies initialized +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] JobModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] SystemConfigModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] AssetModule dependencies initialized +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [InstanceLoader] AuthModule dependencies initialized +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RoutesResolver] AppController {/}: +516ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RoutesResolver] UserController {/user}: +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/user, GET} route +3ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/user/info/:userId, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/user/me, GET} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/user, POST} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/user/count, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/user/:userId, DELETE} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/user/:userId/restore, POST} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/user, PUT} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/user/profile-image, POST} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/user/profile-image/:userId, GET} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RoutesResolver] AssetController {/asset}: +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/upload, POST} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/download/:assetId, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/download-library, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/file/:assetId, GET} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/thumbnail/:assetId, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/curated-objects, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/curated-locations, GET} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/search-terms, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/search, POST} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/count-by-time-bucket, POST} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/count-by-user-id, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/time-bucket, POST} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/:deviceId, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/assetById/:assetId, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/assetById/:assetId, PUT} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset, DELETE} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/check, POST} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/asset/exist, POST} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RoutesResolver] AuthController {/auth}: +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/auth/login, POST} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/auth/admin-sign-up, POST} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/auth/validateToken, POST} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/auth/logout, POST} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RoutesResolver] OAuthController {/oauth}: +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/oauth/config, POST} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/oauth/callback, POST} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RoutesResolver] DeviceInfoController {/device-info}: +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/device-info, POST} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/device-info, PATCH} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RoutesResolver] ServerInfoController {/server-info}: +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/server-info, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/server-info/ping, GET} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/server-info/version, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/server-info/stats, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RoutesResolver] AlbumController {/album}: +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/album/count-by-user-id, GET} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/album, POST} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/album/:albumId/users, PUT} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/album/:albumId/assets, PUT} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/album, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/album/:albumId, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/album/:albumId/assets, DELETE} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/album/:albumId, DELETE} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/album/:albumId/user/:userId, DELETE} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/album/:albumId, PATCH} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/album/:albumId/download, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RoutesResolver] JobController {/jobs}: +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/jobs, GET} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/jobs/:jobId, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/jobs/:jobId, PUT} route +1ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RoutesResolver] SystemConfigController {/system-config}: +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/system-config, GET} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [RouterExplorer] Mapped {/system-config, PUT} route +0ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [NestApplication] Nest application successfully started +51ms
docker-immich-server-1            | [Nest] 29  - 11/17/2022, 4:45:15 AM     LOG [ImmichServer] Running Immich Server in DEVELOPMENT environment - version 1.35.0
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:21 AM     LOG [NestApplication] Nest application successfully started +7453ms
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:21 AM     LOG [ImmichMicroservice] Running Immich Microservices in DEVELOPMENT environment - version 1.35.0
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:21 AM     LOG Reverse Geocoding Initialised
docker-immich-microservices-1     | [Nest] 29  - 11/17/2022, 4:45:24 AM     LOG checksum generation done!
docker-immich-web-1               | Not found: /api/user/count
docker-immich-web-1               | Error: Not found: /api/user/count
docker-immich-web-1               |     at resolve (file:///usr/src/app/node_modules/@sveltejs/kit/src/runtime/server/index.js:267:13)
docker-immich-web-1               |     at Object.handle (/usr/src/app/src/hooks.server.ts:4:14)
docker-immich-web-1               |     at respond (file:///usr/src/app/node_modules/@sveltejs/kit/src/runtime/server/index.js:295:40)
docker-immich-web-1               |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
docker-immich-web-1               |     at async file:///usr/src/app/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
```

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Clone the repo
2. Run `make dev`
3. Access http://localhost:3000/ in browser
4. See the error

**Expected behavior**
Expected dev instance to run properly.

**Screenshots**
See above

**System**
- Phone OS [iOS, Android]: N/A
- Server Version: latest commit from main branch
- Mobile App Version: N/A

**Additional context**
Please let me know if any additional info is needed.

**Comment by alextran1502** [comment]
@bdr99 The port is 2283, not 3000 :)

**Comment by alextran1502** [comment]
@bdr99 Here is the post-installation guide for more information https://immich.app/docs/usage/post-installation

**Comment by bdr99** [comment]
Haha, thanks, that worked! I was following this guide to set up a dev environment: https://immich.app/docs/contribution-guidelines and didn't see it documented there.

**Comment by alextran1502** [comment]
@bdr99 No problem, is there anything we should improve in the documentation, please feel free to point it out

**Comment by bdr99** [comment]
@alextran1502 I opened a PR here with a few small improvements to that page: https://github.com/immich-app/immich/pull/985
